# Display All Tables

This notebook loads the latest export and displays all tables in a loop with filtering options.

## Import Required Libraries

In [11]:
import pandas as pd
from pathlib import Path
from IPython.display import display, HTML

# Import the export reader library
from scraper.export_reader import load_latest_export

## Load the Export Data

In [12]:
# Load the latest export
reader = load_latest_export()
reader.print_summary()

# Get all tables as a dataframe
df_tables = reader.get_all_tables_dataframe()
print(f"\n📊 Total tables to display: {len(df_tables)}\n")

# Display a preview
display(df_tables.head())

Loading latest export: processed_export_1779286564.json
============================================================
EXPORT SUMMARY
============================================================
Total documents: 283
Export file: /home/jgrzyb/Documents/Python/ai4es-oa-paper-scrapper/notebooks/paper_pipeline_data/exports/processed_export_1779286564.json

Documents by source:
source
pmc      264
arxiv     19

Total tables: 2387
Total images: 1727

Document sections:
  Min sections: 0
  Max sections: 49
  Avg sections: 17.5

============================================================

📊 Total tables to display: 2387

,paper_id,section,table_index,global_index,csv_path
0,0903.2017,References,0,0,tables/0903.2017/table_0.csv
1,0903.2017,Radius of the double occupancies,0,1,tables/0903.2017/table_1.csv
2,0903.2017,Expansion from the harmonic trap: Reduction of...,0,2,tables/0903.2017/table_2.csv
3,PMC6004667,Results,0,0,tables/PMC6004667/table_0.csv
4,PMC6004667,Results,1,1,tables/PMC6004667/table_1.csv

## Display Tables in a Loop

In [13]:
def show_table(index):
    """Display a specific table from the tables dataframe."""
    if index < 0 or index >= len(df_tables):
        print('Index out of range')
        return
    
    row = df_tables.iloc[index]
    
    # Display metadata
    header = f"""
    <div style="background-color: #f0f0f0; padding: 10px; border-radius: 5px; margin-bottom: 10px;">
        <b>Table #{index + 1}</b> | Paper: {row['paper_id']} | Section: {row['section']} | Index: {row['table_index']}
    </div>
    """
    display(HTML(header))
    
    # Load and display the table
    try:
        df = reader.load_table_csv(row['csv_path'])
        display(df)
    except FileNotFoundError as e:
        print(f"❌ Error loading table: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
    
    print("-" * 80)

# Display all tables in a loop
count = min(20, len(df_tables))
print(f"Starting to display {count} tables...\n")

for i in range(count):
    try:
        show_table(i)
    except Exception as e:
        print(f"Error displaying table {i}: {e}")
        continue

print(f"\n✅ Finished displaying all {count} tables!")

Starting to display 20 tables...

Empty DataFrame
Columns: [Unnamed: 0, H 0 = − t ∑ i = 1 L − 1 ( c i + 1 , σ † c i , σ + h . c . ) + U ∑ i = 1 L n i , ↑ n i , ↓ . H_{0}=-t\sum_{i=1}^{L-1}(c_{i+1,\sigma}^{\dagger}c_{i,\sigma}+\mathrm{h.c.})+U\sum_{i=1}^{L}n_{i,\uparrow}n_{i,\downarrow}\,., Unnamed: 2, (1)]
Index: []

--------------------------------------------------------------------------------

Empty DataFrame
Columns: [Unnamed: 0, R d 2 = 1 N d ​ ∑ i = 1 L i 2 ​ ⟨ d ~ i ⟩ superscript subscript 𝑅 𝑑 2 1 subscript 𝑁 𝑑 superscript subscript 𝑖 1 𝐿 superscript 𝑖 2 delimited-⟨⟩ subscript ~ 𝑑 𝑖 R_{d}^{2}=\frac{1}{N_{d}}\sum_{i=1}^{L}i^{2}\langle\tilde{d}_{i}\rangle, Unnamed: 2, (2)]
Index: []

--------------------------------------------------------------------------------

,Unnamed: 0,S x = 2 ​ ( τ ) subscript 𝑆 𝑥 2 𝜏 \displaystyle S_{x=2}(\tau),< \displaystyle<,"0.1 ​ S x = 2 ​ ( τ = 0 ) 0.1 subscript 𝑆 𝑥 2 𝜏 0 \displaystyle 0.1\,S_{x=2}(\tau=0)",Unnamed: 4,(3)
0,NaN,S x = 3 ​ ( τ ) subscript 𝑆 𝑥 3 𝜏 \displaystyl...,< \displaystyle<,0.21 ​ S x = 3 ​ ( τ = 0 ) . 0.21 subscript 𝑆 ...,NaN,NaN

--------------------------------------------------------------------------------

,Study,Prevalence (%) [95% CI],% Weight,Country,Sample Size
0,Tetranychus urticae,NaN,NaN,NaN,NaN
1,Astarita et al. [33],40.0,9.6,70.4,1.21
2,Astarita et al. [34],78.3,66.3,90.2,3.30
3,Astarita et al. [35],6.0,4.5,7.5,4.77
4,Delgado et al. [31],66.7,47.8,85.5,2.24
5,Jee et al. [29],32.0,19.1,44.9,3.12
6,Jeebhay et al. [28],22.1,16.2,28.0,4.32
7,Johansson et al. [27],25.8,10.4,41.2,2.72
8,Kim et al. [8],9.9,8.7,11.1,4.78
9,Kim et al. [22],4.3,3.9,4.8,4.80
10,Kim et al. [25],16.6,13.2,19.9,4.63
11,Kim et al. [24],19.8,18.0,21.7,4.75
12,Kronqvist et al. [21],24.0,15.4,32.5,3.89
13,Lee et al. [20],28.0,26.9,29.0,4.78
14,Navarro et al. [16],25.3,19.8,30.8,4.38
15,Seedat et al. [15],46.0,32.2,59.8,2.98
16,Sub-total,NaN,NaN,NaN,NaN
17,D + L pooled prevalence,27.0,20.5,33.5,56.67
18,I–V pooled prevalence,8.7,8.4,9.1,NaN
19,Panonychus citri,NaN,NaN,NaN,NaN
20,Ashida et al. [32],83.3,62.2,104.4,1.98
21,Kim et al. [26],21.8,19.8,23.8,4.74
22,Kim et al. [22],15.6,14.8,16.4,4.79
23,Kim et al. [23],14.3,13.5,15.2,4.79
24,Kim et al. [14],23.0,14.8,31.2,3.94
25,Kim et al. [9],16.6,11.2,22.0,4.39
26,Lee et al. [19],14.2,12.1,16.3,4.73
27,Lee et al. [18],1.3,0.6,2.0,4.79
28,Min et al. [17],14.9,11.3,18.5,4.61
29,Sub-total,NaN,NaN,NaN,NaN
30,D + L pooled prevalence,18.2,12.4,24.0,38.76
31,I–V pooled prevalence,10.3,9.9,10.8,NaN
32,Panonychus ulmi,NaN,NaN,NaN,NaN
33,Kim et al. [25],23.2,19.4,27.1,4.58
34,Sub-total,NaN,NaN,NaN,NaN
35,D + L pooled prevalence,23.2,19.4,27.1,4.58
36,I–V pooled prevalence,23.2,19.4,27.1,NaN
37,Overall,NaN,NaN,NaN,NaN
38,D + L pooled prevalence,22.9,19.0,26.8,100.00
39,I–V pooled prevalence,9.5,9.2,9.7,NaN

--------------------------------------------------------------------------------

,Unnamed: 0,Heterogeneity statistic,Degrees of freedom,p,I-squared** (%),Tau-squared
0,Tetranychus urticae,2177.04,14,< 0.001,99.4,0.0137
1,Panonychus citri,1092.73,8,< 0.001,99.3,0.0070
2,Panonychus ulmi,0.00,0,NaN,NaN,0.0000
3,Overall,3351.78,24,< 0.001,99.3,0.0081

--------------------------------------------------------------------------------

,Unnamed: 0,N,Number of studies,Prevalence (%),95% CI,Heterogeneity statistic (Q),Degrees of freedom,I2 (%)
0,All studies,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Overall,"40,908",25.0,23.0,19.0–27.0,2242.56,24.0,98.80
2,Patient population,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Symptomatic,9180,8.0,44.0,35.0–53.0,151.00,7.0,95.40
4,Mixed,"31,728",17.0,15.0,12.0–20.0,1354.00,16.0,98.82

--------------------------------------------------------------------------------

,Study,Monosensitized prevalence (%) [95% CI],% Weight,Country,Sample size
0,Tetranychus urticae,NaN,NaN,NaN,NaN
1,Astarita et al. [34],74.0,61.0,87.0,2.26
2,Astarita et al. [35],2.1,1.0,3.0,10.23
3,Jee et al. [29],2.0,− 2.0,6.0,7.79
4,Jeebhay et al. [28],6.0,2.0,9.0,8.35
5,Kim et al. [25],8.6,6.0,11.0,9.10
6,Kim et al. [24],0.7,0.0,1.0,10.39
7,Kronqvist et al. [21],11.0,5.0,18.0,5.45
8,Lee et al. [20],5.0,5.0,6.0,10.36
9,Navarro et al. [16],7.0,3.0,10.0,8.53
10,Sub-total,NaN,NaN,NaN,NaN
11,D + L pooled prevalence,7.0,5.0,10.0,72.60
12,I–V pooled prevalence,2.0,2.0,3.0,NaN
13,Panonychus citri,NaN,NaN,NaN,NaN
14,Kim et al. [8],8.8,7.0,10.0,10.00
15,Kim et al. [9],9.9,6.0,14.0,7.31
16,Lee et al. [19],2.2,1.0,3.0,10.24
17,Sub-total,NaN,NaN,NaN,NaN
18,D + L pooled prevalence,7.0,1.0,12.0,27.54
19,I–V pooled prevalence,4.0,4.0,5.0,NaN
20,Overall,NaN,NaN,NaN,NaN
21,D + L pooled prevalence,7.0,5.0,9.0,100.00
22,I–V pooled prevalence,3.0,2.0,3.0,NaN

--------------------------------------------------------------------------------

,Study,Prevalence (%) [95% CI],% Weight,Country,Sample Size
0,Tetranychus urticae,NaN,NaN,NaN,NaN
1,Astarita et al. [33],40.0,9.6,70.4,1.21
2,Astarita et al. [34],78.3,66.3,90.2,3.30
3,Astarita et al. [35],6.0,4.5,7.5,4.77
4,Delgado et al. [31],66.7,47.8,85.5,2.24
5,Jee et al. [29],32.0,19.1,44.9,3.12
6,Jeebhay et al. [28],22.1,16.2,28.0,4.32
7,Johansson et al. [27],25.8,10.4,41.2,2.72
8,Kim et al. [8],9.9,8.7,11.1,4.78
9,Kim et al. [22],4.3,3.9,4.8,4.80
10,Kim et al. [25],16.6,13.2,19.9,4.63
11,Kim et al. [24],19.8,18.0,21.7,4.75
12,Kronqvist et al. [21],24.0,15.4,32.5,3.89
13,Lee et al. [20],28.0,26.9,29.0,4.78
14,Navarro et al. [16],25.3,19.8,30.8,4.38
15,Seedat et al. [15],46.0,32.2,59.8,2.98
16,Sub-total,NaN,NaN,NaN,NaN
17,D + L pooled prevalence,27.0,20.5,33.5,56.67
18,I–V pooled prevalence,8.7,8.4,9.1,NaN
19,Panonychus citri,NaN,NaN,NaN,NaN
20,Ashida et al. [32],83.3,62.2,104.4,1.98
21,Kim et al. [26],21.8,19.8,23.8,4.74
22,Kim et al. [22],15.6,14.8,16.4,4.79
23,Kim et al. [23],14.3,13.5,15.2,4.79
24,Kim et al. [14],23.0,14.8,31.2,3.94
25,Kim et al. [9],16.6,11.2,22.0,4.39
26,Lee et al. [19],14.2,12.1,16.3,4.73
27,Lee et al. [18],1.3,0.6,2.0,4.79
28,Min et al. [17],14.9,11.3,18.5,4.61
29,Sub-total,NaN,NaN,NaN,NaN
30,D + L pooled prevalence,18.2,12.4,24.0,38.76
31,I–V pooled prevalence,10.3,9.9,10.8,NaN
32,Panonychus ulmi,NaN,NaN,NaN,NaN
33,Kim et al. [25],23.2,19.4,27.1,4.58
34,Sub-total,NaN,NaN,NaN,NaN
35,D + L pooled prevalence,23.2,19.4,27.1,4.58
36,I–V pooled prevalence,23.2,19.4,27.1,NaN
37,Overall,NaN,NaN,NaN,NaN
38,D + L pooled prevalence,22.9,19.0,26.8,100.00
39,I–V pooled prevalence,9.5,9.2,9.7,NaN

--------------------------------------------------------------------------------

,Unnamed: 0,Heterogeneity statistic,Degrees of freedom,p,I-squared** (%),Tau-squared
0,Tetranychus urticae,2177.04,14,< 0.001,99.4,0.0137
1,Panonychus citri,1092.73,8,< 0.001,99.3,0.0070
2,Panonychus ulmi,0.00,0,NaN,NaN,0.0000
3,Overall,3351.78,24,< 0.001,99.3,0.0081

--------------------------------------------------------------------------------

,Unnamed: 0,N,Number of studies,Prevalence (%),95% CI,Heterogeneity statistic (Q),Degrees of freedom,I2 (%)
0,All studies,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Overall,"40,908",25.0,23.0,19.0–27.0,2242.56,24.0,98.80
2,Patient population,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Symptomatic,9180,8.0,44.0,35.0–53.0,151.00,7.0,95.40
4,Mixed,"31,728",17.0,15.0,12.0–20.0,1354.00,16.0,98.82

--------------------------------------------------------------------------------

,Study,Monosensitized prevalence (%) [95% CI],% Weight,Country,Sample size
0,Tetranychus urticae,NaN,NaN,NaN,NaN
1,Astarita et al. [34],74.0,61.0,87.0,2.26
2,Astarita et al. [35],2.1,1.0,3.0,10.23
3,Jee et al. [29],2.0,− 2.0,6.0,7.79
4,Jeebhay et al. [28],6.0,2.0,9.0,8.35
5,Kim et al. [25],8.6,6.0,11.0,9.10
6,Kim et al. [24],0.7,0.0,1.0,10.39
7,Kronqvist et al. [21],11.0,5.0,18.0,5.45
8,Lee et al. [20],5.0,5.0,6.0,10.36
9,Navarro et al. [16],7.0,3.0,10.0,8.53
10,Sub-total,NaN,NaN,NaN,NaN
11,D + L pooled prevalence,7.0,5.0,10.0,72.60
12,I–V pooled prevalence,2.0,2.0,3.0,NaN
13,Panonychus citri,NaN,NaN,NaN,NaN
14,Kim et al. [8],8.8,7.0,10.0,10.00
15,Kim et al. [9],9.9,6.0,14.0,7.31
16,Lee et al. [19],2.2,1.0,3.0,10.24
17,Sub-total,NaN,NaN,NaN,NaN
18,D + L pooled prevalence,7.0,1.0,12.0,27.54
19,I–V pooled prevalence,4.0,4.0,5.0,NaN
20,Overall,NaN,NaN,NaN,NaN
21,D + L pooled prevalence,7.0,5.0,9.0,100.00
22,I–V pooled prevalence,3.0,2.0,3.0,NaN

--------------------------------------------------------------------------------

,Study,Type of study,Patients,Control group
0,I. Psychiatric comorbidity in CU patients (stu...,NaN,NaN,NaN
1,1. Juhlin [18],Cohort study,330 CU patients,No
2,2. Pulimood et al. [19],Cohort study,20 CU patients,No
3,3. Picardi et al. [20],Cohort study,29 CU patients,No
4,4. Picardi et al. [21],Cohort study,16 CU patients,No
5,5. Staubach et al. [22],Cohort study,100 CU patients,No
6,6. Mehta et al. [23],Cohort study,50 CU patients,No
7,7. Sorour et al. [24],Cohort study,110 CU patients,No
8,II. Psychiatric comorbidity in CU patients (st...,NaN,NaN,NaN
9,8. Uguz et al. [26],Case–control,89 CU patients,60 individuals
10,9. Atefi et al. [25],Case–control,30 CU patients,30 individuals
11,10. Chu et al. [17],Case–control,"177,879 CU patients","996,356 individuals"
12,11. Staubach et al. [27],Case–control,100 CU patients,96 individuals
13,12. Ozkan et al. [28],Case–control,84 CU patients,75 individuals
14,13. Lapi et al. [29],Case–control,3489 CU patients,"1,714,746 individuals"
15,III. Psychiatric comorbidity in CU patients (s...,NaN,NaN,NaN
16,14. Calıkusu et al. [31],Case–control,31 CU patients,31 patients with psychogenic excoriation (PE)
17,15. Yang et al. [30],Case–control,75 CU outpatients,133 patients with tinea pedis
18,IV. Comorbidity with specific psychiatric diso...,NaN,NaN,NaN
19,16. Demet et al. [33],Cohort study,7 CU,No
20,17. Sukan et al. [34],Case–control,"50 CU patients, 50 vitiligo patients",50 individuals
21,18. Chung et al. [32],Case–control,100 CU patients,60 patients with allergy
22,19. Bashir et al. [36],Cohort study,3 CU patients,No
23,20. Tuna et al. [35],Case–control,130 CU patients,100 individuals
24,V. Case reports–case series—psychiatric interv...,NaN,NaN,NaN
25,21. Hashiro [37],Case report,1 CU patient with anxiety-depressive disorder,No
26,22. Gupta et al. [39],Case series,5 patients with PTSD diagnosed with CU,No
27,23. Gupta et al. [38],Case series,2 CU patients with panic disorder,No
28,VI. Other studies,NaN,NaN,NaN
29,24. Seyhan et al. [40],Cohort study,636 dermatologic patients,No
30,25. Perugi et al. [41],Cohort study,347 patients with bipolar disorder,No

--------------------------------------------------------------------------------

             Unnamed: 0  CU patients CU patients with psychiatric comorbidity
0           Juhlin [18]          NaN                                      NaN
1          Cohort study        330.0                                       53
2  Pulimood et al. [19]          NaN                                      NaN
3          Cohort study         20.0                                       15
4   Picardi et al. [20]          NaN                                      NaN
5          Cohort study         29.0                                       10
6  Staubach et al. [22]          NaN                                      NaN
7          Cohort study        100.0                                       48
8                 Total        479.0                                      126
9     Pooled prevalence          NaN                                    26.3%

--------------------------------------------------------------------------------

            Unnamed: 0    Chronic urticaria patients Control individuals
0                  All  With psychiatric comorbidity                 All
1     Uguz et al. [26]                           NaN                 NaN
2   Case–control study                            89                  44
3    Atefi et al. [25]                           NaN                 NaN
4   Case–control study                            30                  19
5      Chu et al. [17]                           NaN                 NaN
6   Case–control study                       177,879              56,195
7                Total                       177,998              56,258
8                 119#                           63#                 90#
9    Pooled prevalence                           NaN              31.6%*
10                 NaN                    52.9%#, **                 NaN

--------------------------------------------------------------------------------

,DSM-5 classification,PatientsN/all CU patients,ControlaN/all healthy controls,p-value*
0,Prevalence per study,Pooled prevalence (%),Prevalence per study,Pooled prevalence (%)
1,"Sleep–wake disorders (e.g., insomnia disorder,...",57/110 [24]31/130 [35],88/240 (36.7%),12/100 [35]
2,Anxiety disorders (e.g. generalized anxiety di...,30/100 [22]2/50 [23]48/110 [24]24/30 [25]39/89...,197/644 (30.6%),13/30 [25]7/64 [26]
3,"Mood disorders (major depressive disorder, dys...",12/20 [19]17/100 [22]16/50 [23]39/110 [24]15/3...,195/664 (29.4%),5/30 [25]3/64 [26]
4,Trauma and stressor-related disorders (e.g. po...,5/100 [22]1/31 [31]34/100 [32],40/231 (17.3%),–
5,"Somatic symptom and related disorders (e.g., s...",17/100 [22]21/30 [25]11/100 [27]5/84 [28],54/314 (17.2%),12/30 [25]
6,Obsessive–compulsive and related disorders,4/100 [22]1/50 [23]3/110 [24]23/89 [26]3/31 [3...,36/387 (9.3%),1/64 [26]
7,Substance-related and addictive disorders (e.g...,5/100 [22]1/50 [23],6/150 (4%),–

--------------------------------------------------------------------------------

,First author Year (Ref.),Sample size (T/C),"Age, (T/C)",Intervention,Intervention duration,Outcomes
0,Gerasimov 2010,43/47,25.6 ± 7.7/24.1 ± 6.3 months,T: 1.0 × 1010 colony‐forming units of Lactobac...,8 weeks,SCORAD
1,C: 1.0 × 1010 colony‐forming units placebo twi...,NaN,NaN,NaN,NaN,NaN
2,Wu 2011,27/27,7.8 ± 3.5/6.9 ± 3.4 years,T: 475 mg fructo‐oligosaccharide plus 25 mg li...,8 weeks,SCORAD
3,C: 475 mg fructo‐oligosaccharide plus 25 mg co...,NaN,NaN,NaN,NaN,NaN
4,Han 2012,58/60,4.6 ± 3.3/5.1 ± 3.3 years,T: 0.5 × 1010 colony‐forming units of L. plant...,12 weeks,SCORAD
5,C: 0.5 × 1010 colony‐forming units placebo twi...,NaN,NaN,NaN,NaN,NaN
6,Wang 2015,51/53,8.34 ± 3.80/8.04 ± 3.97 years,T: 4 × 109 colony‐forming units of a mixture o...,3 months,SCORAD
7,C: 4 × 109 colony‐forming units placebo once d...,NaN,NaN,NaN,NaN,NaN
8,Navarro‐López 2017,26/24,9.35 ± 3.58/8.96 ± 3.94 years,T: 1.0 × 109 colony‐forming units of a mixture...,12 weeks,SCORAD
9,C: 1.0 × 109 colony‐forming units placebo (mal...,NaN,NaN,NaN,NaN,NaN
10,Plummer 2019,118/137,Preterm infants (Birth to discharge from hospi...,T: 1.0 × 109 colony‐forming units of a mixture...,2 years,SCORAD
11,C: placebo (maltodextrin) once daily,NaN,NaN,NaN,NaN,NaN
12,Jeong 2020,33/33,5.67 ± 3.30/5.33 ± 2.53 years,T: 1.0 × 1010 colony‐forming units of Lactobac...,12 weeks,SCORAD
13,C: 1.0 × 1010 colony‐forming units placebo onc...,NaN,NaN,NaN,NaN,NaN
14,Ahn 2020,41/41,4.8 ± 2.3/5.4 ± 3.0 years,T: 1.0 × 1010 colony‐forming units of L. pento...,12 weeks,SCORAD
15,C: 1.0 × 1010 colony‐forming units placebo onc...,NaN,NaN,NaN,NaN,NaN
16,Cukrowska 2021,66/68,8.2 ± 6.1/8.8 ± 6.6 months,T: 1.0 × 109 colony‐forming units of a mixture...,3 months,SCORAD
17,C: 1.0 × 109 colony‐forming units placebo (mal...,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

,"Author, year",Randomization process,Deviation from intended interventions,Missing outcome data,Measurement of the outcome,Selection of the reported result,Overall
0,Gerasimov 2010,Low risk,Low risk,Low risk,Some concerns,Some concerns,Some concerns
1,Wu 2011,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
2,Han 2012,Low risk,Low risk,Low risk,Some concerns,Low risk,Some concerns
3,Wang 2015,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
4,Navarro‐López 2017,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
5,Plummer 2019,Low risk,Some concerns,Low risk,Low risk,Low risk,Some concerns
6,Jeong 2020,Some concerns,Some concerns,Low risk,Some concerns,Low risk,Some concerns
7,Ahn 2020,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
8,Cukrowska 2021,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns

--------------------------------------------------------------------------------

,First author Year (Ref.),Sample size (T/C),"Age, (T/C)",Intervention,Intervention duration,Outcomes
0,Gerasimov 2010,43/47,25.6 ± 7.7/24.1 ± 6.3 months,T: 1.0 × 1010 colony‐forming units of Lactobac...,8 weeks,SCORAD
1,C: 1.0 × 1010 colony‐forming units placebo twi...,NaN,NaN,NaN,NaN,NaN
2,Wu 2011,27/27,7.8 ± 3.5/6.9 ± 3.4 years,T: 475 mg fructo‐oligosaccharide plus 25 mg li...,8 weeks,SCORAD
3,C: 475 mg fructo‐oligosaccharide plus 25 mg co...,NaN,NaN,NaN,NaN,NaN
4,Han 2012,58/60,4.6 ± 3.3/5.1 ± 3.3 years,T: 0.5 × 1010 colony‐forming units of L. plant...,12 weeks,SCORAD
5,C: 0.5 × 1010 colony‐forming units placebo twi...,NaN,NaN,NaN,NaN,NaN
6,Wang 2015,51/53,8.34 ± 3.80/8.04 ± 3.97 years,T: 4 × 109 colony‐forming units of a mixture o...,3 months,SCORAD
7,C: 4 × 109 colony‐forming units placebo once d...,NaN,NaN,NaN,NaN,NaN
8,Navarro‐López 2017,26/24,9.35 ± 3.58/8.96 ± 3.94 years,T: 1.0 × 109 colony‐forming units of a mixture...,12 weeks,SCORAD
9,C: 1.0 × 109 colony‐forming units placebo (mal...,NaN,NaN,NaN,NaN,NaN
10,Plummer 2019,118/137,Preterm infants (Birth to discharge from hospi...,T: 1.0 × 109 colony‐forming units of a mixture...,2 years,SCORAD
11,C: placebo (maltodextrin) once daily,NaN,NaN,NaN,NaN,NaN
12,Jeong 2020,33/33,5.67 ± 3.30/5.33 ± 2.53 years,T: 1.0 × 1010 colony‐forming units of Lactobac...,12 weeks,SCORAD
13,C: 1.0 × 1010 colony‐forming units placebo onc...,NaN,NaN,NaN,NaN,NaN
14,Ahn 2020,41/41,4.8 ± 2.3/5.4 ± 3.0 years,T: 1.0 × 1010 colony‐forming units of L. pento...,12 weeks,SCORAD
15,C: 1.0 × 1010 colony‐forming units placebo onc...,NaN,NaN,NaN,NaN,NaN
16,Cukrowska 2021,66/68,8.2 ± 6.1/8.8 ± 6.6 months,T: 1.0 × 109 colony‐forming units of a mixture...,3 months,SCORAD
17,C: 1.0 × 109 colony‐forming units placebo (mal...,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

,"Author, year",Randomization process,Deviation from intended interventions,Missing outcome data,Measurement of the outcome,Selection of the reported result,Overall
0,Gerasimov 2010,Low risk,Low risk,Low risk,Some concerns,Some concerns,Some concerns
1,Wu 2011,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
2,Han 2012,Low risk,Low risk,Low risk,Some concerns,Low risk,Some concerns
3,Wang 2015,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
4,Navarro‐López 2017,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
5,Plummer 2019,Low risk,Some concerns,Low risk,Low risk,Low risk,Some concerns
6,Jeong 2020,Some concerns,Some concerns,Low risk,Some concerns,Low risk,Some concerns
7,Ahn 2020,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
8,Cukrowska 2021,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns

--------------------------------------------------------------------------------

,First author,Year,Country,Study design,Gender,Age (years),Sample size,Exposure factors,Outcomes,Quality
0,Longyan Li,2020,China,TS,"M 13,874F 16,380N 1",≤1415–64 ≥ 65,"30,255",Relative humidity (lag7),Asthma outpatient,4/5
1,Huayue Liu,2019,China,TS,"M 1,684F 2,249",18–64 ≥ 65,"3,933",Relative humidity,Asthma hospitalization,3/5
2,Sutyajeet Soneja,2016,USA,C-C,"M 45,226F 70,695",≤45–1718–64 ≥ 65,"115,923",Precipitation,Asthma hospitalization,2/5
3,Marjan Kljakovic,1998,New Zealand,TS,NaN,NaN,"3,844",Relative humidity,Consultations for asthma,2/5
4,Jae-Woo Kwon,2013,South Korea,C-C,NaN,NaN,656,Mean relative humidity,Visits to emergency room for asthma,3/5
5,Nana Mireku,2009,USA,TS,NaN,1–18,"25,401",Relative humidity,Children's asthma ED visits,4/5
6,Hehua Zhang,2020,China,TS,"M 94,854F 53,901",0–56–14 ≥ 15,"173,747",Relative humidity,Asthma outpatient,4/5
7,Toshikazu Abe,2009,Japan,TS,M 52.8%F 47.2%,≤14 > 15,"6,447",Maximum humidityPrecipitation,Visits to emergency room for asthma,4/5
8,Mitsuo Hashimoto,2004,Japan,TS,NaN,2–15,"5,559",Average relative humidity,Visits to emergency room for asthma,4/5
9,Holly Ching-yu Lam,2016,China,TS,NaN,<55–1415–59 > 59,"56,112",Relative humidity,Asthma hospitalization,4/5
10,Zahra Kanannejad,2023,Iran,TS,M 157F 192,19–98,349,"MAR, MAH, MARD",Asthma hospitalization,4/5
11,Zahra Kanannejad,2022,Iran,TS,M 144F 67,≤18,211,"MAR, MAH",Asthma hospitalization,4/5
12,Arun Kumar Sharma,2020,India,TS,M 25F 36,18–3535–49 ≥ 50,61,PrecipitationRelative humidity,Acute attacksof asthma,3/5
13,Leah H. Schinasi,2020,USA,C-C,"M 8,270F 5,213",≤18,"13,483",Precipitation,Acute attacksof asthma,4/5
14,Fei Li,2013,China,CS,NaN,6–13,"20,768",MAH,Asthma attacks,8/11
15,Selma Metintas,2010,Turkey,CS,NaN,≥20,"25,843","MAR, MAH",Asthma attacks,5/11
16,Jae-Woo Kwon,2016,South Korea,C-C,M 302F 281,0–1920–5960–75 ≥ 75,660,Relative humidity,Visits to emergency room for asthma,4/5
17,Ju-Hyeong Park,2022,USA,TS,NaN,0–1819–65 ≥ 65,"63,789",Precipitation,Visits to emergency room for asthma,4/5
18,S K Weiland,2004,Western Europe,ES,NaN,6–713–14,"463,801",MAH,Asthma attacks,8/10
19,David S. Kordit,2020,USA,CS,NaN,0–18 ≥ 19,"42,065",Relative humidity,Asthma hospitalization,8/11
20,Insung Kang,2023,USA,CS,M 14F 39,NaN,53,Relative humidity,Assessment of asthma control,7/11

--------------------------------------------------------------------------------

✅ Finished displaying all 20 tables!

## Filter and Display Specific Tables

Use the options below to display only specific tables based on various criteria.

In [14]:
# Filter 1: Tables in sections containing "method"
print("=" * 80)
print("FILTER 1: TABLES FROM 'METHOD' SECTIONS")
print("=" * 80 + "\n")

method_filter = df_tables[df_tables['section'].str.contains('method', case=False, na=False)]
print(f"Found {len(method_filter)} tables in sections containing 'method'\n")

display_limit = min(20, len(method_filter))
for idx, i in enumerate(method_filter.index[:display_limit]):
    try:
        print(f"\n[Method Filter - Table {idx + 1}/{display_limit}]")
        show_table(i)
    except Exception as e:
        print(f"Error displaying table {i}: {e}")
        continue

print(f"\n✅ Finished displaying {display_limit} tables from 'method' sections!")

# Filter 2: Tables in sections containing "risk of bias" or "rob" variations
print("\n\n" + "=" * 80)
print("FILTER 2: TABLES FROM 'RISK OF BIAS' / 'ROB' SECTIONS")
print("=" * 80 + "\n")

rob_filter = df_tables[
    df_tables['section'].str.contains('risk of bias|rob', case=False, na=False)
]
print(f"Found {len(rob_filter)} tables in sections containing 'risk of bias' or 'rob'\n")

display_limit = min(20, len(rob_filter))
for idx, i in enumerate(rob_filter.index[:display_limit]):
    try:
        print(f"\n[ROB Filter - Table {idx + 1}/{display_limit}]")
        show_table(i)
    except Exception as e:
        print(f"Error displaying table {i}: {e}")
        continue

print(f"\n✅ Finished displaying {display_limit} tables from 'risk of bias'/'rob' sections!")

================================================================================
FILTER 1: TABLES FROM 'METHOD' SECTIONS
================================================================================

Found 58 tables in sections containing 'method'


[Method Filter - Table 1/20]

    No.                                       Search terms
0    #1                   MeSH terms: “rhinitis, allergic”
1    #2  Title/Abstract: “allergic rhinitides” OR “rhin...
2    #3                                           #1 OR #2
3    #4  MeSH terms: “acupuncture” OR “acupuncture ther...
4    #5  Title/Abstract: “acupuncture” OR “manual acupu...
5    #6                                           #4 OR #5
6    #7    Publication Type: “randomized controlled trial”
7    #8  MeSH terms: “randomized controlled trials as t...
8    #9  Title/abstract: “randomized” OR “randomly” OR ...
9   #10                                     #7 OR #8 OR #9
10  #11                                  #3 AND #6 AND #10

--------------------------------------------------------------------------------

[Method Filter - Table 2/20]

  Database              Searching keywords
0   PubMed                      (1) asthma
1      NaN                      (2) wheeze
2      NaN                    (3) migraine
3      NaN                  (4) hemicrania
4      NaN                    (5) headache
5      NaN                   (6) cephalgia
6      NaN                 (7) cephalalgia
7      NaN                    (8) #1 or #2
8      NaN  (9) #3 or #4 or #5 or #6 or #7
9      NaN                  (10) #8 and #9

--------------------------------------------------------------------------------

[Method Filter - Table 3/20]

  Databases                                    Search strategy
0    PubMed  (Allergic rhinitis [Title/Abstract]) OR (rhino...
1  Cochrane  Allergic rhinitis in title abstract keyword AN...

--------------------------------------------------------------------------------

[Method Filter - Table 4/20]

,"Author, year, study location","Study design, setting",Age (years),"Male, n (%)",Past history of allergies or allergic reactions,Past history of anaphylaxis,Vaccine brand and dose,Reaction onset after vaccination [min],Signs and symptoms,Anaphylaxis level of severity,Tryptase level was measured; AND if elevated§,Treatment setting: therapy given for reaction,"Epinephrine received, n (%)",Outcome,Skin test performed? [Time from reaction to the skin test]; and result,Assessment of study risk of bias (tool used; finding),Key findings
0,"Blumenthal et al. 2021 [22], United States","Prospective cohort, multicenterSelf-reporting ...","Mean (SD), 41 (14)",1 (14.3),Three (43%) persons had prior allergies or all...,One (14.3%) person had a prior episode of anap...,"Pfizer-BioNTech, dose 1","Mean [range], 14 [10–30]","Pruritus, urticaria, and/or angioedema, sensat...",All cases were classified as Brighton Level 2 ...,Not measured,"One patient was hospitalized in ICU, and four ...",6 (86),All patients had recovered or been discharged ...,–,(NOS; 8),Allergists and immunologists reviewed the EHRs...
1,"Blumenthal et al. 2021 [22], United States","Prospective cohort, multicenterSelf-reporting ...","Mean (SD), 41 (13)",0 (0),Seven (78%) persons had prior allergies or all...,Four (44%) persons had a prior episode of anap...,"Moderna, dose 1","Mean [range], 19 [1–120]","Pruritus, urticaria, and/or angioedema, sensat...",All cases were classified as Brighton Level 1 ...,Yes; AND was elevated in 1 patient (11),Five patients were treated in an ED,3 (33),All patients had recovered or been discharged ...,–,(NOS; 8),Allergists and immunologists reviewed the EHRs...
2,"Frank et al. 2021 [25], United States",Case report,55-year-old female HCW,0 (0),"A history of significant allergies, including ...",A history of anaphylactic reactions,"Pfizer-BioNTech, dose 1",10 min,Despite premedication with I.V. diphenhydramin...,Case was classified as Brighton Level 1 a,Not measured,Patient was treated at the ED with I.M. epinep...,1 (100),Patient was discharged from the hospital with ...,–,(NOS; 6),Patient’s allergic reaction demonstrated by ed...
3,"Kadali et al. 2021 [27], United States","A randomized, cross‐sectional study using an i...",Average age of all participants who completed ...,About 10.65% of participants were males,Not reported,Not reported,"Moderna, unknown dose",Not reported,Not reported,–,Not measured,Not reported,Not reported,Patient recovered with complete resolution of ...,–,RoB 2; low risk of bias,Incidence of vaccine-triggered anaphylaxis per...
4,"Mathioudakis et al. 2021 [29], United Kingdom",Self-reporting by participants via an online s...,"Age groups [40–49; n = 3]; [50–59, n = 2] AND ...",4 (57),Not reported,Not reported,"Pfizer-BioNTech, dose 1 (n = 1,673), AND dose ...",Not reported,Not reported,All episodes of anaphylaxis reported were desc...,Not measured,None required hospital admission (only treatme...,Not reported,Patients recovered with complete resolution of...,–,(NOS; 6),Incidence of vaccine-triggered anaphylaxis per...
5,"Mathioudakis et al. 2021 [29], United Kingdom",Self-reporting by participants via an online s...,Age groups [30–39; n = 1] AND [40–49; n = 1],0 (0),Not reported,Not reported,"Moderna, dose 1 (n = 282), AND dose 2 (n = 1)",Not reported,Not reported,All episodes of anaphylaxis reported were desc...,Not measured,None required hospital admission (only treatme...,Not reported,Patients recovered with complete resolution of...,–,(NOS; 6),Incidence of vaccine-triggered anaphylaxis per...
6,"Ontario Public Health Agency 2021 [33], Canada",Ontario’s vaccine safety surveillance system,Age group [18–64] AND 65 +,Most were females,About 4 (28.6%) reported either a history of a...,Five (35.7%) persons had a prior episode of an...,"Pfizer-BioNTech, unknown dose","Median [range], 10.5 [9–19.7]",–,Cases were classified as Brighton Level 1 (9 [...,Not measured,Twelve patients (85.7%) were hospitalized and ...,13 (92.8),All patients had recovered or been discharged ...,–,(NOS; 6),Incidence of vaccine-triggered anaphylaxis per...
7,"Ontario Public Health Agency 2021 [33], Canada",Ontario’s vaccine safety surveillance system,Age group [18–64],-,Patient had a prior allergic reaction to non-C...,Patient reported a prior history of anaphylaxi...,"Moderna, unknown dose",11 min,–,Case was classified as Brighton Level 1 (1 [10...,Not measured,Patient was treated in an ED,1 (100),Patient had recovered or been discharged home....,–,(NOS; 6),Incidence of vaccine-triggered anaphylaxis per...
8,"Park et al. 2021 [34], United States",Case report,34-year-old female HCW,0 (0),A history of childhood asthma and eczema; and ...,Patient reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1",3 min,"Patient developed flushing, urticaria on her e...",–,Yes; AND level was not elevated,Patient was treated at the ED with I.M. epinep...,1 (100),Patient recovered with complete resolution of ...,Yes. [Not reported]; and patient showed no rea...,(NOS; 6),Serum tryptase level was within reference rang...
9,"Pitlick et al. 2021 [35], United States","Retrospective case reports, multicenter",22-year-old female,0 (0),Allergic rhinitis,Patient reported no prior history of anaphylaxis,"Moderna, dose 1",20 min,"Angioedema, wheezing, and throat pruritus",Case was classified as Brighton Level 1a,Not measured,Patient was treated in the ED and given antihi...,0 (0),Patient recovered with complete resolution of ...,Yes. [Three weeks after the resolution of clin...,(NOS; 7),Second vaccine dose was successfully given to ...
10,"Restivo et al. 2021 [36], Italy",Case report,30-year-old female HCW,0 (0),A polyallergic subject with a prior reported u...,Patient reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1",5 h after the administration of the vaccine,Patient developed erythematous spots on the fa...,–,Yes; AND level was not elevated,Patient was treated in the ED and given 8 mg I...,0 (0),Patient recovered with complete resolution of ...,Yes. [Two weeks after the resolution of clinic...,(NOS; 6),Patient reported self-administering prednisone...
11,"Sellaturay et al. 2021 [38], United Kingdom",Case report,52-year-old female,0 (0),Patient had prior allergies or allergic reacti...,Patient had prior history of anaphylaxis to drugs,"Pfizer-BioNTech, dose 1",1 min,"Patient developed throat constriction, cough a...",–,Yes; AND level was not elevated,Patient was treated at the ED with I.M. epinep...,1 (100),Patient recovered with complete resolution of ...,Yes. [Not reported]; and SPT in patient showed...,(NOS; 5),PEG allergy was diagnosed as the cause of pati...
12,"Shimabukuro et al. 2021 [39], United States",National passive surveillance (spontaneous rep...,"Median (IQR), 40 (30–50)",2 (9.5),Seventeen (81%) of 21 patients with anaphylaxi...,Seven (33%) had experienced an episode of anap...,"Pfizer-BioNTech, dose 1","Median [range], 13 [2–150]",The most commonsymptoms and signs were urticar...,All cases were classified as Brighton Level 1 ...,Not measured,Four patients (19%) were hospitalized (includi...,19 (90.5),Twenty (95%) were discharged home or had recov...,–,(NOS; 8),CDC physicians evaluated these reports and app...
13,"Shimabukuro et al. 2021 [40], United States",National passive surveillance (spontaneous rep...,"Median (IQR), 39 (27–63)",3 (6.4),Thirty-six (77%) noted a prior allergies or al...,Sixteen (34%) noted a prior episode of anaphyl...,"Pfizer-BioNTech, dose 1 (n = 37), dose 2 (n = ...","Median [range], 10 [< 1–1140] b",Common symptoms and signs were generalized urt...,Cases were classified as Brighton Level 1 (21 ...,Not measured,All patients were treated in health care setti...,Most of the anaphylaxis cases (≈92%) received ...,Most of the cases (≈92%) were discharged home ...,–,(NOS; 8),CDC physicians evaluated these reports and app...
14,"Shimabukuro et al. 2021 [40], United States",National passive surveillance (spontaneous rep...,"Median (IQR), 41 (24–63)",0 (0),Sixteen (84%) noted a prior allergies or aller...,Five (26%) noted a prior episode of anaphylaxi...,"Moderna, dose 1 (n = 17), dose 2 (n = 1) AND u...","Median [range], 10 [1–45]",Common symptoms and signs were generalized urt...,Cases were classified as Brighton Level 1 (10 ...,Not measured,All patients were treated in health care setti...,Most of the anaphylaxis cases (≈92%) received ...,Most of the cases (≈92%) were discharged home ...,–,(NOS; 8),CDC physicians evaluated these reports and app...
15,"Shimabukuro et al. 2021 [39], United States",National passive surveillance (spontaneous rep...,"Median (IQR), 47 (31–63)",0 (0),Nine (90%) persons had a documented history of...,Five (50%) persons had a previous history of a...,"Moderna, dose 1","Median [range], 7.5 [1–45]","Vomiting, nausea, respiratory failure, periorb...",Cases were classified as Brighton Level 1 (6 [...,Not measured,Six patients were hospitalized (including five...,10 (100),All patients had recovered or been discharged ...,–,(NOS; 6),CDC physicians evaluated these reports and app...

--------------------------------------------------------------------------------

[Method Filter - Table 5/20]

,"Author, year, study location","Study design, setting",Age (years),"Male, n (%)",Past history of allergies or allergic reactions,Past history of anaphylaxis,Vaccine brand and dose,Reaction onset after vaccination [min],Signs and symptoms,Treatment setting: therapy given for reaction,"Epinephrine received, n (%)",Outcome,Skin test performed? [Time from reaction to the skin test]; and result,Assessment of study risk of bias (tool used; finding),Key findings
0,"Ackerman et al. 2021 [18], France",Case report,55-year-old male HCW,1 (100),No past medical history and no drug allergy,Patient reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1",180 min,Patient experienced injection-site soreness in...,Patient was hospitalized and treated with derm...,Not reported,A gradual improvement over the days with treat...,Not reported,(NOS; 6),A persistent maculopapular eruption (1 month) ...
1,"Baden et al. 2021 [19], United States","A phase 3 randomized, observer-blinded, placeb...","Mean (range), 51.4 (18–95)","7,923 (52.2)",Not reported,Not reported,"Moderna, dose 1 and dose 2",Unsolicited delayed adverse events of hypersen...,"Allergic and atopic dermatitis (n = 8), contac...",–,–,The reactions typically resolved over the foll...,–,RoB 2; low risk of bias,Incidence of hypersensitivity reactions per 10...
2,"Bae et al. 2021 [20], South Korea",A self-administered online questionnaire to HC...,About 190 (68.6%) of the HCWs were in the age ...,92 (33.2),Not reported,Not reported,"Pfizer-BioNTech, dose 1",Not reported,The most common nonanaphylactic reactions were...,Antipyretics use was less common in the Pfizer...,–,–,–,(NOS; 5),Incidence of allergy-like reactions per 106 do...
3,"Bianchi et al. 2021 [21], Italy",Case series,"Median [range], 37.5 [27–55]",1 (16.7),"Allergic rhinitis (n = 6), asthma (n = 1), ato...",Patients reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1","Median (range), 15 (5–1,440 [24 h])","Generalized acute urticaria, angioedema (tongu...",One case was treated with I.V. betamethasone s...,–,–,Yes. [ Not reported]; SPT resulted always nega...,(NOS; 6),Incidence of mucous-cutaneous adverse reaction...
4,"Blumenthal et al. 2021 [22], United States",Case series,"Median (IQR), 44 (37.2–48.5)",2 (16.7),About 8 (66.7%) of the cases had prior contras...,Patients reported no prior history of anaphylaxis,"Moderna, dose 1",Delayed adverse events of hypersensitivity (de...,"Pruritus, burning, pain, warmth, erythema, ind...",Most patients received treatment for their sym...,–,The symptoms resolved a median of 6 days after...,–,(NOS; 7),All 12 patients completed Moderna vaccination....
5,"CDC COVID-19 Response Team 2021 [24], United S...",National passive surveillance (spontaneous rep...,"Median [range], 43 [18–65]",8 (9.6),"For 56/83 (67%) case reports, a past history o...",Patients reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1","12 (< 1–1,200 [20 h])","Commonly symptoms included pruritus, rash, itc...",Not reported,Not reported,All patients had recovered or been discharged ...,–,(NOS; 7),Incidence of nonanaphylactic reactions per 106...
6,"Corbeddu et al. 2021 [23], Italy",Case series,"Median [range], 56 [36–61]",4 (36.4),"Majority of patients (72.7%, n = 8) had a prev...",Patients reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1 AND dose 2","Median (range), 48 h (1 h–72 h)",Cutaneous symptoms [such as erythematoedematou...,The patient who manifested a relapse of atopic...,–,All manifestations resolved spontaneously with...,–,(NOS; 6),Incidence of cutaneous symptoms per 106 doses ...
7,"Johnston et al. 2021 [26], United States",Case series,"Median [range], 38 [25–89]",3 (18.7),About 1/16 (6.2%) reported a prior localized v...,Patients reported no prior history of anaphylaxis,"Moderna, dose 1 AND dose 2","Median [range], 7 days [2–12 days]",HCWs experienced delayed localized cutaneous r...,"Treatments included topical steroids, oral ant...",–,–,–,(NOS; 8),Reactions to the first vaccine dose had a medi...
8,"Kadali et al. 2021 [27], United States","A randomized, cross‐sectional study using an i...",Average age of all participants who completed ...,About 10.65% of participants were males,Not reported,Not reported,"Moderna, dose 1 AND dose 2",Not reported,"Among the 432 vaccine recipients, (n = 58) rep...",Only 17/432 (3.94%) required seeking help from...,–,Patients recovered with complete resolution of...,–,RoB 2; low risk of bias,Incidence of nonanaphylactic reactions per 106...
9,"Kelso et al. 2021 [28], United States",Case reports,"Median (IQR), 45 (42.2–53.7)",0 (0),Not reported,Not reported,Pfizer-BioNTech (n = 3) AND Moderna (n = 1); b...,"Median [range], 3.5 [1.2–12.5]","Sensation of throat swelling, SOB, hot and swe...",One patient (25%) was hospitalized and needed ...,2 [50],Patients recovered with complete resolution of...,Yes. [ Not reported]; and SPTs and IDTs in all...,(NOS; 6),Subsequent vaccine skin testing suggested that...
10,"McMahon et al. 2021 [30], United States",An international registry of COVID-19 vaccine ...,"Median (IQR), 45 (36–60)",29 (8.4),"Among the 343 cases, (n = 12) reported atopic ...",Not reported,"Moderna, dose 1 AND dose 2","First dose: Median [IQR], 7 days [2–8]Second d...",Among the 369 administered doses [1st and 2nd]...,Patients responded well to topical corticoster...,Not reported,No patients with these findings experienced an...,Not reported,(NOS; 6),Incidence of nonanaphylactic reactions per 106...
11,"McMahon et al. 2021 [30], United States",An international registry of COVID-19 vaccine ...,"Median (IQR), 42 (36–54)",11 (15.5),"Among the 71 cases, (n = 5) reported atopic de...",Not reported,"Pfizer-BioNTech, dose 1 AND dose 2","First dose: Median [IQR], 7 days [2–8]Second d...","Among the 74 administered doses [1st and 2nd],...",Patients responded well to topical corticoster...,Not reported,No patients with these findings experienced an...,Not reported,(NOS; 6),Incidence of nonanaphylactic reactions per 106...
12,"Mustafa et al. 2021 [31], United States",Two case reports,A 64-year-old female (patient 1) ANDa 39-year-...,0 (0),Patient 1 had history of shellfish allergy AND...,Both patients reported no prior history of ana...,"Moderna, dose 1",10 min (patient 1) AND 15 min (patient 2),"Patient 1 had generalized pruritus, urticaria,...",Patient 1 was treated at vaccination site and ...,0 (0),Both patients recovered with complete resoluti...,Yes. [Not reported]; and SPTs in both patients...,(NOS; 5),Second vaccine dose was administered without p...
13,"Ocáriz et al. 2021 [32], Spain","Investigational clinical trial, single centre",43-year-old female,0 (0),A history of severe asthma,Patient reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1",10 min,Patient developed nasal obstruction and rhinol...,Patient was treated at the allergy department ...,0 (0),Patient recovered with complete resolution of ...,Yes. [Not reported]; and SPT in patient was no...,RoB 2; some concerns risk of bias,No modification on tryptase levels compared wi...
14,"Pitlick et al. 2021 [35], United States","Retrospective case reports, multicenter","Median (IQR), 36 (24–52)",2 (28.6),About 4 (57.1%) of the cases had prior drug (i...,Two (28.6%) cases had prior insect stinging (v...,Pfizer-BioNTech (n = 6) AND Moderna (n = 1); b...,"Median [range], 97 [6–405]","Urticaria, tachycardia, rhinorrhea, facial flu...",Patients were treated at the vaccination sites...,–,Patient recovered with complete resolution of ...,Yes. [A median of 16 days after the resolution...,(NOS; 7),All patients successfully received their 2nd v...
15,"Riad et al. 2021 [37], The Czech Republic",A cross-sectional self-administered online que...,About 50.2% of participant were ≤ 43 years old,100 (11.4),About 21.8% and 5.9% of participants reported ...,Patients reported no prior history of anaphylaxis,"Pfizer-BioNTech, dose 1 AND dose 2",Not reported,"Rash (n = 28), urticaria (n = 10), tongue ting...",–,–,–,–,(NOS; 6),Incidence of nonanaphylactic reactions per 106...
16,"Shimabukuro et al. 2021 [39], United States",National passive surveillance (spontaneous rep...,"Median [range], 43 [22–96]",4 (9.3),"For 26/43 (60%) case reports, a past history o...",Patients reported no prior history of anaphylaxis,"Moderna, dose 1","15 (< 1–1,440 [24 h])","Commonly symptoms included pruritus, rash, itc...",–,–,All patients had recovered or been discharged ...,-,(NOS; 6),Incidence of vaccine-triggered anaphylaxis per...
17,"Vieira et al. 2021 [41], Portugal","Prospective cohort, single center",31,0 (0),Allergic rhinitis,Sixty reported a previous history of drug anap...,"Pfizer-BioNTech, dose 1",10,HCW developed a sudden onset generalized urtic...,–,–,–,A total of 115 HCWs performed SPTs and IDTs wi...,(NOS; 6),SPTs and IDTs were performed for each person w...

--------------------------------------------------------------------------------

[Method Filter - Table 6/20]

,"Study, year",Country,Setting,Sample size,No. of males (%),"Mean age (range), years",Nasal provocation positive,Nasal provocation negative,Wheal size cut-off (mms),"Sensitivity, %","Specificity, %",Allergen extracts
0,Zarei et al. [25],USA,Clinic,45,21 (47),39 (25–66),18,27,≥3a,100.0,74.1,Cat
1,Krouse et al. [14],USA,Hospital,37,NR,NR (18–70),15,22,≥3a,87.0,86.0,Timothy grass
2,Krouse et al. [14],USA,Hospital,44,NR,NR (18–70),19,25,≥3a,42.0,64.0,Alternaria
3,Gungor et al. [15],USA,Unclear,62,NR,≥18,34,28,unclear,85.3,78.6,Ragweed
4,Wood et al. [24],USA,Hospital,120,22 (18),32 (18–65),48,32,≥3b,79.0,91.0,Cat
5,Pastorello et al. [21],Italy,Hospital,91,48 (53),NR (9–57),70,31,"≥3 and 100,000BU/ml",98.0,70.0,"Grass,mugwort, birch, pellitory, Dermatophagoi..."
6,Petersson et al. [23],Sweden,Hospital,69,48 (70),27 (14–53),36,33,≥0.5c,97.0,70.0,Birch and timothy grass
7,Pepys et al. [22],UK,Hospital,141,NR,NR,72,64,≥1,68.1,84.4,"Sweet vernal, cocksfoot, meadow fescue, rye, t..."

--------------------------------------------------------------------------------

[Method Filter - Table 7/20]

,"Study, year",Country,Setting,Sample size,Number of males,"Age range, years",Nasal provocation positive,Nasal provocation negative,Wheal size cut-off (mms),"Sensitivity, %","Specificity, %",Allergen extracts
0,Krouse et al. [14],USA,Hospital,37,NR,NR (18–70),2,19,≥3a,50.0,100.0,Timothy grass
1,Krouse et al. [14],USA,Hospital,44,NR,NR (18–70),11,16,≥3a,27.0,69.0,Alternaria
2,Gungor et al. [15],USA,Unclear,62,NR,≥18,34,28,≥2,79.4,67.9,Ragweed
3,Wood et al. [24],USA,Hospital,120,22 (18),32 (18–65),10,29,≥6,60.0,68.9,Cat

--------------------------------------------------------------------------------

[Method Filter - Table 8/20]

  Database                                    Search strategy
0   PubMed  (cohort studies[mesh:noexp] OR followup studie...
1   Embase  ('rheumatoid arthritis'/exp OR 'rheumatoid art...

--------------------------------------------------------------------------------

[Method Filter - Table 9/20]

,Study ID,Author,Year,Country,Year.1,Design,Type of exposure,Exposure assessment,No. of observed cases,Effect size (95% CI)
0,1,Ilar [18],2019,Sweden,1996–2013,CC,Occupational – not better specified,JEMs,742 cases/5235 controls (678 men; 64 women),Any RA: OR 1.3 (1.2–1.5)RA+ : RR 1.28 (1.02–1....
1,2,Schmajuk [25],2019,USA,2019,CO,Mainly coal mining work,Exposure data were self-reported during a tele...,556 silica-exposed male workers,Any RA: OR 2.1 (1.1–3.9)
2,3,Vihlborg [26],2017,Sweden,1930–2013,CO,Iron foundries,A mixed model was used to calculate silica exp...,2187 silica-exposed male workers,SIR 2.59 (1.24–4.76)
3,4,Blanc [27],2015,Sweden,1997–2010,CO,Construction work,JEMs,195 silica-exposed male workers,Any RA: RR 1.33 (1.11–1.60)RA+ : RR 1.28 (1.02...
4,5,Yahya [19],2014,Malaysia,2005–2009,CC,"Stone dust, rock drilling, stone crushing",In-person interview according to an extensive ...,14 cases/12 controls,Any RA: OR 2.0 (0.9–4.6)RA+ : OR 2.4 (1.0–5.6)...
5,6,Makol [28],2011,USA,1985–2006,CO,Various including foundry work and sandblasting,30-45 min telephone interview (if the individu...,1022 cases diagnosed with Silicosis. (only for...,Any RA: RR 2.26 (1.57–3.25)
6,7,Stolt [20],2009,Sweden,1996–2006,CC,"Stone dust, rock drilling, stone crushing",Exposure data were self-reported using a quest...,80 cases/69 controls,Any RA: OR 1.39 (0.98–1.96)RA+ : OR 1.67 (1.13...
7,8,Gold [21],2007,USA,1984–1999,CCMortality-Death certificates data,"Among 509 different jobs mainly hand painting,...",JEMs,"35,730 cases/260,632 controls",Any RA: OR 0.99 (0.94–1.03)
8,9,Stolt [22],2004,Sweden,1996–2001,CC,"Stone dust, rock drilling, stone crushing",Exposure data were self-reported using a quest...,21 cases/11 controls,Any RA: OR 3.0 (1.2–7.6)RA+ : OR 3.5 (1.1–11.2...
9,10,Calvert [23],2003,USA,1982–1995,CCMortality-Death certificates data,Occupational exposure to FCS not better specif...,JEMs,15 cases/20 controls,Any RA: OR 3.75 (1.92–7.32)
10,11,Brown [29],1997,Sweden-Denmark,1965–1983,CO Mortality-Death certificates data,A review of Swedish computerized hospital diag...,A review of Swedish computerized hospital diag...,57 cases (only for the outcome: 44 cases of SLE),Any RA: RR 8.1 (5.9–10.82)
11,12,Sluis-Cremer [24],1986,South Africa,1967–1979,CC,Gold mines,JEMs,96 cases/157 controls,RA+ : OR 5 (1.99–12.56)RA−: OR 1.44 (0.44–4.73...

--------------------------------------------------------------------------------

[Method Filter - Table 10/20]

,Authors/Year,Region/Country,Study Type,Population (Number),Average Age (Years Old),Daily Mean Concentration of PM2.5 (μg/m3),Lag (Days),Outcome: Observed Change (Change per 10 μg/m3 PM2.5 Increase in Pollutant When Applicable),Statistical Model
0,Lu Ma/200822,"Yotsukaido, Japan",Cohort study,Children with severe asthma (19),Mean age 12.9,22.60,Lag0–1,"PEF:-3.40L/min (95% CI:-6.47, −0.33)",Generalized Estimating Equation model
1,BingYu /201023,"Taiwan,China",Cohort study,"Healthy, asthmatic, and allergic rhinitis scho...",Mean age 10.6,28.20,Lag0–1,"FVC:-0.16L (95% CI:-0.23, −0.08)FEV1:-0.12L (9...",Mixed-effects models
2,Yamazak /201124,"Yotsukaido, Japan",Cohort study,Children with severe asthma (17),8–15,24.00,Lag0–1,"PEF:-2.96L/min (95% CI:-4.55, −1.37)",Generalized Estimating Equations
3,Ludmilla/201225,"Amazon,Brazilian",Cohort study,Healthy and asthmatic children (280),Mean age 10.4,24.34,Lag0–1,"PEF:-0.29L/min (95% CI:-0.52, −0.07)",Mixed-effects models
4,Ludmilla/201426,"Tangara,Brazil",Cohort study,Healthy and asthmatic children (220),Mean age 10.3,19.60,Lag0–4,"PEF:-0.54L/min (95% CI:-0.946, −0.137)",Mixed-effects models
5,Masanari/201627,"Matsue,Japan",Cohort study,"Healthy,asthmatic,allergic rhinitis children (...",10–12,23.00,Lag0–1,"PEF:-1.72 L/min (95% CI:-3.82, 0.36)",Linear mixed model
6,Dandan Xu/201828,"Nanjing, China",Cohort study,Healthy School children (86),Mean age 9,84.30,Lag0–1,"PEF:-1.76L/min (95% CI: −3.549, 0.024)FVC: −0....",Mixed-effects regression mode
7,Liu Weiyan/201910,"Hangzhou,China",Cohort study,Healthy school children (1685),Mean age 9.8,50.00,Lag0–1,"PEF:-2.34L/min (95% CI:-4.02, −0.72)",Linear mixed model
8,Dandan Xu/202029,"Zhejiang, China.",Cohort study,Healthy and asthmatic school children (848),Mean age 9.7,67.58,Lag 1,"PEF:-4.02L/min (95% CI: −5.36, −2.73)FVC:-0.03...",Mixed-effects regression mode
9,Yang Xiaoyan/202011,"Beijing, China",Cohort study,Healthy school children (51),9–12,57.75,Lag4,"PEF:-0.49L/min (95% CI:-2.84, 1.87)FVC:-0.033L...",Linear mixed effects model
10,WU Xingbin/202030,"Jinan, China",Cohort study,Healthy school children (484),Not reported,90.00,Lag0–1,"PEF:-1.54L/min (95% CI:-2.33, −0.76)FVC: −0.00...",Multiple linear regression model

--------------------------------------------------------------------------------

[Method Filter - Table 11/20]

,Study,n,Age of cohort,Inclusion criteria,DBPCFC protocol (mg of peanut protein),Threshold definition,Anaphylaxis definition used,Median cumulative dose,Number with symptoms in response to a ≤5-mg discrete dose
0,Published,Data available,"Objective symptoms, no. (%)",Study-defined anaphylaxis,NaN,NaN,NaN,NaN,NaN
1,Symptoms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Taylor et al, 201013",286,283,"Range, 1-48 y; median, 7 y",Routine diagnostic FC,"Various, 0.025-2.5 as initial dose; 15-min int...",LOAEL,CVS/lower respiratory,125 mg (IQR = 16-241)
3,"Blom et al, 201314",135,123,"Range, 2-18 y; median, 7 y",Routine diagnostic FC,"1.7, 3.5, 14, 70, 139, and 351; 30-min intervals",LOAEL,CVS/slower respiratory,144 mg
4,"Van Erp et al, 201315",109,109,"Median, 7 y (IQR, 5-9 y)",Routine diagnostic FC,"0.005, 0.05, 0.25, 0.5, 5, 50, 150, 500, and 1...",LOAEL,Sampson16 grade 4/5,706 mg (IQR = 206-2206)
5,STOP-II201417,99,99,"Range, 7-16 y; median 12 y",Reaction to ≤1455 mg,"5, 50, 100, 300, and 1000; 20- to 30-min inter...",DLS,NIAID18,55 mg (IQR = 5-1400)
6,"EuroPrevall 20154,5",51,43,Median 8 y (IQR = 2-31 y),Diagnostic FC,"0.003, 0.03, 0.3, 3, 30, 100, 300, 1000, and 3...",LOAEL,CVS/lower respiratory,1433 mg
7,"Klemans et al, 201519",100,100,"Range, 16-64 y; median, 24 y",Routine diagnostic FC,"0.005, 0.05, 0.25, 0.5, 5, 50, 150, 500, and 1...",LOAEL,"Consistent with WAO20,∗",206 mg
8,"Kukkonen et al, 201521",69,69,"Range, 6-18 y; median, 8 y",Reaction to ≤1255 mg,"5, 50, 200, and 1000; 30-min intervals",DLS,Hourihane22,55 mg
9,FAHF-2201523,50,50,"Range, 12-45 y; median 16 y",Reaction to ≤2000 mg,"1, 5, 15, 50, 75, 100, 250, 500, and 1000; 10-...",DLS,NIAID18,146 mg
10,ARC001201724,55,55,"Range, 4-26 y; median 8 y",Reaction to ≤143 mg,"3, 10, 30,and 100; 20-to 30-min intervals",DLS,NIAID18,"43 mg (range, 13-143)"
11,VIPES201725,221,221,"Range, 6-55 y; median 11 y84% <18 y",Reaction to ≤444 mg,"1, 3, 10, 30, 100, and 300; 30-min intervals",DLS,"Consistent with WAO20,∗",144 mg (IQR = 44-444)
12,TAKE-AWAY201726,96,96,"Range, 5-15 y; median 9 y",Reaction to ≤144 mg,"3, 10, 30, 100, 300, 1000, and 3000; 30- to 60...",DLS,CVS/lower respiratory,44 mg (IQR = 4-144)
13,"Purington et al, 201827",347,307,"Range, 1-52 y; median 9 y",Routine diagnostic FC,"0.1, 1.7, 5, 20, 50, 100, 100, 100, 123; 15-mi...",DLS,NIAID18,75 mg
14,PALISADE201828,551,551,"Range, 4-55 y; 90% < 18 y",Reaction to ≤144 mg,"1, 3, 10, 30, and 100; 20- to 60-min intervals",DLS,NIAID18 and SAE definition,44 mg (IQR = 4-144)
15,PEPITES201929,356,356,"Range, 4-11 y; median, 7 y",Reaction to ≤444 mg,"1, 3, 10, 30, 100, and 300; 30-min intervals",DLS,"Consistent with WAO20,∗",144 mg (IQR = 44-444)
16,TRACE201930,123,123,"Range, 18-45 y; mean, 25 y",Reaction to ≤1433 mg,"0.003, 0.03, 0.3, 3, 30, 100, 300, and 1000; 3...",DLS,"Consistent with WAO20,∗",133 mg (IQR = 133-433)
17,BOPI201931,64,64,"Range, 8-16 y; median 13 y",Reaction to ≤4443 mg,"3, 10, 30, 100, 300, 1000, and 3000; 30- to 60...",DLS,"Consistent with WAO20,∗",143 mg (IQR = 43-443)
18,POISED201932,120,120,"Range 7-55 y; median, 11 y; 69% <18 y",Reaction to ≤500 mg,"5, 20, 50, 100, 100, and 100; 15- to 60-min in...",DLS,"Consistent with WAO13,∗",75 mg (IQR = 25-175)
19,ARTEMIS202033,175,175,"Range, 4-17 y; mean, 9 y",Reaction to ≤444 mg,"1, 3, 10, 30, 100, and 300; 20- to 30-min inte...",DLS,NIAID18,44 mg (IQR = 14-44)
20,UMCG20204,144,144,"Range, 1-18 y; median, 8 y",Routine diagnostic FC,"Before 2007: 1.75, 3.5, 14,70, 130, 350, and 5...",LOAEL,CVS/lower respiratory,95.8 mg

--------------------------------------------------------------------------------

[Method Filter - Table 12/20]

,SN,Studies,Study design,Region,Total Population of Study,Study duration,Treatment IgG used (Brand name),Comparison,No. of patients (n),Mean age in years (SD/range),"Female gender (n, %)"
0,1.0,Aydiner 201529,"Prospective, observational",Turkey,16,10 months,SCIG,5–10% IVIG vs. SCIG,16,7.5 (0–33 years),7 (43.7%)
1,2.0,Berger 201030,"Open-label, uncontrolled trial",Germany,"51 (adults = 42, children = 9), (3–66 years)",12 months,16% SCIG (Vivaglobin),Historic IVIG vs.,51,37.8 ± 19.40,30 (58.8%)
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16% SCIG,31,10.4 ± 20.24,18 (58.1%)
3,3.0,Ballow 201631,"Phase IV, multi-center, open-label study",USA,24 (2–16 years),12 months,5% DIF IVIG (Flebogamma),Historic IVIG vs. 5% DIF IVIG,24,9.0 (2.0–16.0),5 (20.8%)
4,4.0,Bezrodnik 20138,"Observational, prospective/retrospective, open...",Argentina,15 (6–18 years),36 weeks,16% SCIG (Beriglobina P),16% SCIG,15,10.6 (3.7),4 (27%)
5,5.0,Bezrodnik 201432,"Observational, descriptive and ambispective study",Argentina,32 (8 months - 40 years),36 weeks,16% SCIG (Beriglobina P),Historic IVIG vs. SCIG (15 via pump and 2 via ...,32,11 (8–40),15 (46.9%)
6,6.0,Borte 20179,"Prospective, non-controlled clinical trial",Europe,49 (>2 years),52 weeks,IVIG 10% (Kiovig)/SCIG 16% (Subcuvia),IVIG 10%/SCIG 16% (period1) vs.,"33 (IVIG), 16 (SCIG16%)",17 (2–67),19 (38.8%)
7,NaN,NaN,NaN,NaN,NaN,NaN,SCIG 20%,SCIG 20% (period2),49 (SCIG 20%),NaN,NaN
8,7.0,Borte 201710,"Prospective, open-label, non-controlled, non-r...",USA and Europe,"51 (13 children, 12 adolescents, 26 adults)",12 months,IVIG 10% (Panzyga),3-weekly IVIG then IVIG 10%,21,26.2 ± 21.2,14 (66.7%)
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4-weekly IVIG then IVIG 10%,30,27.2 ± 18.2,19 (63.3%)
10,8.0,Borte 201133,"Prospective, open-label, multicenter, single-a...",Europe,18 (2–11 years) and 5 (12–15 years) and 28 (16...,12 weeks (wash-in/wash-out period)+28 weeks ef...,SCIG 20% (Hizentra),IVIG vs. 20%SCIG,51,"7.2 ± 2.5 (children), 14 ± 1 (adolescents), 34...","5 (27.8%) children, 0 adolescents, 11 (39.3%) ..."
11,9.0,Haddad 20126,"Comparative study for Open-label, multi-center...",USA and Europe,EU = 46,12 weeks wash-in/wash-out period + efficacy pe...,SCIG 20% (Hizentra),SCIG 20% same dose as historic IVIG,46,21.5 ± 15.6,15 (33%)
12,NaN,NaN,NaN,NaN,USA = 38,NaN,NaN,SCIG 20% 1.5 x dose as historic IVIG,38,36.3 ± 19.5,21 (55%)
13,10.0,Hagan 201011,"Prospective, open-label, multicenter, single-a...",USA,49 (5–72 years),12 weeks wash-in/wash-out period and 12-month ...,SCIG 20% (IgPro20),IVIG then SCIG 20%,49,36.3 ± 19.52,21 (55.3%)
14,11.0,Jolles 201134,"Prospective, open-label, multicenter, single-a...",Europe,"53 (17 < 12 years, 5 < 16 years,31 ≥ 16 years).","12-week wash-in/wash-out period, 28 weeks effi...",SCIG 20% (Hizentra),Switch from IVIG to SCIG 20%,"46 (ITT), 23 (PPK)",21.5 ± 15.6,15 (32.6%)
15,12.0,Kanegane 201435,"Prospective, multicenter, open-label, single-a...",Japan,"25 (2–12 years = 11, 12–16 years = 8, 16–65 ye...",12-week wash-in/wash-out period with 12-week e...,IgPro20 SCIG (Hizentra),Switch from IVIG to SCIG 20%,"24 (ITT), 21 (PPK)","17.5 (3–58) ITT, 19(3–58) PPK","9 (37.5%) ITT, 7 (33.3%) PPK"
16,13.0,Krivan 201636,"Open-label, prospective, multicenter, single-a...",Europe,"62 (2–61 years), 36 adults and 26 pediatrics",12 months,IVIG (IqYmune),Switch from IVIG to IqYmune,62,27.4 (2–61),19 (30.6%)
17,14.0,Melamed 201637,"Open-label, multi-center, non-randomized phase...","USA(7), Chile(1), Israel (1)",25 (3–16 years),12 months,5% IVIG (Gammaplex),Switch from IVIG to IVIG 5%,14 on 21-day infusion and 11 on 28-day infusion,10.4 ± 3.84,6 (24%)
18,15.0,Moy 201038,"Prospective, open-label, multi-center, non- co...",USA,50 (≥3 years),12 months,5% IVIG with and 5 g d-sorbitol (Gammaplex 5%),Switch from IVIG to 5% IVIG,22 on 21-day and 28 on 28-day infusion schedule,44 ± 19.10,24 (48%)
19,16.0,Patel 201539,Retrospective chart review,USA,"88 (0-<2 years = 34, 2–5 years = 54)",45.5 months,SCIG 20% (Hizentra),Historic Hizentra use,88,34 months (2-59),35 (40%)
20,17.0,Quinti 201117,"Prospective, multi-center",Italy,302 (CVID + XLA),3.8 years (CVID)5.8 years (XLA),IVIG,IVIG in CVID vs. XLA,302,28.7 ± 18.4 (3–68 years) (CVID),NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.9 ± 6.2 (16 days-40.9 years) (XLA),NaN
22,18.0,Stein 201640,"Prospective, open-label, single-arm, multicent...",USA and Canada,40 (2–70 years)- 39 in US and 6 in Canada,12 months,10% IVIG (Kedrion),Historic Hizentra use (mean age of initiation ...,88,34 months (2-59),35 (40%)
23,19.0,Suez 201641,"Prospective, open-label clinical trial",USA and Canada,74 (≥2 years),52 weeks,IVIG 10% and SCIG 20%,NaN,74,39.9 ± 20.7,13 (29%)
24,20.0,Viallard 201742,"Prospective, multicenter, non-randomized, open...",France,22 (18–70 years),9 months,5% lyophilized IVIG (Tegeline) and IV Ig new g...,"Period 1-IVIG 10% then SCIG 205 in period 2, 3...",22,36 (3–83),37 (48.1%)
25,21.0,Vultaggio 201543,"Prospective, observational, multicenter",Italy,"50 (group A >14 years = 43, Group B ≤ 14 years...",24 months,SCIG 16% (Vivaglobin),IVIG/SCIG vs. SCIG 16%,50,41.9 ± 12.2,8 (36.4%)
26,22.0,Wasserman 201244,"Open-label, phase III, efficacy and pharmacoki...",USA,"63 (6–11 years = 4, 12–17 years = 6, 18–64 yea...",12 months,IVIG 10% (Biotest),IVIG vs. SCIG 16%,50,31.7 ± 15.7,19 (38%)
27,23.0,Wasserman 201245,"Prospective, multicenter, open label, phase III",USA and Canada,"87 (2–12 years = 14, ≥12 years = 73)",14–18 months,SCIG/IVIG preceded by rHyPH20 [recombinant hum...,IVIG 10% infusion in 21 day vs. 28 day,87,41.2 ± 19.68,32 (50.8%)
28,24.0,Wasserman 20167,"Prospective, open-label, non-controlled, multi...",USA and Canada,"63 (<18 years = 15, ≥18 years = 48)",30 months,SCIG preceded by rHyPH20 [recombinant human hy...,SCIG/IVIG + rHyPH20 vs. IVIG/SCIG alone,87,35 (4–78),43 (49.4%)

--------------------------------------------------------------------------------

[Method Filter - Table 13/20]

,SN.,Studies,Type of IgG used,"Dosing protocol, Mean(range) mg/Kg/week",IgG trough level (Mean ± SD) mg/dl,Severe infections n (rate/patient/year),"Overall infection (n, CI)-annual rate per patient","Days of hospitalization (n, Mean ± SD)","Days missed from work/school (n, Mean ± SD)",Adverse events/patient/year
0,1.0,Aydiner 201529,IVIG,330–1250 mg/kg/wk,976 ± 564 mg/dl,0,7 events in 4 pts in 10 months,na,na,na
1,NaN,NaN,SCIG,300–430 mg/kg/wk,1025 ± 409 mg/dl,NaN,NaN,NaN,NaN,NaN
2,2.0,Berger 201030,IVIG,100–200 mg/kg/wk,914.8 ± 273.37 mg/dl,0.03,3.42,na,4.5/subject/year,27.5
3,NaN,NaN,16% SCIG,NaN,878 ± 234.77 mg/dl,NaN,NaN,NaN,NaN,NaN
4,3.0,Ballow 201631,IVIG,300–800 mg/kg/wk,800–1000 mg/dl,1 episode,0.051,0.2 ± 1.1,6.2 ± 17.7,20.2
5,NaN,NaN,5% IVIG,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,4.0,Bezrodnik 20138,IVIG,556 mg/kg/month (420–870),960.2 mg/dl,3 episodes in IVIG/1 in SCIG,1.4,0,na,na
7,NaN,NaN,16% SCIG,139 mg/kg/wk (105–181),"1317 mg/dl (wk16), 1309.2 mg/dl (wk 24) and 12...",NaN,0.4,0,na,0.14
8,5.0,Bezrodnik 201432,IVIG (48 weeks),na,1005.33 ± 419.420 mg/dl,4 episodes,2–7,na,na,0.13
9,NaN,NaN,16% SCIG (9 months),133 mg/kg/wk (100–192),1205 ± 457.990 mg/dl,3 episodes,1–2,na,na,0.02
10,6.0,Borte 20179,Period 1-IVIG 10% for 13 wk/SCIG 16% for 12 wks.,125 ± 42 mg/kg/week (20% SCIG),IVIG 10% = 720 mg/dl SCIG 16% = 897 mg/dl,"0 IVIG, 1(0.27) SCIG 16%)","6.29 rate (IVIG), 8.92 rate (SCIG 16%), 4.38 (...","1 (0.12) IVIG,2 (0.54) SCIG 16%",90 (10.69) IVIG/187(50.42) SCIG,0.058
11,NaN,NaN,Period 2-SCIG 20% for 52 wk,NaN,SCIG 20% = 827 mg/dl,1(0.022),200(4.38),7(0.15)-SCIG,710 (15.55),NaN
12,7.0,Borte 201710,10% IVIG (/3 weeks),485 mg/kg/month,1100–1220 mg/dl,NaN,3.68 (overall)4.19 (3 weekly)),na,37 absences (61.95%),Serious AE 13% (4 weekly) vs. 5% in 4 weekly
13,NaN,NaN,10% IVIG (/4 weeks),NaN,810–870 mg/dl,NaN,3.33 (4 weekly),1 (0.08),3.64,NaN
14,8.0,Borte 201133,IVIG/SCIG,200–800 mg/kg/wk,"694 mg/dl (c), 790 mg/dl (a), 781 mg/dl (ad) g/l",0,4.77/5.18 (a)/5.47 (ad),"8.36(c),0(a),0.63(ad)","1.7 (c), na (a), na (ad)","0.04(c),0.035 (a),0.08(ad)/infusion"
15,NaN,NaN,20% SCIG,"129.9 mg/kg/wk -children(c),113.7 mg/kg/wk- ad...","786 mg/dl (c), 791 mg/dl (a), 831 mg/dl (ad)",0,NaN,NaN,NaN,NaN
16,9.0,Haddad 20126,20% SCIG (1:1) EU,120 mg/kg/wk,810 ± 144 mg/dl,0,5.18,3.48,8,0.59 events/infusion (1:1)
17,NaN,NaN,20% SCIG (1.5:1) USA,210 mg/kg/wk,1254 ± 322 mg/dl,0,2.76,0.2,2.06,0.06 in 1:1
18,10.0,Hagan 201011,20% SCIG,179.6–224.3 mg/kg (IgPro20),1210–1290 mg/dl,0,2.76,0.2,2.06,"local AE = 0.592, other than local AE = 0.043"
19,11.0,Jolles 201134,IVIG,NaN,Pre study = 702 mg/dl,1(wash out) = 0.03 events/patient/year,5.18,3.48,8,0.177/infusion
20,NaN,NaN,20% SCIG,120 ± 35.72 mg/kg/wk (20% SCIG),On infusion = 809 mg/dl,NaN,NaN,NaN,NaN,NaN
21,12.0,Kanegane 201435,IVIG,77.3 ± 30.5 mg/kg/month,653 ± 140 mg/dl (IVIG),0,2.98,0.55,3.48,0.461/infusion
22,NaN,NaN,20% SCIG,87.8 ± 35.2 mg/kg/wk SCIG,715 ± 151 mg/dl (SCIG),NaN,NaN,NaN,NaN,NaN
23,13.0,Krivan 201636,IqYmune,220–970 mg/kg,579 ± 203 mg/dl,1 (0.017),3.79,0.89,1.01,0.45/infusion
24,NaN,NaN,NaN,NaN,773/- 236 mg/dk (IVIG),NaN,NaN,NaN,NaN,NaN
25,14.0,Melamed 201637,IVIG 5% 21-day infusion,300–800 mg/kg/wk,21-day infusion = 987–1083 mg/dl,2 (0.09),3.08,3.5,1.1,0.39/infusion
26,NaN,NaN,IVIG 5% 28-day infusion,NaN,28-day infusion = 822–882 mg/dl,NaN,NaN,NaN,NaN,NaN
27,15.0,Moy 201038,IVIG 5%,469.4 mg/kg/month (21-day infusion)466.2 mg/kg...,21-day infusion = 936–1240 mg/dl,0,3.07,2 days,8.73,1 AE/3 infusions
28,NaN,NaN,NaN,NaN,28-day infusion = 833–1140 mg/dl,NaN,NaN,NaN,NaN,NaN
29,16.0,Patel 201539,SCIG 20%,674 mg/kg/wk (260–2000)552 mg/kg/month (IVIG),794 mg/dl (on IVIG) and 943 mg/dl (IGSC 20%),0.03,0.067 rate,na,na,41 (47%) local AEs
30,17.0,Quinti 201117,IVIG,CVID- 398 ± 167 mg/kg/wk,CVID-667 ± 176 mg/dl,0.06–0.1 episodes patient-year,na,na,na,na
31,NaN,NaN,NaN,XLA-608 ± 273 mg/kg/wk,XLA-758 ± 202 mg/dl,0.03–0.11 episodes patient-year,NaN,NaN,NaN,NaN
32,18.0,Stein 201640,10% IVIG,501.7 mg/kg/month,923.9 mg/dl,2 (0.04),2.9,0.6,2.8,44(98%)- 450 events
33,19.0,Suez 201641,IVIG 10% and SCIG 20%,222 ± 71 mg/kg/wk,1523 mg/dl with IGSC and 1200 mg/dl in IVIG 10...,0,3.86 in IVIG,0.02,1.16,0.036/infusion
34,NaN,NaN,NaN,NaN,NaN,NaN,2.41 in SCIG,NaN,NaN,NaN
35,20.0,Viallard 201742,Tegeline,442 mg/kg/month (286–608),Tegeline 805 ± 134 mg/dl,Tegeline-0,Tegeline-4.35 (0–21.8),Tegeline-0,Tegeline-8.8 (6.4–11.9),Tegeline-0.09
36,NaN,NaN,ClairYg,NaN,ClairYg 917 ± 172 mg/dl,ClairYg-0,ClairYg-4.3(0–15.1),ClairYg-0,ClairYg-0.3(0.1–0.9),ClairYg-0.08
37,21.0,Vultaggio 201543,IVIG,Maintenance of total monthly dose of historic ...,Baseline 635 ± 242.8 mg/dl,5 (0.056),33/39 patients (84.6%)- infection,1.93 ± 4.08 (IVIG),15.27 ± 23.17 (IVIG),Local reactions (14/50 = 28%)
38,NaN,NaN,SCIG 16%,NaN,671 ± 217.5 mg/dl,NaN,NaN,0.64 ± 2.94 (SCIG),2.26 ± 4.45 (SCIG),NaN
39,22.0,Wasserman 201244,IVIG 10%,500 mg/kg/wk (254–1029),1076 ± 254 mg/dl (606–1780 mg/dl) in 21-days,2 (0.035),2.6 (2.3–2.7),0.21,2.28,937 events
40,NaN,NaN,NaN,NaN,943 ± 215 mg/dl (487–2250) in 28-days,NaN,NaN,NaN,NaN,NaN
41,23.0,Wasserman 201245,IVIG/SCIG + IGHy vs. IVIG/SCIG alone,IGHy at 75U/g IgG followed by IgG 10% at 155 m...,"<12 yrs = 995 mg/dl, >12 yrs 1070 mg/dl",2(0.025),2.97 (IGHy)4.51 (IVIG),0.02 (IGHy) vs. 0.06 (IVIG),0.28 (IGHy) vs. 0.23 (IVIG),local AE = 0.199/infusion (IGHy)vs. 0.011/infu...
42,NaN,NaN,NaN,NaN,"<12 yrs = 963 mg/dl, >12 yrs = 1040 mg/dl",NaN,NaN,NaN,NaN,NaN
43,24.0,Wasserman 20167,SCIG + IGHy vs. SCIG,155 ± 53 mg/kg/week,"1135 mg/dl (2 week), 1195 mg/dl(3week), 983 mg...",5 (0.03),2.99,0.12,5.75,10.68/subjects' year

--------------------------------------------------------------------------------

[Method Filter - Table 14/20]

,Question,Recommendation,Recommendation trength,Evidence ertainty
0,What is the risk of SARS-CoV-2 vaccine anaphyl...,For patients with no history of a previous sev...,Strong,High
1,NaN,For patients with a history of a severe allerg...,Conditional,Low
2,In patients without a history of anaphylaxis t...,In patients with no history of a severe allerg...,Strong,Low
3,In patients with a history of anaphylaxis to a...,We suggest against the clinician routinely per...,Conditional,Low
4,Should SARS-CoV-2 mRNA or adenovirus-vector va...,We recommend a shared decision-making paradigm...,Strong,Moderate
5,NaN,In patients with a suspected immediate allergi...,Strong,Moderate
6,NaN,In patients with a suspected or confirmed but ...,Strong,Moderate
7,NaN,In patients with a definite/confirmed recent a...,Strong,Low
8,NaN,Whereas all vaccines should be administered in...,Strong,Moderate
9,NaN,We suggest against routine H1-antihistamine or...,Conditional,Low
10,NaN,We recommend in favor of globally coordinated ...,Research recommendation,NaN

--------------------------------------------------------------------------------

[Method Filter - Table 15/20]

,Unnamed: 0,Population,Intervention,Comparator,Outcome,Timings:,Setting,Types of studies
0,Inclusion,Community pharmacistGeneral physician or gener...,All interventions where there is any form of c...,No collaboration or usual care.,"Primary Outcome: Clinical (asthma severity, as...",Interventions administered once or frequently,"Generally, any setting which involves communit...",Types of studies:Any analytical design: involv...
1,Exclusion,Pharmacist assistant involvedNurses & pharmaci...,Not clearly reporting about the collaboration ...,—,"Qualitative outcomes, such as perception, atti...",NaN,Tertiary care hospitalsPharmacies in hospitals...,Editorials & letter to editorReview articles N...

--------------------------------------------------------------------------------

[Method Filter - Table 16/20]

                                       Main findings
0  Elevated IL‐17 serum values in adults and chil...
1  Severe asthma associated with higher IL‐17 lev...
2  Correlation of IL‐17 values with severity of d...
3             In AD, IL‐17 increase in acute disease

--------------------------------------------------------------------------------

[Method Filter - Table 17/20]

,Outcome measures,Importance,Measure unit,Minimal clinically important difference
0,Mortality,Criticala,NaN,NaN
1,Exacerbation rate,Critical,1. Average reduction in the annual number of e...,1. 25% (a minimum reduction of 0.5 exacerbatio...
2,2. Number of patients who experience 0 exacerb...,2. 10 percentage points,NaN,NaN
3,Oral corticosteroid-maintenance treatment,Critical,1. Average %-reduction in daily dose (maintena...,1. 20% (at least 2.5 mg prednisolone equivalen...
4,2. Percentage of patients who are discontinued...,2. 5 percentage points,NaN,NaN
5,3. Percentage of patients who experience ≥ 50%...,10 percentage pointsb,NaN,NaN
6,Lungfunction FEV1,Important,1. Average change in lung function,1. 200 ml
7,2. Percentage of patients who experience an im...,2. 15 percentage points,NaN,NaN
8,Asthma control,Important,Average change in asthma control. A prioritise...,ACQ: 0.5ACT: 3
9,Quality of life (QoL),Important,Average change in QoL. A prioritised list of s...,AQLQ: 0.5
10,Serious adverse events (SAEs),Important,The added number of SAEs,5 percentage points for the added number of SAEs
11,"Specific subgroups of SAEs, including anaphyla...",No minimal clinically important difference is ...,NaN,NaN
12,Drop-out rate,Important,The percentage of patients who dropped out whe...,10 percentage points
13,Sick leave,Important,Average number of sick leave days per year,5 days/year

--------------------------------------------------------------------------------

[Method Filter - Table 18/20]

,Category,Inclusion criteria,Exclusion criteria
0,Sample,Aged 11–19 years with a FA,Aged outside of 11–19 years or without FA
1,Phenomenon of interest,Beliefs of adolescents with FA,"Not explicitly beliefs (e.g., quality of life)..."
2,Design,"Qualitative, quantitative or mixed methods papers","Abstract, presentation, non‐academic articles ..."
3,Evaluation,"Evaluation of title and abstract, and then ful...",No relevant data in main sections
4,Research type,"Qualitative, quantitative, or mixed methods",NaN

--------------------------------------------------------------------------------

[Method Filter - Table 19/20]

            • Acute upper respiratory tract infection
0   - One or more of the following signs: purulent...
1   - The term was also employed for patients diag...
2   • Acute lower respiratory tract infection (inc...
3   - Cough associated with one or more of the fol...
4   - The term was also employed for cases diagnos...
5   • Acute lower respiratory tract infection (inc...
6   - Cough associated with one or more of the fol...
7   - The term was also employed for cases diagnos...
8                             • Acute gastroenteritis
9   - Three or more loose stools per day (or a num...
10  - The term was also employed for cases diagnos...
11                          • Urinary tract infection
12  - Increased body temperature, failure to thriv...
13  - The term was also employed for cases diagnos...
14        • Benign febrile infection without a source
15  - Fever in a previously healthy, otherwise wel...
16  - The term was also employed for cases diagnos...
17                               • Further infections
18  The diagnosis made in the original report was ...

--------------------------------------------------------------------------------

[Method Filter - Table 20/20]

,N,Study,Year,Type of study,Scale/score,Population/comparator,"“Intervention""",Outcome,Founding
0,Omalizumab for a better antiviral response (in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Farmani A.R.,2021.0,Review,AMSTAR low,/,/,/,no
2,2,Menzella F.,2021.0,Review,AMSTAR low,/,/,/,no
3,3,Costanzo G.,2021.0,Review,AMSTAR low,/,/,/,no
4,4,Greene T.T.,2021.0,Review,AMSTAR low,/,/,/,"YES, NIH grants AI145314, AI081923, AI113923 a..."
...,...,...,...,...,...,...,...,...,...
69,46,Chhiba K. D.,2020.0,Observational cohort study,STROBE low,220 patients in Omalizumab,1 COVID-19,1 ICUa,no
70,48,Pfaar O.,2020.0,Review,AMSTAR low,/,/,/,no
71,49,Humbert M.,2021.0,Review,AMSTAR medium,/,/,/,no
72,Biologic therapy for asthma linked to a more s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,47,Eger K.,2021.0,Retrospective cohort study: 120 in Omalizumab/...,NaN,120 patients in Omalizumab,2 COVID-19,2 ICUa,no

--------------------------------------------------------------------------------

✅ Finished displaying 20 tables from 'method' sections!


================================================================================
FILTER 2: TABLES FROM 'RISK OF BIAS' / 'ROB' SECTIONS
================================================================================

Found 26 tables in sections containing 'risk of bias' or 'rob'


[ROB Filter - Table 1/20]

,"Author, year",Randomization process,Deviation from intended interventions,Missing outcome data,Measurement of the outcome,Selection of the reported result,Overall
0,Gerasimov 2010,Low risk,Low risk,Low risk,Some concerns,Some concerns,Some concerns
1,Wu 2011,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
2,Han 2012,Low risk,Low risk,Low risk,Some concerns,Low risk,Some concerns
3,Wang 2015,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
4,Navarro‐López 2017,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
5,Plummer 2019,Low risk,Some concerns,Low risk,Low risk,Low risk,Some concerns
6,Jeong 2020,Some concerns,Some concerns,Low risk,Some concerns,Low risk,Some concerns
7,Ahn 2020,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
8,Cukrowska 2021,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns

--------------------------------------------------------------------------------

[ROB Filter - Table 2/20]

,Study (Ref),Sequence generation,Allocation concealment,Blinding of participants and personnel,Blinding of outcome assessment,Incomplete outcome data,Selective reporting,Other bias
0,Li et al. 2022 [14],Low,Low,Unclear,Unclear,Low,Low,Unclear
1,Drago et al. 2022 [11],Low,Low,Low,Low,Low,Low,Low
2,Liu et al. 2021 [12],Unclear,Unclear,Low,Low,Low,Low,Low
3,Satia et al. 2021 [15],Low,Low,Low,Low,Low,Unclear,Low
4,Huang et al. 2018 [16],Low,Low,Low,Low,Low,Low,Low
5,Giudice et al. 2017 [17],Low,Low,Low,Low,Low,Unclear,Low
6,Liu et al. 2016 [18],Unclear,Low,Unclear,Unclear,Low,Low,Unclear
7,Smith et al. 2016 [19],Low,Low,Low,Low,Low,Unclear,Low
8,Chen 2010 [20],Low,Low,Low,Low,Low,Low,Low
9,Gutkowski et al. 2010 [21],Unclear,Unclear,Low,Low,Low,Low,Unclear
10,Rose et al. 2010 [22],Unclear,Low,Low,Low,Low,Unclear,Low
11,Giovannini et al. 2007 [23],Low,Low,Low,Low,Low,Unclear,Low

--------------------------------------------------------------------------------

[ROB Filter - Table 3/20]

,Item,External validity,Internal validity,Overall Score
0,1. Was the study’s target population a close r...,2. Was the sampling frame a true or close repr...,3. Was some form of random selection used to s...,4. Was the likelihood of nonresponse bias mini...
1,"Altin, 2020 [45]",0,1,1
2,"Barillari, 2020 [46]",1,1,0
3,"Beltrán-Corbellini, 2020 [47]",0,1,0
4,"Bénézit, 2020 [27]",0,1,1
...,...,...,...,...
57,"Wi, 2020 [78]",0,1,1
58,"Yan, 2020a [8]",0,0,1
59,"Yan, 2020b [15]",0,1,1
60,"Zayet, 2020a [43]",0,1,1
61,"Zayet, 2020b [44]",0,1,1

--------------------------------------------------------------------------------

[ROB Filter - Table 4/20]

Empty DataFrame
Columns: [Unnamed: 0]
Index: []

--------------------------------------------------------------------------------

[ROB Filter - Table 5/20]

,Outcome,Study,Risk of Bias domain rating,Explanation of difference between aggregate data and IPD
0,1,2,3,4
1,Eczema by 1 to 2 years,Chalmers 2020,Low,Low
2,Dissanayake 2019,Low,Low,Some concerns
3,Lowe 2018,Low,Low,Some concerns
4,Mc Clanahan 2019,Low,Low,Some concerns
5,Migacheva 2018,Some concerns,Some concerns,Some concerns
6,Skjerven 2020,Low,Low,Some concerns
7,Yonezawa 2018,Low,Low,Some concerns
8,Food allergy (oral food challenge) by 1 to 2 y...,Chalmers 2020,Low,Low
9,Slippages (over the intervention period),Chalmers 2020,Low,Low
10,Simpson 2014,Low,Low,Low
11,Skjerven 2020,Low,Low,Low
12,Skin infection (over the intervention period),Chalmers 2020,Low,Low
13,Mc Clanahan 2019,Low,Low,Low
14,Simpson 2014,Low,Low,Low
15,Stinging/allergic reactions to moisturizers (o...,Mc Clanahan 2019,Low,Low
16,Time to onset of eczema,Horimukai 2014,Low,Low
17,Skjerven 2020,Low,Low,Some concerns
18,Parent report of immediate reaction to common ...,Chalmers 2020,Low,Low
19,Allergic sensitization to a food allergen (1 t...,Chalmers 2020,Low,Low
20,Lowe 2018,Low,Low,Some concerns

--------------------------------------------------------------------------------

[ROB Filter - Table 6/20]

,A,Comparator,Outcome,D1,D2,D3,D4,D5,Overall
0,1,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Placebo,Food allergy–related quality of life,NaN,NaN,NaN,NaN,NaN,NaN
3,2,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
5,3,Control,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
6,3,Control,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
7,4,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
8,4,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
9,5,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
10,5,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
11,6,Control,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
12,6,Control,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
13,7,Control,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
14,7,Control,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
15,8,Baseline,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
16,9,Baseline,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
17,9,Baseline,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
18,10,Baseline,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

[ROB Filter - Table 7/20]

,Certainty assessment,№ of patients,Effect,Certainty,Importance
0,No. of studies,Study design,Risk of bias,Inconsistency,Indirectness
1,SCORAD Index (assessed with: mean difference),NaN,NaN,NaN,NaN
2,2,randomized trials,not serious,not serious,not serious
3,No tolerance (assessed with: relative risk),NaN,NaN,NaN,NaN
4,4,randomized trials,serious b,not serious,not serious

--------------------------------------------------------------------------------

[ROB Filter - Table 8/20]

Empty DataFrame
Columns: [Unnamed: 0, ( x + 1 ) t + x t + ( y + 1 ) t + y t = y t ​ [ X t + Y t + 1 + ( X + Y + 1 ) t ] . superscript 𝑥 1 𝑡 superscript 𝑥 𝑡 superscript 𝑦 1 𝑡 superscript 𝑦 𝑡 superscript 𝑦 𝑡 delimited-[] superscript 𝑋 𝑡 superscript 𝑌 𝑡 1 superscript 𝑋 𝑌 1 𝑡 (x+1)^{t}+x^{t}+(y+1)^{t}+y^{t}=y^{t}[X^{t}+Y^{t}+1+(X+Y+1)^{t}]., Unnamed: 2]
Index: []

--------------------------------------------------------------------------------

[ROB Filter - Table 9/20]

,Conjecture 3,⇔ iff \iff,Conjecture 4
0,⇓ ⇓ \Downarrow,NaN,⇓ ⇓ \Downarrow
1,Conjecture 3 ′ superscript 3 ′ 3^{\prime},⇔ iff \iff,Conjecture 4 ′ superscript 4 ′ 4^{\prime}
2,⇓ ⇓ \Downarrow,NaN,⇓ ⇓ \Downarrow
3,Conjecture 1 1 1,⇔ iff \iff,Conjecture 2 2 2

--------------------------------------------------------------------------------

[ROB Filter - Table 10/20]

,Function,Exceptional,Constraints,Author
0,x 2 i + 1 superscript 𝑥 superscript 2 𝑖 1 x^{2...,Yes,"APN iff ( i , n ) = 1 𝑖 𝑛 1 (i,n)=1",Gold [ 4 ]
1,x 4 i − 2 i + 1 superscript 𝑥 superscript 4 𝑖 ...,Yes,"APN iff ( i , n ) = 1 𝑖 𝑛 1 (i,n)=1","van Lint-Wilson [ 10 ] ,"
2,NaN,NaN,NaN,Janwa-Wilson [ 6 ]
3,x t superscript 𝑥 𝑡 x^{t},No,"t ≡ 3 ​ ( m ​ o ​ d ​ 4 ) , t > 3 formulae-seq...",Janwa-McGuire-Wilson [ 5 ]
4,x 2 i ​ ℓ + 1 superscript 𝑥 superscript 2 𝑖 ℓ ...,No,"g ​ c ​ d ​ ( ℓ , 2 i − 1 ) < ℓ 𝑔 𝑐 𝑑 ℓ supers...",Jedlicka [ 7 ]
5,x 2 i ​ ℓ + 1 superscript 𝑥 superscript 2 𝑖 ℓ ...,No,"g ​ c ​ d ​ ( ℓ , 2 i − 1 ) = ℓ 𝑔 𝑐 𝑑 ℓ supers...",This paper

--------------------------------------------------------------------------------

[ROB Filter - Table 11/20]

,Study,Was the study question clearly stated?,Was the study population clearly described?,Were the cases consecutive?,Were the subjects comparable?,Was the intervention clearly described?,"Were the outcomes clearly defined, valid, reliable, and applied consistently?",Was the length of the follow-up adequate?,Were the statistical methods well described?,Were the results well described?,Quality of Study
0,Baleeiro and Mull32,Yes,No,NR,No,No,No,NR,No,No,Poor
1,Cowan et al33,Yes,Yes,NR,Yes,Yes,Yes,Yes,Yes,Yes,Good
2,McCullagh et al34,Yes,Yes,NR,No,Yes,Yes,Yes,Yes,Yes,Good

--------------------------------------------------------------------------------

[ROB Filter - Table 12/20]

,Study name,Developing and applying appropriate eligibility criteria,Measurement of exposure,Measurement of outcome,Controlling for confounding,Completeness of data
0,• Hollams [13],• Uncertain risk,• High risk,• Low risk,• High risk,• High Risk
1,NaN,• Although the risk of bias is low for the ori...,• “Vit D levels was measured in thawed serum c...,• Low for lung function and BHR,"• Did not match or adjust for maternal atopy, ...",• Outcome data were missing for 30% of the enr...
2,• The used enzyme immunoassay kit “method appe...,NaN,NaN,NaN,NaN,NaN
3,• Measuring Vitamin D levels at one point only...,NaN,NaN,NaN,NaN,NaN
4,Van Oeffelen [12],• High risk,• High risk,• Low risk,• Low risk,• Uncertain Risk
5,"• Out of the larger cohort, a small “selected”...",• Serum samples were defrosted to measure conc...,for asthma (ISAAC score) Low risk for BHR,• Confounders were added to all models (gender...,• Outcome data were missing for 12% of the enr...,NaN
6,• Measured using a competitive enzyme immunoas...,NaN,NaN,NaN,NaN,NaN
7,• Measuring Vitamin D levels at one point only...,• Also considered playing outside and overweig...,NaN,NaN,NaN,NaN
8,Tolppanen [22],• Uncertain risk,• High risk,"• Uncertain risk for asthma, using spirometry ...",• Low risk,• High risk
9,"• Except for the loss of follow up, the cohort...",• The exposures are standardized for age and s...,• Model 1 unadjusted,• Of 5765 participants in the assessment of th...,NaN,NaN
10,• Measured using high pressure liquid chromato...,• High risk for wheezing,• Models 2 and 3 adjusted for respectively 8 a...,NaN,NaN,NaN
11,• Recall bias,• And of 4488 participants in the spirometric ...,NaN,NaN,NaN,NaN
12,• Measuring Vitamin D levels at one point only...,"• Proportion of incident wheezing, and asthma ...",NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

[ROB Filter - Table 13/20]

,Paper,Airway Microbiome Sample,Comparison Groups,Results on Alpha Diversity
0,[17],Oral WashingInduced Sputum,Atopic Asthmatics vs Non-Atopic Asthmatics vs ...,No Significant Differences
1,[25],Induced Sputum,Asthmatics vs Healthy Controls,↑ in Asthmatics
2,[22],Nasal Brushings,Asthmatics vs Healthy Controls (Young Adults v...,No Significant Differences
3,[26],Bronchoalveolar Lavage,Asthmatics vs Healthy Controls,No Significant Differences
4,Corticosteroid-use vs Control,↑ for Corticosteroid use,NaN,NaN
5,[27],Bronchial Brushing,Asthmatics vs Healthy Controls,↑ in Asthmatics
6,Asthmatics more responsive to clarithromycin t...,↑ in Asthmatics who are more responsive to cla...,NaN,NaN
7,[30],Induced Sputum,Neutrophilic asthmatics vs Eosinophilic asthma...,↑ in Eosinophilic asthmatics
8,[18],Stool Sample,Asthmatics after antibiotic treatment vs Asthm...,↓ in Asthmatics after antibiotic treatment
9,[21],Stool Sample,Atopic Asthmatics vs Healthy Controls,No Gender-associated significant differences
10,[29],Stool Sample,Fixed Airway Obstruction vs Reversible Airway ...,No Significant Difference

--------------------------------------------------------------------------------

[ROB Filter - Table 14/20]

,Type of Microbiome,Paper,Microbiome Sample,Comparison Groups,Results on Beta Diversity
0,Airway,[17],Induced SputumOral Washing,Asthmatics vs Healthy Controls,Significantly Different
1,Airway,[22],Nasal Brushings,Asthmatics vs Healthy Controls (Young Adults v...,Significantly Different between Age Groups wit...
2,Airway,[26],Bronchoalveolar Lavage,Asthmatics vs Healthy Controls,Significantly Different
3,Airway,[27],Oropharyngeal swabs,Identified Asthmatic Phenotypes AP1 vs AP2,No Significant Difference
4,Airway,[30],Induced Sputum,Neutrophilic asthmatics vs Eosinophilic asthma...,Significantly Different
5,Gut,[21],Stool Sample,Atopic Asthmatics vs Healthy Controls,Significantly Different
6,Gut,[23],Metagenome Sequencing,Asthmatics vs Healthy Controls,Significantly Different
7,Gut,[29],Stool Sample,Fixed Airway Obstruction vs Reversible Airway ...,Significantly Different

--------------------------------------------------------------------------------

[ROB Filter - Table 15/20]

,Condition,Phylum,Species Implicated
0,Asthma,Bacillota,"Streptococcus ↑17,18 or significantly differen..."
1,"Lactobacillus ↑17,21",NaN,NaN
2,Clostridium ↑23,NaN,NaN
3,Granulicatella ↑17,NaN,NaN
4,Faecalibacterium ↓23,NaN,NaN
5,Bacteroides,↓17,NaN
6,Prevotella*28,NaN,NaN
7,Pseudomonadota,"25,27",NaN
8,"Moraxella ↑17,20 and implicated in young adult...",NaN,NaN
9,"Neisseria ↑17,28",NaN,NaN
10,Escherichia coli ↑21,NaN,NaN
11,Aggregatibacter ↓17,NaN,NaN
12,Haemophilus dominates asthma samples30,NaN,NaN
13,Healthy control,Actinomycetota,Predominant colonization20 and implicated in y...
14,Bacteroides*,[22],NaN

--------------------------------------------------------------------------------

[ROB Filter - Table 16/20]

,Category,Subgroup,Phylum,Species Implicated
0,Age22,Non-asthmatics,Pseudomonadota,↑ proportion in elderly than young adults
1,Actinomycetota,Propionibacterium ↑ relative abundance in elde...,NaN,NaN
2,Corynebacteriales ↑ relative abundance in elde...,NaN,NaN,NaN
3,Asthmatics,Bacillota,Staphylococcus ↑ proportion in young adults th...,NaN
4,Pseudomonadota,Moraxella ↑ relative proportion in young adult...,NaN,NaN
5,Actinomycetota,Propionibacterium ↑ relative proportion in you...,NaN,NaN
6,Young Adults,Bacteroidota,Prevotella relative abundances negatively corr...,NaN
7,Pseudomonadota,Neisseria negatively correlated with lung func...,NaN,NaN
8,Fusobacteriota,Fusobacterium negatively correlated with lung ...,NaN,NaN
9,Elderly,Pseudomonadota,Burkholderia positively correlated with lung f...,NaN
10,Psychrobacter positively correlated with lung ...,NaN,NaN,NaN
11,Actinomycetota,Corynebacterium negatively correlated with lun...,NaN,NaN
12,Asthmatic Phenotypes,Neutrophilic Asthma30,Actinomycetota,↓ proportion for neutrophilic asthma
13,Bacillota,↓ proportion for neutrophilic asthma,NaN,NaN
14,Pseudomonadota,↑ proportion for neutrophilic asthma,NaN,NaN
15,Airway Reversibility29,Bacillota: Pseudomonadota,Enterococcus: Escherichia-Shigella ↑ in Fixed ...,NaN
16,Bacillota,Streptococceae: Streptococcus ↑ in Fixed Airwa...,NaN,NaN
17,Response to Allergens,IgE to Allergens29,Bacillota,"Rumminococcae, Lachnospiraceae and Clostridial..."
18,Functional Genes Pathways17,Pathway 1: Non-asthmatics (Higher),Actinomycetota,Corynebacterium accolens
19,Propionibacterium acnes,NaN,NaN,NaN
20,Pathway 1 and 2 (Higher): Asthmatics,Bacteroidota,Bacteroides caccae,NaN
21,Pseudomonadota,Escherichia coli,NaN,NaN
22,Bacillota,Veillonella parvula,NaN,NaN
23,Actinomycetota,Bifidobacterium longum,NaN,NaN
24,Pathway 2: Non-asthmatics,Actinomycetota,Corynebacterium accolens,NaN
25,Propionibacterium acnes,NaN,NaN,NaN
26,Bacillota,Staphylococcus aureus,NaN,NaN

--------------------------------------------------------------------------------

[ROB Filter - Table 17/20]

,Paper,Airway Microbiome Sample,Comparison Groups,Results on Alpha Diversity
0,[17],Oral WashingInduced Sputum,Atopic Asthmatics vs Non-Atopic Asthmatics vs ...,No Significant Differences
1,[25],Induced Sputum,Asthmatics vs Healthy Controls,↑ in Asthmatics
2,[22],Nasal Brushings,Asthmatics vs Healthy Controls (Young Adults v...,No Significant Differences
3,[26],Bronchoalveolar Lavage,Asthmatics vs Healthy Controls,No Significant Differences
4,Corticosteroid-use vs Control,↑ for Corticosteroid use,NaN,NaN
5,[27],Bronchial Brushing,Asthmatics vs Healthy Controls,↑ in Asthmatics
6,Asthmatics more responsive to clarithromycin t...,↑ in Asthmatics who are more responsive to cla...,NaN,NaN
7,[30],Induced Sputum,Neutrophilic asthmatics vs Eosinophilic asthma...,↑ in Eosinophilic asthmatics
8,[18],Stool Sample,Asthmatics after antibiotic treatment vs Asthm...,↓ in Asthmatics after antibiotic treatment
9,[21],Stool Sample,Atopic Asthmatics vs Healthy Controls,No Gender-associated significant differences
10,[29],Stool Sample,Fixed Airway Obstruction vs Reversible Airway ...,No Significant Difference

--------------------------------------------------------------------------------

[ROB Filter - Table 18/20]

,Type of Microbiome,Paper,Microbiome Sample,Comparison Groups,Results on Beta Diversity
0,Airway,[17],Induced SputumOral Washing,Asthmatics vs Healthy Controls,Significantly Different
1,Airway,[22],Nasal Brushings,Asthmatics vs Healthy Controls (Young Adults v...,Significantly Different between Age Groups wit...
2,Airway,[26],Bronchoalveolar Lavage,Asthmatics vs Healthy Controls,Significantly Different
3,Airway,[27],Oropharyngeal swabs,Identified Asthmatic Phenotypes AP1 vs AP2,No Significant Difference
4,Airway,[30],Induced Sputum,Neutrophilic asthmatics vs Eosinophilic asthma...,Significantly Different
5,Gut,[21],Stool Sample,Atopic Asthmatics vs Healthy Controls,Significantly Different
6,Gut,[23],Metagenome Sequencing,Asthmatics vs Healthy Controls,Significantly Different
7,Gut,[29],Stool Sample,Fixed Airway Obstruction vs Reversible Airway ...,Significantly Different

--------------------------------------------------------------------------------

[ROB Filter - Table 19/20]

,Condition,Phylum,Species Implicated
0,Asthma,Bacillota,"Streptococcus ↑17,18 or significantly differen..."
1,"Lactobacillus ↑17,21",NaN,NaN
2,Clostridium ↑23,NaN,NaN
3,Granulicatella ↑17,NaN,NaN
4,Faecalibacterium ↓23,NaN,NaN
5,Bacteroides,↓17,NaN
6,Prevotella*28,NaN,NaN
7,Pseudomonadota,"25,27",NaN
8,"Moraxella ↑17,20 and implicated in young adult...",NaN,NaN
9,"Neisseria ↑17,28",NaN,NaN
10,Escherichia coli ↑21,NaN,NaN
11,Aggregatibacter ↓17,NaN,NaN
12,Haemophilus dominates asthma samples30,NaN,NaN
13,Healthy control,Actinomycetota,Predominant colonization20 and implicated in y...
14,Bacteroides*,[22],NaN

--------------------------------------------------------------------------------

[ROB Filter - Table 20/20]

,Category,Subgroup,Phylum,Species Implicated
0,Age22,Non-asthmatics,Pseudomonadota,↑ proportion in elderly than young adults
1,Actinomycetota,Propionibacterium ↑ relative abundance in elde...,NaN,NaN
2,Corynebacteriales ↑ relative abundance in elde...,NaN,NaN,NaN
3,Asthmatics,Bacillota,Staphylococcus ↑ proportion in young adults th...,NaN
4,Pseudomonadota,Moraxella ↑ relative proportion in young adult...,NaN,NaN
5,Actinomycetota,Propionibacterium ↑ relative proportion in you...,NaN,NaN
6,Young Adults,Bacteroidota,Prevotella relative abundances negatively corr...,NaN
7,Pseudomonadota,Neisseria negatively correlated with lung func...,NaN,NaN
8,Fusobacteriota,Fusobacterium negatively correlated with lung ...,NaN,NaN
9,Elderly,Pseudomonadota,Burkholderia positively correlated with lung f...,NaN
10,Psychrobacter positively correlated with lung ...,NaN,NaN,NaN
11,Actinomycetota,Corynebacterium negatively correlated with lun...,NaN,NaN
12,Asthmatic Phenotypes,Neutrophilic Asthma30,Actinomycetota,↓ proportion for neutrophilic asthma
13,Bacillota,↓ proportion for neutrophilic asthma,NaN,NaN
14,Pseudomonadota,↑ proportion for neutrophilic asthma,NaN,NaN
15,Airway Reversibility29,Bacillota: Pseudomonadota,Enterococcus: Escherichia-Shigella ↑ in Fixed ...,NaN
16,Bacillota,Streptococceae: Streptococcus ↑ in Fixed Airwa...,NaN,NaN
17,Response to Allergens,IgE to Allergens29,Bacillota,"Rumminococcae, Lachnospiraceae and Clostridial..."
18,Functional Genes Pathways17,Pathway 1: Non-asthmatics (Higher),Actinomycetota,Corynebacterium accolens
19,Propionibacterium acnes,NaN,NaN,NaN
20,Pathway 1 and 2 (Higher): Asthmatics,Bacteroidota,Bacteroides caccae,NaN
21,Pseudomonadota,Escherichia coli,NaN,NaN
22,Bacillota,Veillonella parvula,NaN,NaN
23,Actinomycetota,Bifidobacterium longum,NaN,NaN
24,Pathway 2: Non-asthmatics,Actinomycetota,Corynebacterium accolens,NaN
25,Propionibacterium acnes,NaN,NaN,NaN
26,Bacillota,Staphylococcus aureus,NaN,NaN

--------------------------------------------------------------------------------

✅ Finished displaying 20 tables from 'risk of bias'/'rob' sections!

## Advanced Statistics

In [15]:
# Statistics about tables
print("📊 TABLE STATISTICS\n")
print(f"Total tables: {len(df_tables)}")
print(f"Unique papers: {df_tables['paper_id'].nunique()}")
print(f"Unique sections: {df_tables['section'].nunique()}\n")

print("Tables per section:")
section_counts = df_tables['section'].value_counts()
display(section_counts)

print("\nTables per paper (top 10):")
paper_counts = df_tables['paper_id'].value_counts().head(10)
display(paper_counts)

📊 TABLE STATISTICS

Total tables: 2387
Unique papers: 207
Unique sections: 403

Tables per section:

section
Results                                                                                            337
2.2. The counting function of C = Spec ​ ℤ ¯ 𝐶 ¯ Spec ℤ C=\overline{{\rm Spec}\,\,{\mathbb{Z}}}    140
2.1 Slowly rotating perturbation                                                                   100
RESULTS                                                                                             78
4.1. Gluing two categories using adjoint functors                                                   64
                                                                                                  ...
Subgroup Analyses of the Effects of Physical Exercise on Lung Function of Asthma Patients            1
A Sensitivity Analysis of Physical Exercise on Life of Asthma Patients                               1
Discussion and Analysis                                                                              1
The Influences of Quality of Life on Patients with Asthma                                            1
Italy: adverse event reports for fexofenadine and other oral antihistamines                          1
Name: count, Length: 403, dtype: int64

Tables per paper (top 10):

paper_id
0903.2024      676
0903.2021      440
0903.2019       77
0903.2018       62
0903.2013       61
0903.2016       55
PMC10567967     33
PMC10564082     27
PMC11809425     23
PMC9793734      16
Name: count, dtype: int64