# Find and Display Risk of Bias (RoB) Tables

This script demonstrates the enhanced `ExportReader` capabilities for identifying
Risk of Bias tables using "smart search" based on references and citations.

%% [markdown]
## Import Required Libraries

In [1]:
import pandas as pd
from pathlib import Path
from IPython.display import display, HTML

# Import the export reader library
from scraper.export_reader import load_latest_export

## Load the Export Data

In [2]:
# Load the latest export
try:
    reader = load_latest_export()
    reader.print_summary()
except Exception as e:
    print(f"Error loading export: {e}")
    # Fallback or exit if no export found
    exit(1)

Loading latest export: processed_export_1780342516.json
============================================================
EXPORT SUMMARY
============================================================
Total documents: 283
Export file: /home/jgrzyb/Documents/Python/ai4es-oa-paper-scrapper/notebooks/paper_pipeline_data/exports/processed_export_1780342516.json

Documents by source:
source
pmc      264
arxiv     19

Total tables: 2387
Total images: 1727

Document sections:
  Min sections: 0
  Max sections: 49
  Avg sections: 17.5

============================================================

## Smart Search for RoB Tables
# 

Instead of searching for "method" or "risk of bias" in section titles, 
we search for sections that cite foundational RoB literature (Higgins 2011, Sterne 2019).

In [3]:
print("=" * 80)
print("SMART SEARCH: FINDING TABLES BY CITATION")
print("=" * 80 + "\n")

# Use the new find_rob_tables method
df_rob_tables = reader.find_rob_tables()

if df_rob_tables.empty:
    print("❌ No RoB tables found using the smart search.")
    print("This might be because the papers don't cite the standard RoB tools,")
    print("or the citations weren't extracted correctly.")
else:
    print(f"✅ Found {len(df_rob_tables)} tables citing Risk of Bias tools!\n")
    display(df_rob_tables[['paper_id', 'section', 'matched_rob_refs', 'csv_path']])

================================================================================
SMART SEARCH: FINDING TABLES BY CITATION
================================================================================

✅ Found 47 tables citing Risk of Bias tools!

,paper_id,section,matched_rob_refs,csv_path
0,PMC10258714,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC10258714/table_1.csv
1,PMC10516441,Methods,[B24],tables/PMC10516441/table_0.csv
2,PMC10516441,Methods,[B24],tables/PMC10516441/table_1.csv
3,PMC10516441,Methods,[B24],tables/PMC10516441/table_2.csv
4,PMC10646712,"Literature search, study characteristics, and ...",[Paper cites RoB tools (heading match)],tables/PMC10646712/table_1.csv
5,PMC11005196,Risk of bias results,[CR23],tables/PMC11005196/table_7.csv
6,PMC11187334,Risk of bias,[Paper cites RoB tools (heading match)],tables/PMC11187334/table_5.csv
7,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_4.csv
8,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_5.csv
9,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_6.csv
10,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_7.csv
11,PMC11541770,Results,[bib20],tables/PMC11541770/table_0.csv
12,PMC11541770,Results,[bib20],tables/PMC11541770/table_1.csv
13,PMC11541770,Results,[bib20],tables/PMC11541770/table_2.csv
14,PMC11541770,Results,[bib20],tables/PMC11541770/table_3.csv
15,PMC11770579,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC11770579/table_1.csv
16,PMC11939832,Comparison and Effects of Interventions,[B26],tables/PMC11939832/table_3.csv
17,PMC4064110,Risk of bias,[Paper cites RoB tools (heading match)],tables/PMC4064110/table_3.csv
18,PMC6218986,Risk of Bias in included studies,[Paper cites RoB tools (heading match)],tables/PMC6218986/table_1.csv
19,PMC7552599,Risk of Bias,[Paper cites RoB tools (heading match)],tables/PMC7552599/table_3.csv
20,PMC8501420,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC8501420/table_1.csv
21,PMC8501448,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC8501448/table_1.csv
22,PMC9290056,SYSTEMATIC REVIEW OF AVAILABLE EVIDENCE,[all15076-bib-0008],tables/PMC9290056/table_0.csv
23,PMC9326918,Study characteristics and risk of bias,[Paper cites RoB tools (heading match)],tables/PMC9326918/table_1.csv
24,PMC9483654,Results,[bib18],tables/PMC9483654/table_0.csv
25,PMC9483654,Results,[bib18],tables/PMC9483654/table_1.csv
26,PMC9483654,Results,[bib18],tables/PMC9483654/table_2.csv
27,PMC9704462,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC9704462/table_1.csv
28,PMC9993208,Results,[cit0030],tables/PMC9993208/table_0.csv
29,PMC9993208,Results,[cit0030],tables/PMC9993208/table_1.csv
30,PMC9993210,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC9993210/table_1.csv
31,PMC10349543,Risk of bias in the included studies,[Paper cites RoB tools (heading match)],tables/PMC10349543/table_3.csv
32,PMC11575415,Risk of bias assessment,[Paper cites RoB tools (heading match)],tables/PMC11575415/table_3.csv
33,PMC8362777,Quality assessment,[Paper cites RoB tools (heading match)],tables/PMC8362777/table_3.csv
34,PMC6640016,Quality assessment,[Paper cites RoB tools (heading match)],tables/PMC6640016/table_3.csv
35,PMC9260209,Assessment of risk of bias,[Paper cites RoB tools (heading match)],tables/PMC9260209/table_3.csv
36,PMC9302682,Risk of bias,[Paper cites RoB tools (heading match)],tables/PMC9302682/table_8.csv
37,PMC6033175,Quality assessment for the 15 additional papers,[Paper cites RoB tools (heading match)],tables/PMC6033175/table_3.csv
38,PMC9395947,Quality assessment of studies,[Paper cites RoB tools (heading match)],tables/PMC9395947/table_5.csv
39,PMC9704443,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC9704443/table_1.csv
40,PMC8610064,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC8610064/table_1.csv
41,PMC9704456,"Literature search, study characteristics, and ...",[Paper cites RoB tools (heading match)],tables/PMC9704456/table_1.csv
42,PMC10165145,Quality assessment of guidelines,[Paper cites RoB tools (heading match)],tables/PMC10165145/table_1.csv
43,PMC8330866,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC8330866/table_1.csv
44,PMC11838081,Risk of bias,[Paper cites RoB tools (heading match)],tables/PMC11838081/table_5.csv
45,PMC10182790,Quality Assessment/Risk of Bias in Individual ...,[Paper cites RoB tools (heading match)],tables/PMC10182790/table_1.csv
46,PMC10809821,Study characteristics and risk-of-bias assessment,[Paper cites RoB tools (heading match)],tables/PMC10809821/table_3.csv

## Display Filtered Tables

In [4]:
def show_table(row_index, df_source):
    """Display a specific table from a given dataframe."""
    row = df_source.iloc[row_index]
    pid = row['paper_id']
    
    all_refs = reader.get_all_references_dataframe()
    ref_details = []
    
    for rid in row['matched_rob_refs']:
        if rid == "Paper cites RoB tools (heading match)":
            ref_details.append(f"<li><b>{rid}</b></li>")
            continue
            
        ref_info = all_refs[(all_refs['paper_id'] == pid) & (all_refs['ref_id'] == rid)]
        if not ref_info.empty:
            title = ref_info.iloc[0]['title']
            text = ref_info.iloc[0]['text']
            ref_details.append(f"<li><b>{rid}</b>: {title}<br><small>{text}</small></li>")
        else:
            ref_details.append(f"<li><b>{rid}</b></li>")
            
    ref_list_html = f"<ul>{''.join(ref_details)}</ul>" if ref_details else "None"
    
    # Display metadata
    header = f"""
    <div style="background-color: #e8f4f8; padding: 10px; border-radius: 5px; margin-bottom: 10px; border-left: 5px solid #2980b9;">
        <b>RoB Table #{row_index + 1}</b> | Paper: <b>{pid}</b> | Section: <i>{row['section']}</i>
        <br><b>Matched References:</b>
        {ref_list_html}
    </div>
    """
    display(HTML(header))
    
    # Load and display the table
    try:
        df = reader.load_table_csv(row['csv_path'])
        display(df)
    except FileNotFoundError as e:
        print(f"❌ Error loading table: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
    
    print("-" * 80)

# Display identified tables
if not df_rob_tables.empty:
    display_limit = min(len(df_rob_tables), len(df_rob_tables))
    print(f"Displaying top {display_limit} RoB tables...\n")
    
    for i in range(display_limit):
        try:
            show_table(i, df_rob_tables)
        except Exception as e:
            print(f"Error displaying table {i}: {e}")
            continue

Displaying top 47 RoB tables...

      No.             Author Olopatadine group Ketotifen group Jada scores
0  Number        Age [years]          Male (n)         Methods      Number
1       1     Ul Abidin 2022                31    30.944 ±3.34           –
2       2           Sah 2019                30   24.16 ± 10.22          18
3       3         Patel 2018                60   36.35 ± 11.91          38
4       4  Mortemousque 2014                37     46.6 ± 18.5          13
5       5         Figus 2010                30          37 ±20          15
6       6       Borazan 2009                20     26.9 ± 10.6          10
7       7       Avunduk 2005                16               –           9

--------------------------------------------------------------------------------

,Inclusion criteria,Exclusion criteria
0,Patients older than 18 years,Patients younger than 18 years
1,AERD with or without comorbidities,No AERD
2,ESS (with or without AD + ATAD),Biologics
3,Papers 2016–2023,Older papers
4,"Prospective and retrospective studies, reviews...",Case study descriptions

--------------------------------------------------------------------------------

                                          MeSH terms
0  AERD, N-ERD, NSAID, sinus surgery, ESS, FESS, ...
1  Aspirin, aspirin desensitization, aspirin chal...
2  Asthma, guideline, consensus, position, statem...
3         Assessment, evaluation and recommendations

--------------------------------------------------------------------------------

   Systematic questionnaire to evaluate and select manuscripts
0   Is this a prospective or retrospective study, ...
1       Does it include patients older than 18 years?
2                        AERD diagnose was confirmed?
3   Was ESS performed as single treatment or prior...
4                 Is the surgical extension declared?
5                   Is the patient group followed up?
6                Is the surgical recurrence declared?
7          Are the success or failure rates declared?
8   Do the patients refer receive biologics at any...
9                                    Is SNOT-22 used?
10  What is the impact of this therapeutic interve...
11          Is the conclusion relevant to our review?

--------------------------------------------------------------------------------

       Author Metformin group Control group Jada scores
0      Number     Age [years]      Male (n)        PSAI
1    Tam 2022              35   51.4 ± 13.2           –
2  Singh 2017              20    50.7 ±10.4          12
3  Singh 2016              21    45.1 ±13.0          12

--------------------------------------------------------------------------------

,Study,Was the study question clearly stated?,Was the study population clearly described?,Were the cases consecutive?,Were the subjects comparable?,Was the intervention clearly described?,"Were the outcomes clearly defined, valid, reliable, and applied consistently?",Was the length of the follow-up adequate?,Were the statistical methods well described?,Were the results well described?,Quality of Study
0,Baleeiro and Mull32,Yes,No,NR,No,No,No,NR,No,No,Poor
1,Cowan et al33,Yes,Yes,NR,Yes,Yes,Yes,Yes,Yes,Yes,Good
2,McCullagh et al34,Yes,Yes,NR,No,Yes,Yes,Yes,Yes,Yes,Good

--------------------------------------------------------------------------------

,A,Comparator,Outcome,D1,D2,D3,D4,D5,Overall
0,1,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Placebo,Food allergy–related quality of life,NaN,NaN,NaN,NaN,NaN,NaN
3,2,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
5,3,Control,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
6,3,Control,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
7,4,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
8,4,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
9,5,Placebo,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
10,5,Placebo,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
11,6,Control,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
12,6,Control,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
13,7,Control,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
14,7,Control,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
15,8,Baseline,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
16,9,Baseline,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN
17,9,Baseline,Eliciting dose,NaN,NaN,NaN,NaN,NaN,NaN
18,10,Baseline,Severity of symptoms during challenge,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

,Study,Country,Study design,Number of patients,Study period,Setting,Patient selection (random/consecutive),Patient type and exclusion criteria
0,Iammatteo et al. (2019) [25],USA,Single-arm trial with historical controls,321,DC: January 2016 to December 2017PST: October ...,Outpatient drug allergy clinic,DC: consecutive patients with reported penicil...,Aged ≥ 7 with historical non-life-threatening ...
1,Mustafa et al. (2019) [26],USA,RCT,159,April to August 2018,Outpatient allergy practice,363 consecutive patients with reported penicil...,Aged 5–17 with a history of cutaneous-only rea...
2,Stevenson et al. (2019) [27],Australia,Retrospective study,447,February 2016 to May 2018,Seven immunology outpatient clinics,"All patients, aged ≥ 16 years who underwent PS...",Aged ≥ 16 yearsSome patients (n = 203) were cl...
3,Copaescu et al. (2023) (PALACE) [28],"USA, Canada, and Australia",RCT,382,June 2021 to December 2022,Six allergy outpatient clinics,Out of 446 consecutive patients labeled with a...,Aged ≥ 18 PEN-FAST score < 3Excluded: drug-rel...
4,Ramsey et al. (2023) [29],USA,RCT,38,N.A,N.A,N.A,Pregnant patients with a history of cutaneous-...

--------------------------------------------------------------------------------

,Study,Treatment arm,Comparator arm,Female sex,Age,Condition requiring penicillin
0,Iammatteo et al. (2019) [25],2-step direct DC to oral amoxicillin (n = 155),PST followed by a challenge to amoxicillin (n ...,DC: 77.4% (120)PST: 80% (136),DC: 50.1 ± 2.4PST: 52.1 ± 1.5,Not specified
1,Mustafa et al. (2019) [26],2-step direct DC to oral amoxicillin (n = 79),PST followed by challenge to amoxicillin (n = 80),69.8% (111),38.2 ± 25.0,Not specified
2,Stevenson et al. (2019) [27],1 or 2-step direct DC to oral amoxicillin or c...,PST followed by challenge to amoxicillin or cu...,DC: 55.7% (93)PST: 68.6% (192),DC: 42.4 ± 19.5PST: 47.0 ± 18.3,Not specified
3,Copaescu et al. (2023) (PALACE) [28],"1 or 2-step direct DC with oral amoxicillin, p...",PST followed by 1-step oral challenge (n = 190),65.5% (247),51 (35-66),Not specified
4,Ramsey et al. (2023) [29],2-step direct DC with oral amoxicillin (n = 16),PST followed by a challenge to amoxicillin (n ...,100% (38),28.4 (25.2–30.8),Peripartum prophylaxis in group B strept-colon...

--------------------------------------------------------------------------------

,Study,Drug-challenge,Skin test,Timing of outcome assessment
0,Iammatteo et al. (2019) [25],All graded challenges were single-blind (patie...,PST were performed when appropriate before cha...,DC: 120 minPST: not specified61.9% (n = 96) pa...
1,Mustafa et al. (2019) [26],Oral DC: 1/10 of the target dose of amoxicilli...,PST: skin prick test to volar forearm using th...,DC: 66.7 ± 4.8 minPST: 72.7 ± 5.3 min
2,Stevenson et al. (2019) [27],Oral amoxicillin challenge was performed for p...,PST was selected for each patient according to...,DC: 60 to 90 minPST: not specifiedPhone follow...
3,Copaescu et al. (2023) (PALACE) [28],Oral DC: lowest available therapeutic dose at ...,PST: skin prick test with benzylpenicilloyl po...,DC: 1.8 h (IQR 1.3–3.7)PST: 2.3 (IQR 1.7–5.5)A...
4,Ramsey et al. (2023) [29],N.A,N.A,DC 70 minPST 72 min

--------------------------------------------------------------------------------

                         Immediate allergic reaction
0                      Sensitivity/subgroup analysis
1                              RCTs only (3 studies)
2                               Non-RCTs (2 studies)
3                                Pregnancy (1 study)
4                    Children and adults (3 studies)
5                            Adults only (2 studies)
6   Allergic reaction at longest available follow-up
7                      Sensitivity/subgroup analysis
8                              RCTs only (3 studies)
9                               Non-RCTs (2 studies)
10                               Pregnancy (1 study)
11                   Children and adults (3 studies)
12                           Adults only (2 studies)

--------------------------------------------------------------------------------

,Source (study code),Country (centers),Intent-to-Treat vs. Placebo Participants,Male sex (%),"Age, Mean (Range), y","Asthma, %","Poly-Sensitization, %",Severity of ARC,"Treatment Duration (Preseason + Grass Pollen Season), wks."
0,"Didier, 2007 (VO34.04)",10 countries in Europe (n = 42),"155 vs. 156 randomized,133 vs. 146 completed,1...",56.9,28.9 (18–45),10,54.5,Moderate or severe,16 + 4
1,"Wahn, 2009 (VO52.06)",5 countries in Europe (n = 29),"139 vs. 139 randomized,131 vs. 135 completed,1...",64.3,10.9 (4–17),21.4,59,Moderate or severe,16 + 6
2,"Cox, 2012 (VO61.08USA)",UnitedStates (n = 51),"233 vs. 240 randomized,207 vs. 223 completed,2...",46.6,37.2 (18–65),20.1,78,Severe,18 + 6
3,Horak 2009§ (VO56.07A),Austria (n = 1),"45 vs. 44 randomized,42 vs. 40 completed,45 vs...",41.6,27.3 (18–50),n.r.,n.r.,Moderate or severe,16
4,Long-term study,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Didier 2011 (VO53.06),"10 countries in Europe, Canada, and Russia (n ...","207 vs. 219 randomized,1st year189 vs. 204 com...",62.2,30.5 (18–49),15.3,60.6,Severe,16 + 7 (1st year)16 + 8 (2nd year)16 + 8 (3rd ...

--------------------------------------------------------------------------------

               A. Symptom score1. Fixed effects model
0                                             Studies
1                         5 studies26, 27, 28, 29, 30
2                             4 studies26, 27, 28, 29
3                                 3 studies26, 27, 28
4                                                 NaN
5   2. Subgroup analysis under the random-effects ...
6                                           Subgroups
7                                                 NaN
8                       Adults26,28, 29, 30Children27
9                              Europe26,27,29,30USA28
10               Asthma (>20%)27,28Asthma (<20%)26,30
11                                                NaN
12          B. Medication score1. Fixed effects model
13                                            Studies
14                                                NaN
15                             4 studies26, 27, 28,30
16                                                NaN
17  2. Subgroup analysis under the random-effects ...
18                                          Subgroups
19                                                NaN
20                           Adults26,28,30Children27
21                                Europe26,27,30USA28
22               Asthma (>20%)27,28Asthma (<20%)26,30

--------------------------------------------------------------------------------

,Certainty assessment,№ of patients,Effect,Certainty,Importance
0,№ of studies,Study design,Risk of bias,Inconsistency,Indirectness
1,Symptom score (follow-up: mean 1 years; assess...,NaN,NaN,NaN,NaN
2,5,randomized trials,not serious,not serious,not serious
3,Medication score (follow-up: mean 1 years; ass...,NaN,NaN,NaN,NaN
4,4,randomized trials,not serious,not serious,not serious

--------------------------------------------------------------------------------

,Study,Didier 2007 (VO34.04),Wahn 2009 (VO52.06),Horak 2009 (VO56.07A),Cox 2012 (VO61.08USA),Didier 2011a (VO53.06),Total,P
0,Placebo (n = 156),300 IR (n = 155),Placebo (n = 139),300 IR (n = 139),Placebo (n = 44),300 IR (n = 45),Placebo (n = 240),300 IR (n = 233)
1,Patients with TEAE N (%),76 (48.7),97 (62.6),114 (82),118 (84.9),14 (31.8),27 (60.0),54 (22.5)
2,Discontinuation due to AE N (%),0 (0),8 (5.1),2 (1.4),7 (5),2 (4.5),1 (2.2),2 (0.8)

--------------------------------------------------------------------------------

,No.,"Author, year",Alcaftadine group,Olopatadine group,Jadad scores
0,Number,Age [years],Male (n),Ocular symptom score,Methods
1,1,"Singh, 2022",50,41.8,32
2,2,"Krishnan, 2022",60,27.9 ±7.7,39
3,3,"Manoj, 2022",50,28.43 ±10.43,28
4,4,"Renuka, 2021",30,29.78 ±11.63,21
5,5,"Fujishima, 2021",53,38.1 ±11.82,27
6,6,"Ayyappanavar, 2021",60,28.66 ±9.12,38
7,7,"Poonam, 2020",50,30.15 ±11.02,34
8,8,"Sanjeev, 2020",40,29.32 ±10.54,26
9,9,"Dudeja, 2019",15,–,9
10,10,"Agarwal, 2017",47,–,20
11,11,"Ackerman, 2013",43,39.3 ±12.4,12
12,12,"Barlesi, 2013",34,41.0 ±14.1,13

--------------------------------------------------------------------------------

,Outcome measurement,"RCTs, n","Comparisons, n","Patients, n",Effect (95% confidential intervals),Certainty of the evidence (GRADE),Comments
0,RQLQ sleep domain,8,12,"3,961",SMD: 0.292 (0.235 to 0.350),⊕⊕⊕◯ Moderatea,Significant improvement in sleep quality among...
1,Nocturnal Rhinoconjunctivitis Quality of Life ...,1,2,"1,068",SMD: 0.284 (0.164 to 0.404),⊕⊕⊕⊕ High,"Improvement observed, but evidence is limited ..."
2,Epworth Sleepiness Scale,2,2,74,SMD: 0.027 (−0.429 to 0.483),⊕⊕⊕◯ Moderateb,No significant improvement in sleepiness
3,Sensitivity Analysis: RQLQ sleep domain exclud...,6,8,"2,799",SMD: 0.304 (0.235 to 0.373),⊕⊕⊕⊕ High,Significant improvement in sleep quality among...
4,Subgroup Analysis: RQLQ sleep domain for patie...,4,6,"2,018",SMD: 0.329 (0.250 to 0.408),⊕⊕⊕⊕ High,Significant improvement in sleep quality among...
5,Subgroup Analysis: RQLQ sleep domain for patie...,4,6,"1,943",SMD: 0.252 (0.168 to 0.336),⊕⊕◯◯ Lowc,Low certainty evidence suggests significant im...

--------------------------------------------------------------------------------

,Study name,Developing and applying appropriate eligibility criteria,Measurement of exposure,Measurement of outcome,Controlling for confounding,Completeness of data
0,• Hollams [13],• Uncertain risk,• High risk,• Low risk,• High risk,• High Risk
1,NaN,• Although the risk of bias is low for the ori...,• “Vit D levels was measured in thawed serum c...,• Low for lung function and BHR,"• Did not match or adjust for maternal atopy, ...",• Outcome data were missing for 30% of the enr...
2,• The used enzyme immunoassay kit “method appe...,NaN,NaN,NaN,NaN,NaN
3,• Measuring Vitamin D levels at one point only...,NaN,NaN,NaN,NaN,NaN
4,Van Oeffelen [12],• High risk,• High risk,• Low risk,• Low risk,• Uncertain Risk
5,"• Out of the larger cohort, a small “selected”...",• Serum samples were defrosted to measure conc...,for asthma (ISAAC score) Low risk for BHR,• Confounders were added to all models (gender...,• Outcome data were missing for 12% of the enr...,NaN
6,• Measured using a competitive enzyme immunoas...,NaN,NaN,NaN,NaN,NaN
7,• Measuring Vitamin D levels at one point only...,• Also considered playing outside and overweig...,NaN,NaN,NaN,NaN
8,Tolppanen [22],• Uncertain risk,• High risk,"• Uncertain risk for asthma, using spirometry ...",• Low risk,• High risk
9,"• Except for the loss of follow up, the cohort...",• The exposures are standardized for age and s...,• Model 1 unadjusted,• Of 5765 participants in the assessment of th...,NaN,NaN
10,• Measured using high pressure liquid chromato...,• High risk for wheezing,• Models 2 and 3 adjusted for respectively 8 a...,NaN,NaN,NaN
11,• Recall bias,• And of 4488 participants in the spirometric ...,NaN,NaN,NaN,NaN
12,• Measuring Vitamin D levels at one point only...,"• Proportion of incident wheezing, and asthma ...",NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

,Certainty assessment,№ of patients,Effect,Certainty,Importance
0,No. of studies,Study design,Risk of bias,Inconsistency,Indirectness
1,SCORAD Index (assessed with: mean difference),NaN,NaN,NaN,NaN
2,2,randomized trials,not serious,not serious,not serious
3,No tolerance (assessed with: relative risk),NaN,NaN,NaN,NaN
4,4,randomized trials,serious b,not serious,not serious

--------------------------------------------------------------------------------

,Item,External validity,Internal validity,Overall Score
0,1. Was the study’s target population a close r...,2. Was the sampling frame a true or close repr...,3. Was some form of random selection used to s...,4. Was the likelihood of nonresponse bias mini...
1,"Altin, 2020 [45]",0,1,1
2,"Barillari, 2020 [46]",1,1,0
3,"Beltrán-Corbellini, 2020 [47]",0,1,0
4,"Bénézit, 2020 [27]",0,1,1
...,...,...,...,...
57,"Wi, 2020 [78]",0,1,1
58,"Yan, 2020a [8]",0,0,1
59,"Yan, 2020b [15]",0,1,1
60,"Zayet, 2020a [43]",0,1,1
61,"Zayet, 2020b [44]",0,1,1

--------------------------------------------------------------------------------

           Author Nigella sativa group Control group              Jadad score
0          Number          Age [years]    Female (n)  Body mass index [kg/m2]
1      Salem 2017                   26    37.5 ±12.7                       18
2     Koshak 2017                   40        39 ±13                       25
3  Barlianto 2017                   14   8.79 ±2.940                        9
4  Boskabady 2007                   15             –                        –

--------------------------------------------------------------------------------

,No.,Author,OC 000459 group,Control group,Jadad scores
0,Sample size,Age [years] Mean (SD) or Mean (range),Male (n),FEV1 [l] Mean (SD),Predicted FEV1 (%) Mean (SD)
1,1,Pettipher 2014,134,40.4 (11.4),55
2,2,Singh 2013,13,31.1 (7.1),–
3,3,Horak 2012,18,28.9 (6.8),18
4,4,Barnes 2012,65,43.4 (18–55),38

--------------------------------------------------------------------------------

,Study nameref,FEV1 improvement for SITT versus ICS/LABA,Reduction of moderate‐severe exacerbation for SITT versus ICS/LABA
0,TRIMARAN10 BDP/FF/GLY versus BDP/FF,57 mL (95% CI 15–99; p = .0080) for medium dose,"15% (RR 0.85, 95% CI 0.73–0.99; p = .033) for ..."
1,TRIGGER10 BDP/FF/GLY versus BDP/FF BDP/FF/GLY ...,73 mL (95% CI 26–120; p = .0025) for high dose...,"12% (RR 0.88, 95% CI 0.75–1.03; p = .11) for h..."
2,IRIDIUM15 MF/IND/GLY versus MF/IND MF/IND/GLY ...,76 mL (p < .001) for medium dose65 mL (p < .00...,"13% (RR 0.87, 95% CI 0.71–1.06; p = .17) for m..."
3,ARGON17 MF/IND/GLY versus FP/SLM+TIO,High‐dose and medium‐dose MF/IND/GLY were non‐...,Medium‐dose MF/IND/GLY versus FP/SLM high dose...
4,CAPTAIN18 F/UMEC/VI 100/62.5/25 versus F/VI 10...,"110 mL (66, 153; p < .001) for medium dose 92 ...",No statistically significant difference F/UMEC...

--------------------------------------------------------------------------------

,Study,Country,Treatment regimen,Dosing,No. of patients,Treatment duration
0,Paller AS [26],China,Dupilumab,"300 mg q4w, 200/300 mg q2w",84.0,16 weeks
1,Placebo,NaN,85,NaN,NaN,NaN
2,Simpson EL [27],USA,Dupilumab,"300 mg qw, 300 mg q2w",447.0,16 weeks
3,Placebo,NaN,224,NaN,NaN,NaN
4,Blauvelt A [28],USA,Dupilumab + TCS,"300 mg qw, 300 mg q2w",425.0,52 weeks
5,Placebo + TCS,NaN,315,NaN,NaN,NaN
6,Blauvelt A [29],USA,Dupilumab,300 mg qw,97.0,16 weeks
7,Placebo,NaN,97,NaN,NaN,NaN
8,de Bruin-Weller M [30],Netherlands,Dupilumab + TCS,"300 mg qw, 300 mg q2w",217.0,16 weeks
9,Placebo + TCS,NaN,108,NaN,NaN,NaN
10,Deleuran M [31],Denmark,Dupilumab,300 mg qw,249.0,76 weeks
11,Placebo,NaN,398,NaN,NaN,NaN
12,Worm M [32],Germany,Dupilumab,"300 mg qw/q2w, 300 mg q4w, 300 mg q8w",339.0,36 weeks
13,Placebo,NaN,83,NaN,NaN,NaN
14,Tsianakas A [33],Germany,Dupilumab,300 mg qw,32.0,12 weeks
15,Placebo,NaN,32,NaN,NaN,NaN
16,Beck LA [34],USA,Dupilumab,300 mg qw,55.0,16 weeks
17,Placebo,NaN,54,NaN,NaN,NaN
18,Thaci D [35],Germany,Dupilumab + TCS,"300 mg qw, 300 mg, q2w, 300 mg q4w, 200 mg qw,...",318.0,16 weeks
19,Placebo + TCS,NaN,61,NaN,NaN,NaN
20,Bieber T,Germany,Dupilumab,200 mg q2w,243.0,12 weeks
21,Placebo,NaN,131,NaN,NaN,NaN

--------------------------------------------------------------------------------

   Characteristics of studies with median or mean number of ARTIs without SD or SE or a difference between them
0                                              Author
1                                        Caramia 1994
2                               Carriere-Roussel 2017
3                                           Chen 2004
4                                           Dils 1979
5                                        Fiocchi 1988
6                                          Longo 1988
7                                       Passali 1994a
8                                          Pozzi 2004
9                                  Riedl-Seifert 1995
10                                       Schaad 2010b
11  Characteristics of the studies reporting clini...
12                                       Fiocchi 1989
13                                    Giovannini 2000
14                                          Mora 2002
15                                          Mora 2007
16                                         Renzo 2004
17  Characteristics of the studies reporting the p...
18                                        Burgio 1994
19                                      Careddu 1994b
20                                       Göhring 2017
21                                        Fukuda 1999
22                                         Mora 2010a
23                                    Padayachee 2014
24                                         Paupe 1991
25                                   Rutishauser 1998
26                                    Santamaria 2019
27                                        Taylor 2003
28                                          Wahl 2008
29  Characteristics of the Studies Reporting Diver...
30                                    Andrianova 2003
31                                        Collet 1993
32                              Espinosa Rosales 2009
33                                       Fiocchi 2012
34                                     Iuldashev 1988
35                                        Mameli 2015
36                                 Martin du Pan 1982
37                                        Sramek 1986

--------------------------------------------------------------------------------

               Author, year                        Reasons for their exclusion
0             Almeida, 1999             Participants with asthma were included
1            Banovcin, 1992  The trial was not double-blind or placebo-cont...
2                Barr, 1965                      Trial with asthmatic children
3             Barrett, 2010                  Children and adults were included
4               Braido 2014                         Clinical trial with adults
5             Carlone, 2014                         Clinical trial with adults
6             Colombo, 2014                     Not a placebo-controlled trial
7                 Das, 2000              Participants' ages were not specified
8     Doody-Oppikofer, 1998  The study examined only the acute phase of inf...
9               Erman, 2009             A poorly defined homeopathic treatment
10         Fintelmann, 2012                         Clinical trial with adults
11            Fontana, 1965            Clinical trial with children and adults
12           Graubaum, 2012                         Clinical trial with adults
13           Grimfeld, 2004             An antihistamine was used in the trial
14              Grimm, 1999  Children and adults were not separated in the ...
15              Heinz, 2010                         Clinical trial with adults
16      Herrera-Basto, 1998  Researchers compared the effect of pidotimod o...
17              Jawad, 2012                         Clinical trial with adults
18            Jesenak, 2013            Trials comparing vitamin C with placebo
19        Kondrat'eva, 2009             A poorly defined homeopathic treatment
20       Kozhukharova, 1987  The trial was not double-blind or placebo-cont...
21              Kudin, 2009             A poorly defined homeopathic treatment
22          Lauriello, 1990  Researchers compared the effect of the interve...
23                Lee, 2012                         Clinical trial with adults
24             Licari, 2014  The trial was not double-blind or placebo-cont...
25          Luchikhin, 2000  The trial was not double-blind or placebo-cont...
26                 Ma, 1994  The trial was not double-blind or placebo-cont...
27             Macchi, 2005                         Clinical trial with adults
28       Makovetskaya, 2001  The trial was not double-blind or placebo-cont...
29          Mohammadi, 2014                     Not a placebo-controlled trial
30              Mora, 2010b  A trial without the prevention approach for ac...
31            Mueller, 1969             Participants with asthma were included
32  Namazova-Baranova, 2015                     Not a placebo-controlled trial
33            Nespoli, 1992                     Not a placebo-controlled trial
34    Obrosova-Serova, 1972  The trial was not double-blind or placebo-cont...
35            Oggiano, 1985                           Open trial with children
36             Oldini, 1990  Children and adults were not separated in the ...
37   Ortega del Alamo, 2005  Researchers compared the effect of the interve...
38              Predy, 2005                         Clinical trial with adults
39             Prusek, 1987                     Not a placebo-controlled trial
40               Razi, 2010             Participants with asthma were included
41         Rosaschino, 2004                                         Open trial
42              Rossi, 2004                         Clinical trial with adults
43               Ruah, 2001                     Not a placebo-controlled trial
44              Rytel, 1974                         Clinical trial with adults
45             Scotti, 1987                     Not a placebo-controlled trial
46             Sly PD, 2019  Only related to lower respiratory tract infect...
47         Steinsbekk, 2005             A poorly defined homeopathic treatment
48          Tiralongo, 2012                         Clinical trial with adults
49           Vascotto, 1985                     Not a placebo-controlled trial
50               Yale, 2004                         Clinical trial with adults
51           Zagólski, 2015                     Not a placebo-controlled trial

--------------------------------------------------------------------------------

  Patient or population: children aged under 18 years of age susceptible to acute respiratory tract infections from clinics, private practices, hospital departments, schools, orphanages, etc.Intervention: Any immunostimulant with a trial period of 3–12 months.Comparison: PlaceboO: Number of ARTIs per treatment group during the study periodS: Randomized controlled trialsT: Trials of 3–12 months duration published from January 1965 to January 10, 2022).
0                                           Outcomes
1                                       Assumed risk
2                                            Placebo
3                                    Number of ARTIs
4                               Ratio of Means ARTIs
5       Incidence of gastrointestinal adverse events
6                   Incidence of skin adverse events

--------------------------------------------------------------------------------

,No.,Author,Guselkumab group,Adalimumab group,Jada scores
0,Number,Age [years],Female (n),BMI [kg/m2],Duration of psoriasis [years]
1,1,Reich 2017,496,43.7 ±12.2,147
2,2,Blauvelt 2017,329,43.9 ±12.74,89
3,3,Gordon 2015,208,"44.0, median",59

--------------------------------------------------------------------------------

,Author,Year,Study design,Country,Age,LUS probe,Lung fields,Diagnostic LUS findings,LUS/CXR,Patients,Pneumonia,TP,TN,FP,FN
0,Caiulo [31],2013,Prospective,Italy,1–16 y,Linear,6.0,"ConsolidationsFBL, PLA",LUS,102.0,89.0,88.0,13.0,0.0,1.0
1,CXR,81,13,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Reali [32],2014,Prospective,Italy,0–16 y,Linear,4.0,ConsolidationsFBL,LUS,107.0,81.0,76.0,25.0,1.0,5.0
3,CXR,66,24,2,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dianova [33],2015,Prospective,Russia,0–18 y,"Linear,convex",6.0,Consolidations,LUS,154.0,154.0,147.0,0.0,0.0,7.0
5,CXR,126,0,0,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Iorio [34],2015,Retrospective,Italy,0–12 y,Linear,6.0,Consolidations,LUS,52.0,29.0,28.0,22.0,1.0,1.0
7,CXR,25,22,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ho [35],2015,Retrospective,Taiwan,73.2 m,Convex,6.0,Consolidations,LUS,163.0,163.0,159.0,0.0,0.0,4.0
9,CXR,151,0,0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Urbankowska [36],2015,Prospective,Poland,0–18 y,Linear,6.0,Consolidations,LUS,106.0,106.0,71.0,0.0,5.0,30.0
11,CXR,76,0,0,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Guerra [37],2016,Prospective,Italy,0–16,"Convex, Linear",6.0,Consolidations,LUS,222.0,222.0,207.0,0.0,7.0,8.0
13,CXR,197,0,17,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Yadav [38],2017,Prospective,India,0–5,Micro convex,6.0,"Consolidations,PE, FBL",LUS,118.0,106.0,105.0,0.0,0.0,13.0
15,CXR,101,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Sharif [39],2021,Prospective,Pakistan,2–12 y,Linear,6.0,Consolidation,LUS,100.0,64.0,64.0,0.0,0.0,36.0
17,CXR,50,0,0,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

,Author,LUS/CXR,Sensitivity (95% CI),Specificity (95% CI),Positive predictive value (95% CI),Negative predictive value (95% CI)
0,Caiulo [31],LUS,98.9% (93.9–100),100% (75.3–100),100% (95.9–100),92.9% (66.1–99.8)
1,CXR,91% (83.1–96.0),100% (75.3–100),100% (95.5–100),61.9% (38.4–81.9),NaN
2,Reali [32],LUS,93.8% (86.2–98.0),96.2% (80.4–99.9),98.7% (93.0–100),86.2% (68.3–96.1)
3,CXR,81.5% (71.3–89.2),92.3% (74.9–99.1),97.1% (89.8–99.6),61.5% (44.6–76.6),NaN
4,Dianova [33],LUS,95.5% (90.0–98.2),NaN,100% (97.5–100),0.0% (0.0–41.0)
5,CXR,81.8% (74.8–87.6),NaN,100% (97.1–100),0.0% (0–12.3),NaN
6,Iorio [34],LUS,96.6% (82.2–99.9),95.7% (78.1–99.9),96.6% (82.2–99.9),95.7% (78.1–99.9)
7,CXR,86.2% (68.3–96.1),95.7% (78.1–99.9),96.2% (80.4–99.9),84.6% (65.1–95.6),NaN
8,Ho [35],LUS,97.5% (93.8–99.3),NaN,100% (97.7–100),0.0% (0.0–60.2)
9,CXR,92.6% (87.5–96.1),NaN,100% (97.0–100),0.0% (0.0–26.5),NaN
10,Urbankowska [36],LUS,93.0% (85.0–98.0),100% (88.0–100),100% (95.9–100),0.0% (0.0–41.0)
11,CXR,100% (95.0–100),100% (88.0–100),100% (95.5–100),0.0% (0–12.3),NaN
12,Guerra [37],LUS,97.0% (93.0–99.0),100% (63.0–100),100% (95.9–100),0.0% (0.0–41.0)
13,CXR,92% (88.0–95.0),100% (63.0–100),100% (95.5–100),0.0% (0–12.3),NaN
14,Yadav [38],LUS,89.0% (81.9–94.0),NaN,100% (96.5–100),0.0% (0.0–24.7)
15,CXR,85.6% (77.9–91.4),NaN,100% (96.4–100),0.0% (0.0–19.5),NaN
16,Sharif [39],LUS,100% (93.0–100),92.3% (63.0–99.9),95.31% (95.9–99.9),100% (78.1–100)
17,CXR,81.96% (80.0–95.0),100% (63.0–100),100% (95.5–100),78.0% (68.3–96.1),NaN
18,Total,LUS,95.5% (93.6–97.1),96.3% (92.1–98.4),99.0% (97.8–99.8),63.6% (40.7–82.7)
19,CXR,87.4% (84.3–90.0),98.6% (95.8–99.6),99.5% (99.1–99.9),44.6% (20.4–68.3),NaN

--------------------------------------------------------------------------------

              Author Apremilast group Control group  Jada scores
0             Number              Age    Female (n)  BMI [kg/m2]
1  Van Voorhees 2020              201    47.0 ±15.0           76
2   Bissonnette 2018               50     56.6 ±8.6           30
3         Reich 2017               84    46.0 ±13.6           34
4          Paul 2015              274    45.3 ±13.1           98
5          Papp 2015              562    45.8 ±13.1          183
6        Strand 2013               88    44.1 ±14.7           38
7          Papp 2013               85    48.4 ±12.3           36

--------------------------------------------------------------------------------

,"Author, year",Randomization process,Deviation from intended interventions,Missing outcome data,Measurement of the outcome,Selection of the reported result,Overall
0,Gerasimov 2010,Low risk,Low risk,Low risk,Some concerns,Some concerns,Some concerns
1,Wu 2011,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
2,Han 2012,Low risk,Low risk,Low risk,Some concerns,Low risk,Some concerns
3,Wang 2015,Low risk,Low risk,Low risk,Low risk,Low risk,Low risk
4,Navarro‐López 2017,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
5,Plummer 2019,Low risk,Some concerns,Low risk,Low risk,Low risk,Some concerns
6,Jeong 2020,Some concerns,Some concerns,Low risk,Some concerns,Low risk,Some concerns
7,Ahn 2020,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns
8,Cukrowska 2021,Some concerns,Low risk,Low risk,Some concerns,Low risk,Some concerns

--------------------------------------------------------------------------------

,Study (Ref),Sequence generation,Allocation concealment,Blinding of participants and personnel,Blinding of outcome assessment,Incomplete outcome data,Selective reporting,Other bias
0,Li et al. 2022 [14],Low,Low,Unclear,Unclear,Low,Low,Unclear
1,Drago et al. 2022 [11],Low,Low,Low,Low,Low,Low,Low
2,Liu et al. 2021 [12],Unclear,Unclear,Low,Low,Low,Low,Low
3,Satia et al. 2021 [15],Low,Low,Low,Low,Low,Unclear,Low
4,Huang et al. 2018 [16],Low,Low,Low,Low,Low,Low,Low
5,Giudice et al. 2017 [17],Low,Low,Low,Low,Low,Unclear,Low
6,Liu et al. 2016 [18],Unclear,Low,Unclear,Unclear,Low,Low,Unclear
7,Smith et al. 2016 [19],Low,Low,Low,Low,Low,Unclear,Low
8,Chen 2010 [20],Low,Low,Low,Low,Low,Low,Low
9,Gutkowski et al. 2010 [21],Unclear,Unclear,Low,Low,Low,Low,Unclear
10,Rose et al. 2010 [22],Unclear,Low,Low,Low,Low,Unclear,Low
11,Giovannini et al. 2007 [23],Low,Low,Low,Low,Low,Unclear,Low

--------------------------------------------------------------------------------

,"First author, publication year",Selection,Comparability#,Exposure,Total points
0,"Lee, 2008 [24]",**,–,***,5
1,"Tadbir, 2012 [17]",****,**,***,9
2,"Chang, 2013 [21]",***,**,***,8
3,"Andisheh-Tadbir, 2014 [18]",****,**,***,9
4,"Lotfi, 2015 [19]",***,**,***,8
5,"Jiang, 2016 [6]",***,**,***,8
6,"Yu, 2016 [25]",**,*,***,6
7,"Ghallab, 2017 [26]",****,**,***,9
8,"Nosratzehi, 2017 [20]",**,–,***,5
9,"Peisker, 2017 [22]",***,**,***,8
10,"Schiegnitz, 2017 [23]",**,*,***,6
11,"Lee, 2018 [24]",***,–,***,6
12,"Choudhry, 2019 [27]",***,**,***,8

--------------------------------------------------------------------------------

,"Reference (first author, year)",Adequate definition .of cases*,Representativenessof cases*,Selection of control subjects*,Definition of control subjects*,Control for important factor or additional factorΔ,Exposure assessment*,Same method of ascertainment for all subjects*,Nonresponse rate•,Total quality scores
0,"Levrini, 2006 [19]",*,*,–,–,**,*,*,*,7.0
1,"Mikulewicz, 2011 [16]",*,*,–,*,**,*,*,*,8.0
2,"Abtahi, 2013 [5]",*,*,*,*,**,*,*,–,8.0
3,"Martín-Cameán, 2014 [18]",*,*,–,*,–,*,*,*,6.0
4,"Mikulewicz, 2015 [17]",*,*,*,–,–,*,*,*,6.0
5,"Jamshidi, 2018 [3]",*,*,*,*,*,*,*,–,7.0
6,Mean score,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

Empty DataFrame
Columns: [Unnamed: 0]
Index: []

--------------------------------------------------------------------------------

,Outcome,Study,Risk of Bias domain rating,Explanation of difference between aggregate data and IPD
0,1,2,3,4
1,Eczema by 1 to 2 years,Chalmers 2020,Low,Low
2,Dissanayake 2019,Low,Low,Some concerns
3,Lowe 2018,Low,Low,Some concerns
4,Mc Clanahan 2019,Low,Low,Some concerns
5,Migacheva 2018,Some concerns,Some concerns,Some concerns
6,Skjerven 2020,Low,Low,Some concerns
7,Yonezawa 2018,Low,Low,Some concerns
8,Food allergy (oral food challenge) by 1 to 2 y...,Chalmers 2020,Low,Low
9,Slippages (over the intervention period),Chalmers 2020,Low,Low
10,Simpson 2014,Low,Low,Low
11,Skjerven 2020,Low,Low,Low
12,Skin infection (over the intervention period),Chalmers 2020,Low,Low
13,Mc Clanahan 2019,Low,Low,Low
14,Simpson 2014,Low,Low,Low
15,Stinging/allergic reactions to moisturizers (o...,Mc Clanahan 2019,Low,Low
16,Time to onset of eczema,Horimukai 2014,Low,Low
17,Skjerven 2020,Low,Low,Some concerns
18,Parent report of immediate reaction to common ...,Chalmers 2020,Low,Low
19,Allergic sensitization to a food allergen (1 t...,Chalmers 2020,Low,Low
20,Lowe 2018,Low,Low,Some concerns

--------------------------------------------------------------------------------

,QHES criteria no.a,Atherly et al (2009)10,Bhaumik et al (2013)16,Castro et al (2003)21,Fabian et al (2014)17,Flores et al (2009)11,Higgins et al (1998)20,Karnick et al (2007)18,Lara et al (2013)12,McCowan et al (1997)22,Mogasale et al (2013)13,Ryan et al (2012)14,Smith et al (2012)24,Tai et al (2011)19,Turcotte et al (2014)23,Willems et al (2007)15
0,1,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7,7,7.0,7,7.0,7.0
1,2,2.0,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,2,2,2.0,2,0.0,2.0
2,3,8.0,6.0,8.0,4.0,8.0,6.0,8.0,6.0,8.0,8,8,8.0,6,6.0,8.0
3,4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0,0,0.0,0,0.0,1.0
4,5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,0.0,9,9,4.5,0,4.5,9.0
5,6,6.0,6.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,6,0,6.0,0,0.0,6.0
6,7,5.0,5.0,5.0,0.0,5.0,5.0,5.0,5.0,0.0,5,5,5.0,5,5.0,5.0
7,8,7.0,7.0,0.0,5.0,7.0,7.0,7.0,7.0,0.0,0,7,7.0,0,7.0,7.0
8,9,6.0,6.0,2.0,6.0,8.0,8.0,8.0,6.0,8.0,8,6,6.0,8,8.0,8.0
9,10,6.0,6.0,4.0,0.0,6.0,4.0,4.0,6.0,4.0,0,4,6.0,0,4.0,4.0
10,11,0.0,7.0,7.0,0.0,7.0,7.0,7.0,7.0,7.0,7,0,7.0,0,7.0,7.0
11,12,4.0,8.0,8.0,4.5,4.0,8.0,8.0,5.0,2.0,8,8,8.0,2,4.0,8.0
12,13,3.5,7.0,3.5,7.0,3.5,3.5,3.5,3.5,3.5,7,7,7.0,7,7.0,3.5
13,14,0.0,6.0,6.0,0.0,0.0,6.0,6.0,3.0,0.0,0,3,0.0,6,0.0,6.0
14,15,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8,8,8.0,8,8.0,8.0
15,16,0.0,3.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,3,3,3.0,0,3.0,0.0
16,Total,67.0,90.5,66.0,54.0,77.0,74.0,84.0,71.0,50.5,78,77,84.5,51,70.5,89.5

--------------------------------------------------------------------------------

,"Author, year and country","Quality of basic diagnostic methodology as per international guidelines4, 5, 6, 19, 20, 21, 22, 23, 24, 25 (Yes/No):Clinical historyClinical examinationSerum tryptase (2 samples)Skin tests (prick and intradermal)Patch testsDPTs,Serum Ig E",Patients characterized as per current international guidelines (Yes/HSR not investigated/confirmed),Quality assessment and limitations of study (use of the Critical Appraisal Skills Programme (CASP)18 cohort study checklist)
0,MDAS,NaN,NaN,NaN
1,"Nettis et al., 200129 Italy",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,"Well‐designed, well documented data from patie..."
2,"Ramam et al., 201027 India",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,Small patient number (23)
3,"Asero et el, 200228 Italy",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,"No epidemiological basis, H/O multiple allergy..."
4,MDIS,NaN,NaN,NaN
5,"Schiavino et al., 200732 Italy",Clinical history √Clinical examination xSerum ...,Yes HSR not investigated/confirmed,Use of pre‐medication (sodium cromolyn or oral...
6,"De Pasquale et al., 201231 Italy",Clinical history √Clinical examination √Serum ...,Yes HSR not investigated/confirmed,Small number of patients (30)Female patients only
7,"Macy et al., 201230 USA",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,No allergy workupRetrospective data extraction...
8,"Omer et al., 201425 UK",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,No allergy workupRetrospective data extraction...
9,"Peter, 201633 South Africa",Clinical history √Clinical examination √Serum ...,NoHSR not investigated/confirmed,Single case study
10,MDAS & MDIS,NaN,NaN,NaN
11,"Blumenthal et al., 201826 USA",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,No allergy workupRetrospective data extraction...
12,MDI,NaN,NaN,NaN
13,"Antoniou et al., 201620 UK",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,No allergy workupRisk of referral bias from pr...
14,"Okeahialam, 201734 Nigeria",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,Number of patients (489)No allergy workupRetro...
15,MDH,NaN,NaN,NaN
16,"Gex‐Collet et al., 200538 Switzerland",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,Small number of patients (7)Tests performed at...
17,"Columbo et el, 200939 Italy",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,Small number of patients (28)
18,"Atanaskovic‐Markovic et al., 201235 Serbia",Clinical history √Clinical examination xSerum ...,Yes definition for positive prick & intraderma...,Children only.Small number (7/279) identified ...
19,"Studer et al., 201236 France",Clinical history √Clinical examination xSerum ...,Yes HSR not investigated/confirmed,Small patient number (11/1925 identified as MDH)
20,"Guvenir et al., 201937 Turkey",Clinical history √Clinical examination xSerum ...,Yes definition for immediate and delayed HSR w...,Number of patients (73)
21,MDHS,NaN,NaN,NaN
22,"Landry et al., 202040 France",Clinical history √Clinical examination xSerum ...,Yes definition for immediate and delayed HSR s...,Not all patients with alleged drug hypersensit...
23,POLYALLERGY,NaN,NaN,NaN
24,"Jimenez et al., 201942 USA",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,No allergy workupRetrospective data extraction...
25,MASS,NaN,NaN,NaN
26,"Park et al., 200041 Canada",Clinical history √Clinical examination xSerum ...,NoHSR not investigated/confirmed,Telephone calls and questionnaires to parents ...

--------------------------------------------------------------------------------

,Author,Abrocitinib group,Control group,Jadad scores
0,Number,Age [years],Female (n),Duration of atopic dermatitis [years]
1,Bieber 2021,226,38.8 ±14.5,122
2,Simpson 2020,154,33.0 ±17.4,73
3,Silverberg 2020,155,33.5 ±14.7,67
4,Gooderham 2019,55,38.7 ±17.6,27

--------------------------------------------------------------------------------

         Author Mometasone furoate group Control group Jadad scores
0        Number              Age [years]    Female (n)  Weight [kg]
1     Amar 2017                      113     8.6 (1.9)           44
2   Skoner 2011                       44           6.3           16
3  Meltzer 2007                      100     8.2 (0.2)           38
4   Berger 2006                       98     9.0 (1.8)           57

--------------------------------------------------------------------------------

,No.,Author,Abrocitinib 200 mg group,Abrocitinib 100 mg group,Jada scores
0,Number,Age [years],Female (n),Duration of atopic dermatitis [year],EASI score
1,1,Bieber 2021,226,38.8 ±14.5,122
2,2,Simpson 2020,154,33.0 ±17·4,73
3,3,Silverberg 2020,155,33.5 ±14.7,67
4,4,Gooderham 2019,55,38.7 ±17.6,27

--------------------------------------------------------------------------------

,Unnamed: 0,8 shortlisted CPGs,Other CPGs
0,Mean Score (SD) (%),Mean Score (SD) (%),NaN
1,AGREE II Domains,NaN,NaN
2,Scope and Purpose,92.07 (4.43),58.41 (22.15)
3,Stakeholder involvement,89.19 (7.61),41.81 (18.76)
4,Rigour of Development,87.80 (6.48),31.85 (19.68)
5,Clarity and presentation,85.91 (8.70),72.98 (10.88)
6,Applicability,60.57 (12.51),23.75 (9.62)
7,Editorial Independence,82.89 (20.44),43.18 (27.94)
8,AGREE-REX Domains,NaN,NaN
9,Clinical applicability,88.20 (3.64),50.36 (15.42)
10,Values & Preferences,72.69 (14.78),23.11 (9.45)
11,Implementability,78.57 (10.04),42.86 (15.20)
12,AGREE-REX Overall scores,NaN,NaN
13,Overall recommendations for use in the appropr...,1.11 (0.10),2.19 (0.50)
14,Overall recommendations for use in my context,1.29 (0.22),2.27 (0.43)

--------------------------------------------------------------------------------

                    Author FP/FORM group FP/SAL group        Jadad scores
0                   Number   Age [years]   Female (n)  Predicted FEV1 (%)
1           Ploszczuk 2018           167    8.4 ±1.81                  58
2              Emeryk 2016           106    8.8 (2.1)                  34
3  Bodzenta- Lukaszyk 2010           101            –                   –

--------------------------------------------------------------------------------

,Study,Representativeness of the exposed cohort,Selection of the non-exposed cohort,Ascertainment of exposure,Demonstration that outcome of interest was not present at start of the study,Comparability of cohorts,Assessment of outcome,Was follow up long enough for outcomes to occur,Adequacy,Total
0,Eun S et al. (2019),+,–,+,+,++,+,+,+,8
1,Gaig P et al. (2004),+,–,–,+,++,–,+,+,6
2,Jo YH et al. (2022),+,–,+,+,++,+,+,+,8
3,Wertenteil S et al. (2019),+,–,+,+,++,+,+,+,8
4,Asero R et al. (2020),+,+,+,+,++,+,+,+,9
5,Gregoriou et al. (2009),+,–,+,+,++,+,+,+,8
6,Savic S et al. (2020),+,–,+,+,+,+,+,–,7
7,Aktar S. et al. (2015),+,+,+,+,++,+,+,+,9
8,Kolkhir P et al. (2020),+,–,+,+,+,+,+,+,7
9,Kurt E et al. (2011),+,–,+,+,+,+,+,+,7
10,Anis O et al. (2023),+,+,+,+,++,+,+,+,9
11,Chen H et al. (2016),+,–,+,+,+,+,+,+,7
12,Chiu HY et al. (2018),+,–,+,+,++,+,+,+,8
13,Confino-Cohen R et al. (2012),+,+,+,+,++,+,+,+,9
14,Ghazanfar M et al. (2020),+,+,+,+,++,+,+,+,9
15,Gupta P et al. (2023),+,–,+,+,++,+,+,+,8
16,Kolkhir P et al. (2021),+,–,+,+,++,+,+,+,8
17,Kokaturk E et al. (2021),+,–,+,+,+,+,+,+,7
18,Grieco T et al. (2020),+,–,+,+,++,+,+,+,8
19,Tagka A et al. (2021),+,–,+,+,++,+,+,+,8
20,Sirufo M et al. (2021),+,–,+,+,++,+,+,+,8
21,Sommer R. et al. (2020),+,–,+,+,++,+,+,+,8
22,De Ue et al. (2011),+,–,+,+,++,+,+,+,8
23,Erol K et al. (2020),+,–,+,+,++,+,+,+,8
24,Sanchez-Diaz M et al. (2023),+,–,+,+,++,+,+,+,8
25,Silvares M et al. (2011),+,–,+,+,++,+,+,+,8

--------------------------------------------------------------------------------

                        Studies Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10
0           Davis et al, 200023  U  Y  Y  Y  Y  N  N  Y  U   Y
1           Walsh et al, 200021  Y  Y  Y  Y  Y  N  Y  Y  U   Y
2        Lindberg et al, 200125  U  Y  Y  Y  Y  Y  Y  Y  Y   Y
3   Scherman & Löwhagen, 200430  Y  Y  Y  Y  Y  N  Y  Y  Y   Y
4          Gamble et al, 200729  Y  Y  Y  Y  Y  N  Y  Y  Y   Y
5          Peláez et al, 201427  N  Y  Y  Y  Y  N  N  Y  Y   Y
6          George et al, 201532  N  Y  Y  Y  Y  N  Y  Y  Y   Y
7          Peláez et al, 201624  N  Y  Y  Y  Y  N  Y  Y  N   Y
8        Hedenrud et al, 201922  Y  Y  Y  Y  Y  Y  Y  Y  Y   Y
9          Norful et al, 202028  Y  Y  Y  Y  Y  N  Y  Y  Y   Y
10  Ardura-Garcia et al, 202126  Y  Y  Y  Y  Y  N  Y  Y  Y   Y
11        Wadhahi et al, 202231  Y  Y  Y  Y  Y  N  Y  Y  Y   Y

--------------------------------------------------------------------------------

,Study,Age [years],Male,Treatment,No. of patients,Background therapy,Duration,Efficiency outcomes,Safety outcomes
0,Emma 2021 (1),32.7 ±15.87,52.90%,15 mg QD,239 (adults)64 (adolescents),Topical nonmedicated emollients,16 weeks,①②,③④⑤⑥⑦⑧
1,30 mg QD,243 (adults)64 (adolescents),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Placebo,241 (adults)61 (adolescents),NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Emma 2021 (2),32.1 ±15.66,55.30%,15 mg QD,243 (adults)58 (adolescents),Topical nonmedicated emollients,16 weeks,①②,③④⑤⑥⑦⑧
4,30 mg QD,247 (adults)62 (adolescents),NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Placebo,242 (adults)60 (adolescents),NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Kristian 2021,32.8 ±15.29,59.90%,15 mg QD,261 (adults)60 (adolescents),Topical corticosteroids,16 weeks,①②,③④⑤⑥⑦⑧
7,30 mg QD,260 (adults)60 (adolescents),NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Placebo,264 (adults)63 (adolescents),NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Emma 2020,39.9 ±15.77,62.30%,7.5 mg QD,42 (adults),Topical nonmedicated emollients,16 weeks,①②,③④⑤⑥⑦⑧
10,15 mg QD,42 (adults),NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,30 mg QD,42 (adults),NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Placebo,41 (adults),NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

## Reference Inspection
# 

Let's see what RoB references were found in the documents.

In [5]:
print("\n" + "=" * 80)
print("INSPECTING IDENTIFIED RoB REFERENCES")
print("=" * 80 + "\n")

df_refs = reader.get_all_references_dataframe()
if not df_refs.empty:
    # Filter for references that match our RoB criteria
    rob_dois = ['10.1136/bmj.d5928', '10.1136/bmj.l4898', 'd5928', 'l4898']
    rob_keywords = ['risk of bias', 'cochrane collaboration', 'rob 2', 'rob2']
    
    is_rob = df_refs['doi'].fillna('').str.lower().apply(
        lambda x: any(d.lower() in x for d in rob_dois)
    ) | df_refs['text'].fillna('').str.lower().apply(
        lambda x: any(k in x for k in rob_keywords)
    )
    
    found_rob_refs = df_refs[is_rob]
    print(f"Found {len(found_rob_refs)} unique RoB-related bibliographic entries across documents.")
    display(found_rob_refs[['paper_id', 'ref_id', 'doi', 'title', 'year']])
else:
    print("No references found in the export.")

================================================================================
INSPECTING IDENTIFIED RoB REFERENCES
================================================================================

Found 97 unique RoB-related bibliographic entries across documents.

,paper_id,ref_id,doi,title,year
299,PMC11694227,B24,10.1136/bmj.l4898,Rob 2: a revised tool for assessing risk of bi...,2019
638,PMC10420062,B7,10.1136/bmj.l4898,Rob 2: a revised tool for assessing risk of bi...,2019
836,PMC11370728,B37,NaN,NaN,2020
1035,PMC8588837,bib20,10.1016/j.jclinepi.2011.11.014,Assessing risk of bias in prevalence studies: ...,2012
1432,PMC9483654,bib18,NaN,NaN,2011
...,...,...,...,...,...
15464,PMC9236485,cit0023,10.1136/bmj.l4898,RoB 2: a revised tool for assessing risk of bi...,2019
15465,PMC9236485,cit0024,10.1136/bmj.i4919,ROBINS-I: a tool for assessing risk of bias in...,2016
15494,PMC9326918,cit0020,10.1136/bmj.d5928,The Cochrane Collaboration’s tool for assessin...,2011
16265,PMC11415968,bib57,10.1136/bmj.l4898,RoB 2: a revised tool for assessing risk of bi...,Aug 28 2019
16269,PMC11415968,bib61,NaN,NaN,2023