# Find and Display Risk of Bias (RoB) Tables

This script demonstrates the enhanced `ExportReader` capabilities for identifying
Risk of Bias tables using "smart search" based on references and citations.

%% [markdown]
## Import Required Libraries

In [2]:
import pandas as pd
from pathlib import Path
from IPython.display import display, HTML

# Import the export reader library
from scraper.export_reader import load_latest_export

## Load the Export Data

In [3]:
# Load the latest export
try:
    reader = load_latest_export()
    reader.print_summary()
except Exception as e:
    print(f"Error loading export: {e}")
    # Fallback or exit if no export found
    exit(1)

Loading latest export: processed_export_1780342516.json
============================================================
EXPORT SUMMARY
============================================================
Total documents: 283
Export file: /home/jgrzyb/Documents/Python/ai4es-oa-paper-scrapper/notebooks/paper_pipeline_data/exports/processed_export_1780342516.json

Documents by source:
source
pmc      264
arxiv     19

Total tables: 2387
Total images: 1727

Document sections:
  Min sections: 0
  Max sections: 49
  Avg sections: 17.5

============================================================

## Smart Search for RoB Tables
# 

Instead of searching for "method" or "risk of bias" in section titles, 
we search for sections that cite foundational RoB literature (Higgins 2011, Sterne 2019).

In [4]:
print("=" * 80)
print("SMART SEARCH: FINDING TABLES BY CITATION")
print("=" * 80 + "\n")

# Use the new find_rob_tables method
df_rob_tables = reader.find_rob_tables()

if df_rob_tables.empty:
    print("❌ No RoB tables found using the smart search.")
    print("This might be because the papers don't cite the standard RoB tools,")
    print("or the citations weren't extracted correctly.")
else:
    print(f"✅ Found {len(df_rob_tables)} tables citing Risk of Bias tools!\n")
    display(df_rob_tables[['paper_id', 'section', 'matched_rob_refs', 'csv_path']])

================================================================================
SMART SEARCH: FINDING TABLES BY CITATION
================================================================================

✅ Found 31 tables citing Risk of Bias tools!

,paper_id,section,matched_rob_refs,csv_path
0,PMC9483654,Results,[bib18],tables/PMC9483654/table_0.csv
1,PMC9483654,Results,[bib18],tables/PMC9483654/table_1.csv
2,PMC9483654,Results,[bib18],tables/PMC9483654/table_2.csv
3,PMC7552599,Risk of Bias,[Paper cites RoB tools (heading match)],tables/PMC7552599/table_3.csv
4,PMC11939832,Comparison and Effects of Interventions,[B26],tables/PMC11939832/table_3.csv
5,PMC9993208,Results,[cit0030],tables/PMC9993208/table_0.csv
6,PMC9993208,Results,[cit0030],tables/PMC9993208/table_1.csv
7,PMC11541770,Results,[bib20],tables/PMC11541770/table_0.csv
8,PMC11541770,Results,[bib20],tables/PMC11541770/table_1.csv
9,PMC11541770,Results,[bib20],tables/PMC11541770/table_2.csv
10,PMC11541770,Results,[bib20],tables/PMC11541770/table_3.csv
11,PMC9290056,SYSTEMATIC REVIEW OF AVAILABLE EVIDENCE,[all15076-bib-0008],tables/PMC9290056/table_0.csv
12,PMC11187334,Risk of bias,[Paper cites RoB tools (heading match)],tables/PMC11187334/table_5.csv
13,PMC10258714,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC10258714/table_1.csv
14,PMC11770579,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC11770579/table_1.csv
15,PMC9993210,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC9993210/table_1.csv
16,PMC6218986,Risk of Bias in included studies,[Paper cites RoB tools (heading match)],tables/PMC6218986/table_1.csv
17,PMC10516441,Methods,[B24],tables/PMC10516441/table_0.csv
18,PMC10516441,Methods,[B24],tables/PMC10516441/table_1.csv
19,PMC10516441,Methods,[B24],tables/PMC10516441/table_2.csv
20,PMC10646712,"Literature search, study characteristics, and ...",[Paper cites RoB tools (heading match)],tables/PMC10646712/table_1.csv
21,PMC9704462,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC9704462/table_1.csv
22,PMC11005196,Risk of bias results,[CR23],tables/PMC11005196/table_7.csv
23,PMC8501420,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC8501420/table_1.csv
24,PMC4064110,Risk of bias,[Paper cites RoB tools (heading match)],tables/PMC4064110/table_3.csv
25,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_4.csv
26,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_5.csv
27,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_6.csv
28,PMC11193836,Study Selection,[CR34],tables/PMC11193836/table_7.csv
29,PMC8501448,"Literature search, study characteristics and q...",[Paper cites RoB tools (heading match)],tables/PMC8501448/table_1.csv
30,PMC9326918,Study characteristics and risk of bias,[Paper cites RoB tools (heading match)],tables/PMC9326918/table_1.csv

## Display Filtered Tables

In [5]:
def show_table(row_index, df_source):
    """Display a specific table from a given dataframe."""
    row = df_source.iloc[row_index]
    
    # Display metadata
    header = f"""
    <div style="background-color: #e8f4f8; padding: 10px; border-radius: 5px; margin-bottom: 10px; border-left: 5px solid #2980b9;">
        <b>RoB Table #{row_index + 1}</b> | Paper: <b>{row['paper_id']}</b> | Section: <i>{row['section']}</i>
        <br>Matched References: {', '.join(row['matched_rob_refs'])}
    </div>
    """
    display(HTML(header))
    
    # Load and display the table
    try:
        df = reader.load_table_csv(row['csv_path'])
        display(df)
    except FileNotFoundError as e:
        print(f"❌ Error loading table: {e}")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
    
    print("-" * 80)

# Display identified tables
if not df_rob_tables.empty:
    display_limit = min(10, len(df_rob_tables))
    print(f"Displaying top {display_limit} RoB tables...\n")
    
    for i in range(display_limit):
        try:
            show_table(i, df_rob_tables)
        except Exception as e:
            print(f"Error displaying table {i}: {e}")
            continue

Displaying top 10 RoB tables...

   Characteristics of studies with median or mean number of ARTIs without SD or SE or a difference between them
0                                              Author
1                                        Caramia 1994
2                               Carriere-Roussel 2017
3                                           Chen 2004
4                                           Dils 1979
5                                        Fiocchi 1988
6                                          Longo 1988
7                                       Passali 1994a
8                                          Pozzi 2004
9                                  Riedl-Seifert 1995
10                                       Schaad 2010b
11  Characteristics of the studies reporting clini...
12                                       Fiocchi 1989
13                                    Giovannini 2000
14                                          Mora 2002
15                                          Mora 2007
16                                         Renzo 2004
17  Characteristics of the studies reporting the p...
18                                        Burgio 1994
19                                      Careddu 1994b
20                                       Göhring 2017
21                                        Fukuda 1999
22                                         Mora 2010a
23                                    Padayachee 2014
24                                         Paupe 1991
25                                   Rutishauser 1998
26                                    Santamaria 2019
27                                        Taylor 2003
28                                          Wahl 2008
29  Characteristics of the Studies Reporting Diver...
30                                    Andrianova 2003
31                                        Collet 1993
32                              Espinosa Rosales 2009
33                                       Fiocchi 2012
34                                     Iuldashev 1988
35                                        Mameli 2015
36                                 Martin du Pan 1982
37                                        Sramek 1986

--------------------------------------------------------------------------------

               Author, year                        Reasons for their exclusion
0             Almeida, 1999             Participants with asthma were included
1            Banovcin, 1992  The trial was not double-blind or placebo-cont...
2                Barr, 1965                      Trial with asthmatic children
3             Barrett, 2010                  Children and adults were included
4               Braido 2014                         Clinical trial with adults
5             Carlone, 2014                         Clinical trial with adults
6             Colombo, 2014                     Not a placebo-controlled trial
7                 Das, 2000              Participants' ages were not specified
8     Doody-Oppikofer, 1998  The study examined only the acute phase of inf...
9               Erman, 2009             A poorly defined homeopathic treatment
10         Fintelmann, 2012                         Clinical trial with adults
11            Fontana, 1965            Clinical trial with children and adults
12           Graubaum, 2012                         Clinical trial with adults
13           Grimfeld, 2004             An antihistamine was used in the trial
14              Grimm, 1999  Children and adults were not separated in the ...
15              Heinz, 2010                         Clinical trial with adults
16      Herrera-Basto, 1998  Researchers compared the effect of pidotimod o...
17              Jawad, 2012                         Clinical trial with adults
18            Jesenak, 2013            Trials comparing vitamin C with placebo
19        Kondrat'eva, 2009             A poorly defined homeopathic treatment
20       Kozhukharova, 1987  The trial was not double-blind or placebo-cont...
21              Kudin, 2009             A poorly defined homeopathic treatment
22          Lauriello, 1990  Researchers compared the effect of the interve...
23                Lee, 2012                         Clinical trial with adults
24             Licari, 2014  The trial was not double-blind or placebo-cont...
25          Luchikhin, 2000  The trial was not double-blind or placebo-cont...
26                 Ma, 1994  The trial was not double-blind or placebo-cont...
27             Macchi, 2005                         Clinical trial with adults
28       Makovetskaya, 2001  The trial was not double-blind or placebo-cont...
29          Mohammadi, 2014                     Not a placebo-controlled trial
30              Mora, 2010b  A trial without the prevention approach for ac...
31            Mueller, 1969             Participants with asthma were included
32  Namazova-Baranova, 2015                     Not a placebo-controlled trial
33            Nespoli, 1992                     Not a placebo-controlled trial
34    Obrosova-Serova, 1972  The trial was not double-blind or placebo-cont...
35            Oggiano, 1985                           Open trial with children
36             Oldini, 1990  Children and adults were not separated in the ...
37   Ortega del Alamo, 2005  Researchers compared the effect of the interve...
38              Predy, 2005                         Clinical trial with adults
39             Prusek, 1987                     Not a placebo-controlled trial
40               Razi, 2010             Participants with asthma were included
41         Rosaschino, 2004                                         Open trial
42              Rossi, 2004                         Clinical trial with adults
43               Ruah, 2001                     Not a placebo-controlled trial
44              Rytel, 1974                         Clinical trial with adults
45             Scotti, 1987                     Not a placebo-controlled trial
46             Sly PD, 2019  Only related to lower respiratory tract infect...
47         Steinsbekk, 2005             A poorly defined homeopathic treatment
48          Tiralongo, 2012                         Clinical trial with adults
49           Vascotto, 1985                     Not a placebo-controlled trial
50               Yale, 2004                         Clinical trial with adults
51           Zagólski, 2015                     Not a placebo-controlled trial

--------------------------------------------------------------------------------

  Patient or population: children aged under 18 years of age susceptible to acute respiratory tract infections from clinics, private practices, hospital departments, schools, orphanages, etc.Intervention: Any immunostimulant with a trial period of 3–12 months.Comparison: PlaceboO: Number of ARTIs per treatment group during the study periodS: Randomized controlled trialsT: Trials of 3–12 months duration published from January 1965 to January 10, 2022).
0                                           Outcomes
1                                       Assumed risk
2                                            Placebo
3                                    Number of ARTIs
4                               Ratio of Means ARTIs
5       Incidence of gastrointestinal adverse events
6                   Incidence of skin adverse events

--------------------------------------------------------------------------------

,Item,External validity,Internal validity,Overall Score
0,1. Was the study’s target population a close r...,2. Was the sampling frame a true or close repr...,3. Was some form of random selection used to s...,4. Was the likelihood of nonresponse bias mini...
1,"Altin, 2020 [45]",0,1,1
2,"Barillari, 2020 [46]",1,1,0
3,"Beltrán-Corbellini, 2020 [47]",0,1,0
4,"Bénézit, 2020 [27]",0,1,1
...,...,...,...,...
57,"Wi, 2020 [78]",0,1,1
58,"Yan, 2020a [8]",0,0,1
59,"Yan, 2020b [15]",0,1,1
60,"Zayet, 2020a [43]",0,1,1
61,"Zayet, 2020b [44]",0,1,1

--------------------------------------------------------------------------------

,Outcome measurement,"RCTs, n","Comparisons, n","Patients, n",Effect (95% confidential intervals),Certainty of the evidence (GRADE),Comments
0,RQLQ sleep domain,8,12,"3,961",SMD: 0.292 (0.235 to 0.350),⊕⊕⊕◯ Moderatea,Significant improvement in sleep quality among...
1,Nocturnal Rhinoconjunctivitis Quality of Life ...,1,2,"1,068",SMD: 0.284 (0.164 to 0.404),⊕⊕⊕⊕ High,"Improvement observed, but evidence is limited ..."
2,Epworth Sleepiness Scale,2,2,74,SMD: 0.027 (−0.429 to 0.483),⊕⊕⊕◯ Moderateb,No significant improvement in sleepiness
3,Sensitivity Analysis: RQLQ sleep domain exclud...,6,8,"2,799",SMD: 0.304 (0.235 to 0.373),⊕⊕⊕⊕ High,Significant improvement in sleep quality among...
4,Subgroup Analysis: RQLQ sleep domain for patie...,4,6,"2,018",SMD: 0.329 (0.250 to 0.408),⊕⊕⊕⊕ High,Significant improvement in sleep quality among...
5,Subgroup Analysis: RQLQ sleep domain for patie...,4,6,"1,943",SMD: 0.252 (0.168 to 0.336),⊕⊕◯◯ Lowc,Low certainty evidence suggests significant im...

--------------------------------------------------------------------------------

,Author,Year,Study design,Country,Age,LUS probe,Lung fields,Diagnostic LUS findings,LUS/CXR,Patients,Pneumonia,TP,TN,FP,FN
0,Caiulo [31],2013,Prospective,Italy,1–16 y,Linear,6.0,"ConsolidationsFBL, PLA",LUS,102.0,89.0,88.0,13.0,0.0,1.0
1,CXR,81,13,0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Reali [32],2014,Prospective,Italy,0–16 y,Linear,4.0,ConsolidationsFBL,LUS,107.0,81.0,76.0,25.0,1.0,5.0
3,CXR,66,24,2,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dianova [33],2015,Prospective,Russia,0–18 y,"Linear,convex",6.0,Consolidations,LUS,154.0,154.0,147.0,0.0,0.0,7.0
5,CXR,126,0,0,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Iorio [34],2015,Retrospective,Italy,0–12 y,Linear,6.0,Consolidations,LUS,52.0,29.0,28.0,22.0,1.0,1.0
7,CXR,25,22,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ho [35],2015,Retrospective,Taiwan,73.2 m,Convex,6.0,Consolidations,LUS,163.0,163.0,159.0,0.0,0.0,4.0
9,CXR,151,0,0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Urbankowska [36],2015,Prospective,Poland,0–18 y,Linear,6.0,Consolidations,LUS,106.0,106.0,71.0,0.0,5.0,30.0
11,CXR,76,0,0,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Guerra [37],2016,Prospective,Italy,0–16,"Convex, Linear",6.0,Consolidations,LUS,222.0,222.0,207.0,0.0,7.0,8.0
13,CXR,197,0,17,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Yadav [38],2017,Prospective,India,0–5,Micro convex,6.0,"Consolidations,PE, FBL",LUS,118.0,106.0,105.0,0.0,0.0,13.0
15,CXR,101,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Sharif [39],2021,Prospective,Pakistan,2–12 y,Linear,6.0,Consolidation,LUS,100.0,64.0,64.0,0.0,0.0,36.0
17,CXR,50,0,0,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

,Author,LUS/CXR,Sensitivity (95% CI),Specificity (95% CI),Positive predictive value (95% CI),Negative predictive value (95% CI)
0,Caiulo [31],LUS,98.9% (93.9–100),100% (75.3–100),100% (95.9–100),92.9% (66.1–99.8)
1,CXR,91% (83.1–96.0),100% (75.3–100),100% (95.5–100),61.9% (38.4–81.9),NaN
2,Reali [32],LUS,93.8% (86.2–98.0),96.2% (80.4–99.9),98.7% (93.0–100),86.2% (68.3–96.1)
3,CXR,81.5% (71.3–89.2),92.3% (74.9–99.1),97.1% (89.8–99.6),61.5% (44.6–76.6),NaN
4,Dianova [33],LUS,95.5% (90.0–98.2),NaN,100% (97.5–100),0.0% (0.0–41.0)
5,CXR,81.8% (74.8–87.6),NaN,100% (97.1–100),0.0% (0–12.3),NaN
6,Iorio [34],LUS,96.6% (82.2–99.9),95.7% (78.1–99.9),96.6% (82.2–99.9),95.7% (78.1–99.9)
7,CXR,86.2% (68.3–96.1),95.7% (78.1–99.9),96.2% (80.4–99.9),84.6% (65.1–95.6),NaN
8,Ho [35],LUS,97.5% (93.8–99.3),NaN,100% (97.7–100),0.0% (0.0–60.2)
9,CXR,92.6% (87.5–96.1),NaN,100% (97.0–100),0.0% (0.0–26.5),NaN
10,Urbankowska [36],LUS,93.0% (85.0–98.0),100% (88.0–100),100% (95.9–100),0.0% (0.0–41.0)
11,CXR,100% (95.0–100),100% (88.0–100),100% (95.5–100),0.0% (0–12.3),NaN
12,Guerra [37],LUS,97.0% (93.0–99.0),100% (63.0–100),100% (95.9–100),0.0% (0.0–41.0)
13,CXR,92% (88.0–95.0),100% (63.0–100),100% (95.5–100),0.0% (0–12.3),NaN
14,Yadav [38],LUS,89.0% (81.9–94.0),NaN,100% (96.5–100),0.0% (0.0–24.7)
15,CXR,85.6% (77.9–91.4),NaN,100% (96.4–100),0.0% (0.0–19.5),NaN
16,Sharif [39],LUS,100% (93.0–100),92.3% (63.0–99.9),95.31% (95.9–99.9),100% (78.1–100)
17,CXR,81.96% (80.0–95.0),100% (63.0–100),100% (95.5–100),78.0% (68.3–96.1),NaN
18,Total,LUS,95.5% (93.6–97.1),96.3% (92.1–98.4),99.0% (97.8–99.8),63.6% (40.7–82.7)
19,CXR,87.4% (84.3–90.0),98.6% (95.8–99.6),99.5% (99.1–99.9),44.6% (20.4–68.3),NaN

--------------------------------------------------------------------------------

,Source (study code),Country (centers),Intent-to-Treat vs. Placebo Participants,Male sex (%),"Age, Mean (Range), y","Asthma, %","Poly-Sensitization, %",Severity of ARC,"Treatment Duration (Preseason + Grass Pollen Season), wks."
0,"Didier, 2007 (VO34.04)",10 countries in Europe (n = 42),"155 vs. 156 randomized,133 vs. 146 completed,1...",56.9,28.9 (18–45),10,54.5,Moderate or severe,16 + 4
1,"Wahn, 2009 (VO52.06)",5 countries in Europe (n = 29),"139 vs. 139 randomized,131 vs. 135 completed,1...",64.3,10.9 (4–17),21.4,59,Moderate or severe,16 + 6
2,"Cox, 2012 (VO61.08USA)",UnitedStates (n = 51),"233 vs. 240 randomized,207 vs. 223 completed,2...",46.6,37.2 (18–65),20.1,78,Severe,18 + 6
3,Horak 2009§ (VO56.07A),Austria (n = 1),"45 vs. 44 randomized,42 vs. 40 completed,45 vs...",41.6,27.3 (18–50),n.r.,n.r.,Moderate or severe,16
4,Long-term study,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Didier 2011 (VO53.06),"10 countries in Europe, Canada, and Russia (n ...","207 vs. 219 randomized,1st year189 vs. 204 com...",62.2,30.5 (18–49),15.3,60.6,Severe,16 + 7 (1st year)16 + 8 (2nd year)16 + 8 (3rd ...

--------------------------------------------------------------------------------

               A. Symptom score1. Fixed effects model
0                                             Studies
1                         5 studies26, 27, 28, 29, 30
2                             4 studies26, 27, 28, 29
3                                 3 studies26, 27, 28
4                                                 NaN
5   2. Subgroup analysis under the random-effects ...
6                                           Subgroups
7                                                 NaN
8                       Adults26,28, 29, 30Children27
9                              Europe26,27,29,30USA28
10               Asthma (>20%)27,28Asthma (<20%)26,30
11                                                NaN
12          B. Medication score1. Fixed effects model
13                                            Studies
14                                                NaN
15                             4 studies26, 27, 28,30
16                                                NaN
17  2. Subgroup analysis under the random-effects ...
18                                          Subgroups
19                                                NaN
20                           Adults26,28,30Children27
21                                Europe26,27,30USA28
22               Asthma (>20%)27,28Asthma (<20%)26,30

--------------------------------------------------------------------------------

,Certainty assessment,№ of patients,Effect,Certainty,Importance
0,№ of studies,Study design,Risk of bias,Inconsistency,Indirectness
1,Symptom score (follow-up: mean 1 years; assess...,NaN,NaN,NaN,NaN
2,5,randomized trials,not serious,not serious,not serious
3,Medication score (follow-up: mean 1 years; ass...,NaN,NaN,NaN,NaN
4,4,randomized trials,not serious,not serious,not serious

--------------------------------------------------------------------------------

## Reference Inspection
# 

Let's see what RoB references were found in the documents.

In [6]:
print("\n" + "=" * 80)
print("INSPECTING IDENTIFIED RoB REFERENCES")
print("=" * 80 + "\n")

df_refs = reader.get_all_references_dataframe()
if not df_refs.empty:
    # Filter for references that match our RoB criteria
    rob_dois = ['10.1136/bmj.d5928', '10.1136/bmj.l4898', 'd5928', 'l4898']
    rob_keywords = ['risk of bias', 'cochrane collaboration', 'rob 2', 'rob2']
    
    is_rob = df_refs['doi'].fillna('').str.lower().apply(
        lambda x: any(d.lower() in x for d in rob_dois)
    ) | df_refs['text'].fillna('').str.lower().apply(
        lambda x: any(k in x for k in rob_keywords)
    )
    
    found_rob_refs = df_refs[is_rob]
    print(f"Found {len(found_rob_refs)} unique RoB-related bibliographic entries across documents.")
    display(found_rob_refs[['paper_id', 'ref_id', 'doi', 'title', 'year']])
else:
    print("No references found in the export.")

================================================================================
INSPECTING IDENTIFIED RoB REFERENCES
================================================================================

Found 97 unique RoB-related bibliographic entries across documents.

,paper_id,ref_id,doi,title,year
299,PMC11694227,B24,10.1136/bmj.l4898,Rob 2: a revised tool for assessing risk of bi...,2019
638,PMC10420062,B7,10.1136/bmj.l4898,Rob 2: a revised tool for assessing risk of bi...,2019
836,PMC11370728,B37,NaN,NaN,2020
1035,PMC8588837,bib20,10.1016/j.jclinepi.2011.11.014,Assessing risk of bias in prevalence studies: ...,2012
1432,PMC9483654,bib18,NaN,NaN,2011
...,...,...,...,...,...
15464,PMC9236485,cit0023,10.1136/bmj.l4898,RoB 2: a revised tool for assessing risk of bi...,2019
15465,PMC9236485,cit0024,10.1136/bmj.i4919,ROBINS-I: a tool for assessing risk of bias in...,2016
15494,PMC9326918,cit0020,10.1136/bmj.d5928,The Cochrane Collaboration’s tool for assessin...,2011
16265,PMC11415968,bib57,10.1136/bmj.l4898,RoB 2: a revised tool for assessing risk of bi...,Aug 28 2019
16269,PMC11415968,bib61,NaN,NaN,2023