In [8]:
# Import exported article JSON

# This notebook loads the aggregated export JSON, lists processed documents, and renders section tables in a form that is easy to inspect and re-import.

In [9]:
import json
from pathlib import Path
import pandas as pd

EXPORT_PATH = Path("../paper_pipeline_data/exports/processed_export_1778606250.json")


def load_export(path=EXPORT_PATH):
    path = Path(path)
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def list_documents(data):
    for idx, doc in enumerate(data, start=1):
        print(f"{idx}. {doc.get('paper_id')} [{doc.get('source')}]")


def table_to_dataframe(table):
    header = table.get("header") or []
    rows = table.get("rows") or []
    if not header:
        return pd.DataFrame(rows)
    return pd.DataFrame(rows, columns=header)


def render_document_tables(doc):
    print("\nDocument metadata:")
    print(
        {
            k: doc.get(k)
            for k in ["paper_id", "source", "pmcid", "arxiv_id", "md_path", "html_path", "authors", "emails"]
            if k in doc
        }
    )

    sections = doc.get("sections", [])
    print(f"\nSections: {len(sections)}")

    for section in sections:
        tables = section.get("tables", [])
        if not tables:
            continue

        print(f"\n## {section.get('heading', '(untitled)')}")
        for idx, table in enumerate(tables, start=1):
            df = table_to_dataframe(table)
            print(f"\nTable {idx}")
            display(df)


data = load_export()
print(f"Loaded {len(data)} documents from {EXPORT_PATH}")
list_documents(data)

Loaded 20 documents from ../paper_pipeline_data/exports/processed_export_1778606250.json
1. 10.1186/s13601-019-0278-3 [pmc]
2. 10.1186/s13601-018-0209-8 [pmc]
3. 10.1002/clt2.12283 [pmc]
4. 10.3389/falgy.2024.1499406 [pmc]
5. 10.1186/s13601-019-0268-5 [pmc]
6. 10.3389/falgy.2024.1483430 [pmc]
7. 10.3389/falgy.2021.741135 [pmc]
8. 10.1002/clt2.70003 [pmc]
9. 10.5114/ada.2023.124795 [pmc]
10. 10.1186/s13223-023-00826-y [pmc]
11. 10.1002/clt2.12207 [pmc]
12. 10.3389/falgy.2023.1211949 [pmc]
13. 10.1002/clt2.12338 [pmc]
14. 10.1159/000538049 [pmc]
15. 10.1186/s13223-021-00597-4 [pmc]
16. 10.1002/clt2.12055 [pmc]
17. 10.1016/j.jaci.2021.03.042 [pmc]
18. 10.1016/j.jaci.2020.04.058 [pmc]
19. 10.1111/all.15560 [pmc]
20. 10.1016/j.anai.2021.02.013 [pmc]

In [10]:
if data:
    choice = 1
    if len(data) > 1:
        print("\nSelect a document to render:")
        list_documents(data)
        try:
            choice = int(input("Choose document number: ").strip())
        except Exception:
            choice = 1

    choice = max(1, min(choice, len(data)))
    selected = data[choice - 1]
    render_document_tables(selected)

Select a document to render:
1. 10.1186/s13601-019-0278-3 [pmc]
2. 10.1186/s13601-018-0209-8 [pmc]
3. 10.1002/clt2.12283 [pmc]
4. 10.3389/falgy.2024.1499406 [pmc]
5. 10.1186/s13601-019-0268-5 [pmc]
6. 10.3389/falgy.2024.1483430 [pmc]
7. 10.3389/falgy.2021.741135 [pmc]
8. 10.1002/clt2.70003 [pmc]
9. 10.5114/ada.2023.124795 [pmc]
10. 10.1186/s13223-023-00826-y [pmc]
11. 10.1002/clt2.12207 [pmc]
12. 10.3389/falgy.2023.1211949 [pmc]
13. 10.1002/clt2.12338 [pmc]
14. 10.1159/000538049 [pmc]
15. 10.1186/s13223-021-00597-4 [pmc]
16. 10.1002/clt2.12055 [pmc]
17. 10.1016/j.jaci.2021.03.042 [pmc]
18. 10.1016/j.jaci.2020.04.058 [pmc]
19. 10.1111/all.15560 [pmc]
20. 10.1016/j.anai.2021.02.013 [pmc]

Document metadata:
{'paper_id': '10.1186/s13601-019-0278-3', 'source': 'pmc', 'pmcid': 'PMC6706894', 'md_path': 'paper_pipeline_data/md/PMC6706894.md', 'html_path': 'paper_pipeline_data/html/PMC6706894.html', 'authors': ['Gerasimos N. Konstantinou', 'George N. Konstantinou'], 'emails': ['gerkonst@gmail.com', 'gnkonstantinou@gmail.com']}

Sections: 23

## Results

Table 1

,Study,Type of study,Patients,Control group
0,I. Psychiatric comorbidity in CU patients (stu...,,,
1,1. Juhlin [18],Cohort study,330 CU patients,No
2,2. Pulimood et al. [19],Cohort study,20 CU patients,No
3,3. Picardi et al. [20],Cohort study,29 CU patients,No
4,4. Picardi et al. [21],Cohort study,16 CU patients,No
5,5. Staubach et al. [22],Cohort study,100 CU patients,No
6,6. Mehta et al. [23],Cohort study,50 CU patients,No
7,7. Sorour et al. [24],Cohort study,110 CU patients,No
8,II. Psychiatric comorbidity in CU patients (st...,,,
9,8. Uguz et al. [26],Case–control,89 CU patients,60 individuals
10,9. Atefi et al. [25],Case–control,30 CU patients,30 individuals
11,10. Chu et al. [17],Case–control,"177,879 CU patients","996,356 individuals"
12,11. Staubach et al. [27],Case–control,100 CU patients,96 individuals
13,12. Ozkan et al. [28],Case–control,84 CU patients,75 individuals
14,13. Lapi et al. [29],Case–control,3489 CU patients,"1,714,746 individuals"
15,III. Psychiatric comorbidity in CU patients (s...,,,
16,14. Calıkusu et al. [31],Case–control,31 CU patients,31 patients with psychogenic excoriation (PE)
17,15. Yang et al. [30],Case–control,75 CU outpatients,133 patients with tinea pedis
18,IV. Comorbidity with specific psychiatric diso...,,,
19,16. Demet et al. [33],Cohort study,7 CU,No
20,17. Sukan et al. [34],Case–control,"50 CU patients, 50 vitiligo patients",50 individuals
21,18. Chung et al. [32],Case–control,100 CU patients,60 patients with allergy
22,19. Bashir et al. [36],Cohort study,3 CU patients,No
23,20. Tuna et al. [35],Case–control,130 CU patients,100 individuals
24,V. Case reports–case series—psychiatric interv...,,,
25,21. Hashiro [37],Case report,1 CU patient with anxiety-depressive disorder,No
26,22. Gupta et al. [39],Case series,5 patients with PTSD diagnosed with CU,No
27,23. Gupta et al. [38],Case series,2 CU patients with panic disorder,No
28,VI. Other studies,,,
29,24. Seyhan et al. [40],Cohort study,636 dermatologic patients,No
30,25. Perugi et al. [41],Cohort study,347 patients with bipolar disorder,No

Table 2

                        CU patients CU patients with psychiatric comorbidity
0           Juhlin [18]
1          Cohort study         330                                       53
2  Pulimood et al. [19]
3          Cohort study          20                                       15
4   Picardi et al. [20]
5          Cohort study          29                                       10
6  Staubach et al. [22]
7          Cohort study         100                                       48
8                 Total         479                                      126
9     Pooled prevalence                                                26.3%

Table 3

                          Chronic urticaria patients Control individuals
0                  All  With psychiatric comorbidity                 All
1     Uguz et al. [26]
2   Case–control study                            89                  44
3    Atefi et al. [25]
4   Case–control study                            30                  19
5      Chu et al. [17]
6   Case–control study                       177,879              56,195
7                Total                       177,998              56,258
8                 119#                           63#                 90#
9    Pooled prevalence                                            31.6%*
10                                        52.9%#, **

Table 4

,DSM-5 classification,PatientsN/all CU patients,ControlaN/all healthy controls,p-value*
0,Prevalence per study,Pooled prevalence (%),Prevalence per study,Pooled prevalence (%)
1,"Sleep–wake disorders (e.g., insomnia disorder,...",57/110 [24]31/130 [35],88/240 (36.7%),12/100 [35]
2,Anxiety disorders (e.g. generalized anxiety di...,30/100 [22]2/50 [23]48/110 [24]24/30 [25]39/89...,197/644 (30.6%),13/30 [25]7/64 [26]
3,"Mood disorders (major depressive disorder, dys...",12/20 [19]17/100 [22]16/50 [23]39/110 [24]15/3...,195/664 (29.4%),5/30 [25]3/64 [26]
4,Trauma and stressor-related disorders (e.g. po...,5/100 [22]1/31 [31]34/100 [32],40/231 (17.3%),–
5,"Somatic symptom and related disorders (e.g., s...",17/100 [22]21/30 [25]11/100 [27]5/84 [28],54/314 (17.2%),12/30 [25]
6,Obsessive–compulsive and related disorders,4/100 [22]1/50 [23]3/110 [24]23/89 [26]3/31 [3...,36/387 (9.3%),1/64 [26]
7,Substance-related and addictive disorders (e.g...,5/100 [22]1/50 [23],6/150 (4%),–